/-
Copyright (c) 2026 Octavian Halmaghi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Octavian Halmaghi
-/
module

public import Mathlib.Algebra.Group.Subgroup.Map
public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.Nilpotent
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Virtually cyclic groups

A group is *virtually cyclic* if it has a cyclic subgroup of finite index.
Virtually cyclic groups are fundamental in geometric group theory: they are
exactly the elementary subgroups of hyperbolic groups, the groups with at most
two ends, and the conclusion of the curvature-free Margulis lemma of
Besson–Courtois–Gallot–Sambusetti.

## Main definitions and results

* `Group.IsVirtuallyCyclic` : a group with a cyclic subgroup of finite index.
* `IsCyclic.isVirtuallyCyclic`, `Group.isVirtuallyCyclic_of_finite` : cyclic
  and finite groups are virtually cyclic.
* `Group.IsVirtuallyCyclic.isVirtuallyNilpotent` : virtually cyclic groups are
  virtually nilpotent (companion to `Group.IsNilpotent.isVirtuallyNilpotent`).
* `Group.IsVirtuallyCyclic.subgroup`, `Group.IsVirtuallyCyclic.of_surjective`,
  `Group.IsVirtuallyCyclic.quotient` : closure under subgroups, surjective
  images and quotients.

Additive versions (`AddGroup.IsVirtuallyAddCyclic` and companions) are
generated by `to_additive`; the nilpotent bridge stays multiplicative-only,
as Mathlib has no additive nilpotency.

## TODO

* A finitely generated group is virtually cyclic iff it has ≤ 2 ends
  (requires ends of groups, not yet in Mathlib).
-/

@[expose] public section

namespace Group

variable (G : Type*) [Group G]

/-- A group is **virtually cyclic** if it has a cyclic subgroup of finite
index. -/
@[to_additive /-- An additive group is **virtually cyclic** if it has a cyclic
additive subgroup of finite index. -/]
def IsVirtuallyCyclic : Prop :=
  ∃ H : Subgroup G, IsCyclic H ∧ H.FiniteIndex

variable {G}

/-- A cyclic group is virtually cyclic. -/
@[to_additive]
theorem _root_.IsCyclic.isVirtuallyCyclic (hG : IsCyclic G) :
    IsVirtuallyCyclic G := by
  have := hG
  exact ⟨⊤, inferInstance, inferInstance⟩

/-- A trivial group is virtually cyclic. -/
@[to_additive]
theorem isVirtuallyCyclic_of_subsingleton [Subsingleton G] :
    IsVirtuallyCyclic G :=
  isCyclic_of_subsingleton.isVirtuallyCyclic

/-- A finite group is virtually cyclic — via the trivial subgroup, which is
cyclic and of finite index. -/
@[to_additive]
theorem isVirtuallyCyclic_of_finite [Finite G] : IsVirtuallyCyclic G := by
  have : Subsingleton (⊥ : Subgroup G) :=
    ⟨fun a b => Subtype.ext ((Subgroup.mem_bot.mp a.2).trans
      (Subgroup.mem_bot.mp b.2).symm)⟩
  exact ⟨⊥, inferInstance, ⟨Subgroup.index_ne_zero_of_finite⟩⟩

set_option linter.style.haveILetI false in
/-- A virtually cyclic group is virtually nilpotent: a cyclic group is
commutative, hence nilpotent. This slots next to
`Group.IsNilpotent.isVirtuallyNilpotent`. -/
theorem IsVirtuallyCyclic.isVirtuallyNilpotent (h : IsVirtuallyCyclic G) :
    IsVirtuallyNilpotent G := by
  obtain ⟨H, hc, hfi⟩ := h
  refine ⟨H, ?_, hfi⟩
  -- `letI`, not `have`: the goal `IsNilpotent ↥H` carries the `Group` instance
  -- as a parameter, and `(hc.commGroup).toGroup` matches `H.toGroup` only by
  -- unfolding the inlined value.
  letI : CommGroup H := hc.commGroup
  exact CommGroup.isNilpotent

/-- Every subgroup of a virtually cyclic group is virtually cyclic. The
witness is `H.subgroupOf K`, cyclic because it is isomorphic to `H ⊓ K ≤ H`,
of finite index in `K` by `Subgroup.instFiniteIndex_subgroupOf`. -/
@[to_additive]
theorem IsVirtuallyCyclic.subgroup (h : IsVirtuallyCyclic G)
    (K : Subgroup G) : IsVirtuallyCyclic K := by
  obtain ⟨H, hc, hfi⟩ := h
  have := hc
  have := hfi
  refine ⟨H.subgroupOf K, ?_, inferInstance⟩
  have hEq : H.subgroupOf K = (H ⊓ K).subgroupOf K := by
    ext x
    simp [Subgroup.mem_subgroupOf]
  have : IsCyclic (↥(H ⊓ K)) := Subgroup.isCyclic_of_le inf_le_left
  rw [hEq]
  exact (Subgroup.subgroupOfEquivOfLe inf_le_right).isCyclic.mpr inferInstance

/-- The image of a virtually cyclic group under a surjective homomorphism is
virtually cyclic. Cyclicity of the image subgroup comes from
`isCyclic_of_surjective` along `f.subgroupMap`; finiteness of its index from
`Subgroup.index_map_dvd`. -/
@[to_additive]
theorem IsVirtuallyCyclic.of_surjective {G' : Type*} [Group G']
    (f : G →* G') (hf : Function.Surjective f) (h : IsVirtuallyCyclic G) :
    IsVirtuallyCyclic G' := by
  obtain ⟨H, hc, hfi⟩ := h
  have := hc
  refine ⟨H.map f, ?_, ?_⟩
  · exact isCyclic_of_surjective _ (f.subgroupMap_surjective H)
  · refine ⟨fun h0 => hfi.index_ne_zero ?_⟩
    have hd := Subgroup.index_map_dvd (H := H) hf
    rwa [h0, zero_dvd_iff] at hd

/-- Quotients of virtually cyclic groups are virtually cyclic. -/
@[to_additive]
theorem IsVirtuallyCyclic.quotient (h : IsVirtuallyCyclic G)
    (N : Subgroup G) [N.Normal] : IsVirtuallyCyclic (G ⧸ N) :=
  h.of_surjective (QuotientGroup.mk' N) (QuotientGroup.mk'_surjective N)

end Group
