import Counterexamples.CharPZeroNeCharZero
import Counterexamples.Cyclotomic105
import Counterexamples.DirectSumIsInternal
import Counterexamples.Girard
import Counterexamples.LinearOrderWithPosMulPosEqZero
import Counterexamples.QuadraticForm
