./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Adjunctions.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Basic.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Biproducts.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Colimits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/EnoughInjectives.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/EpiMono.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/EquivalenceGroupAddGroup.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/FilteredColimits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/ForgetCorepresentable.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Images.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Injective.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Kernels.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Limits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Preadditive.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Subobject.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/ZModuleEquivalence.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/Grp/Zero.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/GrpWithZero.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/HopfAlgebraCat/Basic.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Abelian.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Adjunctions.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Algebra.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Basic.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Biproducts.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/ChangeOfRings.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Colimits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Differentials/Basic.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Differentials/Presheaf.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/EpiMono.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/FilteredColimits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Free.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Images.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Injective.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Kernels.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Limits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Monoidal/Basic.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Monoidal/Closed.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Monoidal/Symmetric.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/Abelian.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/ChangeOfRings.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/Colimits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/Limits.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/Pushforward.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/Sheafification.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Presheaf/Sheafify.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Products.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Projective.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Sheaf.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Sheaf/Abelian.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Sheaf/ChangeOfRings.lean
./scripts/fix-comments.py Mathlib/Algebra/Category/ModuleCat/Sheaf/Colimits.lean
