./scripts/fix-comments.py Mathlib/RingTheory/WittVector/Frobenius.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/FrobeniusFractionField.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/Identities.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/InitTail.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/IsPoly.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/Isocrystal.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/MulCoeff.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/MulP.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/StructurePolynomial.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/Teichmuller.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/Truncated.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/Verschiebung.lean
./scripts/fix-comments.py Mathlib/RingTheory/WittVector/WittPolynomial.lean
./scripts/fix-comments.py Mathlib/RingTheory/ZMod.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Basic.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Cofinality.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Continuum.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/CountableCover.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Divisibility.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/ENat.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Finite.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Ordinal.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/PartENat.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/SchroederBernstein.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/Subfield.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/ToNat.lean
./scripts/fix-comments.py Mathlib/SetTheory/Cardinal/UnivLE.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Basic.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Birthday.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Domineering.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Impartial.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Nim.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Ordinal.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/PGame.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/Short.lean
./scripts/fix-comments.py Mathlib/SetTheory/Game/State.lean
./scripts/fix-comments.py Mathlib/SetTheory/Lists.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/Arithmetic.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/Basic.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/CantorNormalForm.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/Exponential.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/FixedPoint.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/FixedPointApproximants.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/NaturalOps.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/Notation.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/Principal.lean
./scripts/fix-comments.py Mathlib/SetTheory/Ordinal/Topology.lean
./scripts/fix-comments.py Mathlib/SetTheory/Surreal/Basic.lean
./scripts/fix-comments.py Mathlib/SetTheory/Surreal/Dyadic.lean
./scripts/fix-comments.py Mathlib/SetTheory/Surreal/Multiplication.lean
./scripts/fix-comments.py Mathlib/SetTheory/ZFC/Basic.lean
./scripts/fix-comments.py Mathlib/SetTheory/ZFC/Ordinal.lean
./scripts/fix-comments.py Mathlib/Tactic.lean
./scripts/fix-comments.py Mathlib/Tactic/Abel.lean
./scripts/fix-comments.py Mathlib/Tactic/AdaptationNote.lean
./scripts/fix-comments.py Mathlib/Tactic/ApplyAt.lean
./scripts/fix-comments.py Mathlib/Tactic/ApplyCongr.lean
./scripts/fix-comments.py Mathlib/Tactic/ApplyFun.lean
./scripts/fix-comments.py Mathlib/Tactic/ApplyWith.lean
./scripts/fix-comments.py Mathlib/Tactic/ArithMult.lean
./scripts/fix-comments.py Mathlib/Tactic/ArithMult/Init.lean
./scripts/fix-comments.py Mathlib/Tactic/Attr/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/Attr/Register.lean
./scripts/fix-comments.py Mathlib/Tactic/Basic.lean
./scripts/fix-comments.py Mathlib/Tactic/ByContra.lean
./scripts/fix-comments.py Mathlib/Tactic/CC.lean
./scripts/fix-comments.py Mathlib/Tactic/CC/Addition.lean
./scripts/fix-comments.py Mathlib/Tactic/CC/Datatypes.lean
./scripts/fix-comments.py Mathlib/Tactic/CC/Lemmas.lean
./scripts/fix-comments.py Mathlib/Tactic/CancelDenoms.lean
./scripts/fix-comments.py Mathlib/Tactic/CancelDenoms/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/Cases.lean
./scripts/fix-comments.py Mathlib/Tactic/CasesM.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/BicategoricalComp.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/BicategoryCoherence.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/Coherence.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/Elementwise.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/Monoidal.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/MonoidalComp.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/Reassoc.lean
./scripts/fix-comments.py Mathlib/Tactic/CategoryTheory/Slice.lean
./scripts/fix-comments.py Mathlib/Tactic/Change.lean
./scripts/fix-comments.py Mathlib/Tactic/Check.lean
./scripts/fix-comments.py Mathlib/Tactic/Choose.lean
./scripts/fix-comments.py Mathlib/Tactic/Clean.lean
./scripts/fix-comments.py Mathlib/Tactic/ClearExcept.lean
./scripts/fix-comments.py Mathlib/Tactic/ClearExclamation.lean
./scripts/fix-comments.py Mathlib/Tactic/Clear_.lean
./scripts/fix-comments.py Mathlib/Tactic/Coe.lean
./scripts/fix-comments.py Mathlib/Tactic/Common.lean
./scripts/fix-comments.py Mathlib/Tactic/ComputeDegree.lean
./scripts/fix-comments.py Mathlib/Tactic/CongrExclamation.lean
./scripts/fix-comments.py Mathlib/Tactic/CongrM.lean
./scripts/fix-comments.py Mathlib/Tactic/Constructor.lean
./scripts/fix-comments.py Mathlib/Tactic/Continuity.lean
./scripts/fix-comments.py Mathlib/Tactic/Continuity/Init.lean
./scripts/fix-comments.py Mathlib/Tactic/ContinuousFunctionalCalculus.lean
./scripts/fix-comments.py Mathlib/Tactic/Contrapose.lean
./scripts/fix-comments.py Mathlib/Tactic/Conv.lean
./scripts/fix-comments.py Mathlib/Tactic/Convert.lean
./scripts/fix-comments.py Mathlib/Tactic/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/DefEqTransformations.lean
./scripts/fix-comments.py Mathlib/Tactic/DeprecateMe.lean
./scripts/fix-comments.py Mathlib/Tactic/DeriveFintype.lean
./scripts/fix-comments.py Mathlib/Tactic/DeriveToExpr.lean
./scripts/fix-comments.py Mathlib/Tactic/DeriveTraversable.lean
./scripts/fix-comments.py Mathlib/Tactic/Eqns.lean
./scripts/fix-comments.py Mathlib/Tactic/Eval.lean
./scripts/fix-comments.py Mathlib/Tactic/ExistsI.lean
./scripts/fix-comments.py Mathlib/Tactic/Explode.lean
./scripts/fix-comments.py Mathlib/Tactic/Explode/Datatypes.lean
./scripts/fix-comments.py Mathlib/Tactic/Explode/Pretty.lean
./scripts/fix-comments.py Mathlib/Tactic/ExtendDoc.lean
./scripts/fix-comments.py Mathlib/Tactic/ExtractGoal.lean
./scripts/fix-comments.py Mathlib/Tactic/ExtractLets.lean
./scripts/fix-comments.py Mathlib/Tactic/FBinop.lean
./scripts/fix-comments.py Mathlib/Tactic/FailIfNoProgress.lean
./scripts/fix-comments.py Mathlib/Tactic/FieldSimp.lean
./scripts/fix-comments.py Mathlib/Tactic/FinCases.lean
./scripts/fix-comments.py Mathlib/Tactic/Find.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/AEMeasurable.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Attr.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/ContDiff.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Decl.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Differentiable.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Elab.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/FunctionData.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Mor.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/RefinedDiscrTree.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/StateList.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Theorems.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/ToBatteries.lean
./scripts/fix-comments.py Mathlib/Tactic/FunProp/Types.lean
./scripts/fix-comments.py Mathlib/Tactic/GCongr.lean
./scripts/fix-comments.py Mathlib/Tactic/GCongr/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/GCongr/ForwardAttr.lean
./scripts/fix-comments.py Mathlib/Tactic/Generalize.lean
./scripts/fix-comments.py Mathlib/Tactic/GeneralizeProofs.lean
./scripts/fix-comments.py Mathlib/Tactic/Group.lean
./scripts/fix-comments.py Mathlib/Tactic/GuardGoalNums.lean
./scripts/fix-comments.py Mathlib/Tactic/GuardHypNums.lean
./scripts/fix-comments.py Mathlib/Tactic/Have.lean
./scripts/fix-comments.py Mathlib/Tactic/HaveI.lean
./scripts/fix-comments.py Mathlib/Tactic/HelpCmd.lean
./scripts/fix-comments.py Mathlib/Tactic/HigherOrder.lean
./scripts/fix-comments.py Mathlib/Tactic/Hint.lean
./scripts/fix-comments.py Mathlib/Tactic/ITauto.lean
./scripts/fix-comments.py Mathlib/Tactic/InferParam.lean
./scripts/fix-comments.py Mathlib/Tactic/Inhabit.lean
./scripts/fix-comments.py Mathlib/Tactic/IntervalCases.lean
./scripts/fix-comments.py Mathlib/Tactic/IrreducibleDef.lean
./scripts/fix-comments.py Mathlib/Tactic/Lemma.lean
./scripts/fix-comments.py Mathlib/Tactic/Lift.lean
./scripts/fix-comments.py Mathlib/Tactic/LiftLets.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Datatypes.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Frontend.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Lemmas.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Oracle/FourierMotzkin.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm/Datatypes.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm/Gauss.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm/PositiveVector.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm/SimplexAlgorithm.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Parsing.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Preprocessing.lean
./scripts/fix-comments.py Mathlib/Tactic/Linarith/Verification.lean
./scripts/fix-comments.py Mathlib/Tactic/LinearCombination.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/GlobalAttributeIn.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/HashCommandLinter.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/Lint.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/OldObtain.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/Style.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/TextBased.lean
./scripts/fix-comments.py Mathlib/Tactic/Linter/UnusedTactic.lean
./scripts/fix-comments.py Mathlib/Tactic/Measurability.lean
./scripts/fix-comments.py Mathlib/Tactic/Measurability/Init.lean
./scripts/fix-comments.py Mathlib/Tactic/MinImports.lean
./scripts/fix-comments.py Mathlib/Tactic/MkIffOfInductiveProp.lean
./scripts/fix-comments.py Mathlib/Tactic/ModCases.lean
./scripts/fix-comments.py Mathlib/Tactic/Monotonicity.lean
./scripts/fix-comments.py Mathlib/Tactic/Monotonicity/Attr.lean
./scripts/fix-comments.py Mathlib/Tactic/Monotonicity/Basic.lean
./scripts/fix-comments.py Mathlib/Tactic/Monotonicity/Lemmas.lean
./scripts/fix-comments.py Mathlib/Tactic/MoveAdd.lean
./scripts/fix-comments.py Mathlib/Tactic/NoncommRing.lean
./scripts/fix-comments.py Mathlib/Tactic/Nontriviality.lean
./scripts/fix-comments.py Mathlib/Tactic/Nontriviality/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Basic.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/BigOperators.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/DivMod.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Eq.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/GCD.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Ineq.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Inv.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/IsCoprime.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/LegendreSymbol.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/NatFib.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/NatSqrt.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/OfScientific.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Pow.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Prime.lean
./scripts/fix-comments.py Mathlib/Tactic/NormNum/Result.lean
./scripts/fix-comments.py Mathlib/Tactic/NthRewrite.lean
./scripts/fix-comments.py Mathlib/Tactic/Observe.lean
./scripts/fix-comments.py Mathlib/Tactic/PPWithUniv.lean
./scripts/fix-comments.py Mathlib/Tactic/Peel.lean
./scripts/fix-comments.py Mathlib/Tactic/Polyrith.lean
./scripts/fix-comments.py Mathlib/Tactic/Positivity.lean
./scripts/fix-comments.py Mathlib/Tactic/Positivity/Basic.lean
./scripts/fix-comments.py Mathlib/Tactic/Positivity/Core.lean
./scripts/fix-comments.py Mathlib/Tactic/Positivity/Finset.lean
./scripts/fix-comments.py Mathlib/Tactic/ProdAssoc.lean
./scripts/fix-comments.py Mathlib/Tactic/ProjectionNotation.lean
./scripts/fix-comments.py Mathlib/Tactic/Propose.lean
./scripts/fix-comments.py Mathlib/Tactic/ProxyType.lean
./scripts/fix-comments.py Mathlib/Tactic/PushNeg.lean
./scripts/fix-comments.py Mathlib/Tactic/Qify.lean
./scripts/fix-comments.py Mathlib/Tactic/RSuffices.lean
./scripts/fix-comments.py Mathlib/Tactic/Recall.lean
./scripts/fix-comments.py Mathlib/Tactic/Recover.lean
./scripts/fix-comments.py Mathlib/Tactic/ReduceModChar.lean
./scripts/fix-comments.py Mathlib/Tactic/ReduceModChar/Ext.lean
./scripts/fix-comments.py Mathlib/Tactic/Relation/Rfl.lean
./scripts/fix-comments.py Mathlib/Tactic/Relation/Symm.lean
./scripts/fix-comments.py Mathlib/Tactic/Relation/Trans.lean
./scripts/fix-comments.py Mathlib/Tactic/Rename.lean
./scripts/fix-comments.py Mathlib/Tactic/RenameBVar.lean
./scripts/fix-comments.py Mathlib/Tactic/Replace.lean
./scripts/fix-comments.py Mathlib/Tactic/RewriteSearch.lean
./scripts/fix-comments.py Mathlib/Tactic/Rify.lean
./scripts/fix-comments.py Mathlib/Tactic/Ring.lean
./scripts/fix-comments.py Mathlib/Tactic/Ring/Basic.lean
./scripts/fix-comments.py Mathlib/Tactic/Ring/PNat.lean
./scripts/fix-comments.py Mathlib/Tactic/Ring/RingNF.lean
./scripts/fix-comments.py Mathlib/Tactic/Sat/FromLRAT.lean
./scripts/fix-comments.py Mathlib/Tactic/Says.lean
./scripts/fix-comments.py Mathlib/Tactic/ScopedNS.lean
./scripts/fix-comments.py Mathlib/Tactic/Set.lean
./scripts/fix-comments.py Mathlib/Tactic/SetLike.lean
./scripts/fix-comments.py Mathlib/Tactic/SimpIntro.lean
./scripts/fix-comments.py Mathlib/Tactic/SimpRw.lean
./scripts/fix-comments.py Mathlib/Tactic/Simps/Basic.lean
./scripts/fix-comments.py Mathlib/Tactic/Simps/NotationClass.lean
./scripts/fix-comments.py Mathlib/Tactic/SlimCheck.lean
./scripts/fix-comments.py Mathlib/Tactic/SplitIfs.lean
./scripts/fix-comments.py Mathlib/Tactic/Spread.lean
./scripts/fix-comments.py Mathlib/Tactic/Subsingleton.lean
./scripts/fix-comments.py Mathlib/Tactic/Substs.lean
./scripts/fix-comments.py Mathlib/Tactic/SuccessIfFailWithMsg.lean
./scripts/fix-comments.py Mathlib/Tactic/SudoSetOption.lean
./scripts/fix-comments.py Mathlib/Tactic/SuppressCompilation.lean
./scripts/fix-comments.py Mathlib/Tactic/SwapVar.lean
./scripts/fix-comments.py Mathlib/Tactic/TFAE.lean
./scripts/fix-comments.py Mathlib/Tactic/Tauto.lean
./scripts/fix-comments.py Mathlib/Tactic/TermCongr.lean
./scripts/fix-comments.py Mathlib/Tactic/ToAdditive.lean
./scripts/fix-comments.py Mathlib/Tactic/ToAdditive/Frontend.lean
./scripts/fix-comments.py Mathlib/Tactic/ToExpr.lean
./scripts/fix-comments.py Mathlib/Tactic/ToLevel.lean
./scripts/fix-comments.py Mathlib/Tactic/Trace.lean
./scripts/fix-comments.py Mathlib/Tactic/TryThis.lean
./scripts/fix-comments.py Mathlib/Tactic/TypeCheck.lean
./scripts/fix-comments.py Mathlib/Tactic/TypeStar.lean
./scripts/fix-comments.py Mathlib/Tactic/UnsetOption.lean
./scripts/fix-comments.py Mathlib/Tactic/Use.lean
./scripts/fix-comments.py Mathlib/Tactic/Variable.lean
./scripts/fix-comments.py Mathlib/Tactic/WLOG.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/Calc.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/CommDiag.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/CongrM.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/Conv.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/GCongr.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/SelectInsertParamsClass.lean
./scripts/fix-comments.py Mathlib/Tactic/Widget/SelectPanelUtils.lean
./scripts/fix-comments.py Mathlib/Tactic/Zify.lean
./scripts/fix-comments.py Mathlib/Testing/SlimCheck/Functions.lean
./scripts/fix-comments.py Mathlib/Testing/SlimCheck/Gen.lean
./scripts/fix-comments.py Mathlib/Testing/SlimCheck/Sampleable.lean
./scripts/fix-comments.py Mathlib/Testing/SlimCheck/Testable.lean
./scripts/fix-comments.py Mathlib/Topology/AlexandrovDiscrete.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Affine.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Algebra.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Algebra/Rat.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/ConstMulAction.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Constructions/DomMulAct.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/ContinuousAffineMap.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/ContinuousMonoidHom.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Equicontinuity.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Field.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/FilterBasis.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Group/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Group/Compact.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Group/OpenMapping.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Group/TopologicalAbelianization.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/GroupCompletion.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/GroupWithZero.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Defs.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Group.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/GroupCompletion.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Module.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/NatInt.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Nonarchimedean.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Order.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Real.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/InfiniteSum/Ring.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Localization.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Alternating/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Cardinality.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/CharacterSpace.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Determinant.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/FiniteDimension.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/LinearPMap.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/LocallyConvex.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Multilinear/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Multilinear/Bounded.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Multilinear/Topology.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Simple.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/Star.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/StrongTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/UniformConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Module/WeakDual.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Monoid.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/MulAction.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/MvPolynomial.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Nonarchimedean/AdicTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Nonarchimedean/Bases.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Nonarchimedean/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Nonarchimedean/Completion.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/OpenSubgroup.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/Archimedean.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/Compact.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/Field.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/Floor.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/Group.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/LiminfLimsup.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/Rolle.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Order/UpperLower.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Polynomial.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/PontryaginDual.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/ProperConstSMul.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Ring/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Ring/Ideal.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Semigroup.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Star.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/StarSubalgebra.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/UniformConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/UniformField.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/UniformFilterBasis.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/UniformGroup.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/UniformMulAction.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/UniformRing.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Valued/NormedValued.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Valued/ValuationTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/Valued/ValuedField.lean
./scripts/fix-comments.py Mathlib/Topology/Algebra/WithZeroTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Baire/CompleteMetrizable.lean
./scripts/fix-comments.py Mathlib/Topology/Baire/Lemmas.lean
./scripts/fix-comments.py Mathlib/Topology/Baire/LocallyCompactRegular.lean
./scripts/fix-comments.py Mathlib/Topology/Bases.lean
./scripts/fix-comments.py Mathlib/Topology/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Bornology/Absorbs.lean
./scripts/fix-comments.py Mathlib/Topology/Bornology/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Bornology/BoundedOperation.lean
./scripts/fix-comments.py Mathlib/Topology/Bornology/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/Bornology/Hom.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Born.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHaus/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHaus/EffectiveEpi.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHaus/Limits.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHaus/Projective.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHausLike/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHausLike/EffectiveEpi.lean
./scripts/fix-comments.py Mathlib/Topology/Category/CompHausLike/Limits.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Compactum.lean
./scripts/fix-comments.py Mathlib/Topology/Category/FinTopCat.lean
./scripts/fix-comments.py Mathlib/Topology/Category/LightProfinite/AsLimit.lean
./scripts/fix-comments.py Mathlib/Topology/Category/LightProfinite/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/LightProfinite/EffectiveEpi.lean
./scripts/fix-comments.py Mathlib/Topology/Category/LightProfinite/Limits.lean
./scripts/fix-comments.py Mathlib/Topology/Category/LightProfinite/Sequence.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Locale.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/AsLimit.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/CofilteredLimit.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/EffectiveEpi.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/Limits.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/Nobeling.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/Product.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Profinite/Projective.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Stonean/Adjunctions.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Stonean/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Stonean/EffectiveEpi.lean
./scripts/fix-comments.py Mathlib/Topology/Category/Stonean/Limits.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Adjunctions.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/EffectiveEpi.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/EpiMono.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Limits/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Limits/Cofiltered.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Limits/Konig.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Limits/Products.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Limits/Pullbacks.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/OpenNhds.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Opens.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCat/Yoneda.lean
./scripts/fix-comments.py Mathlib/Topology/Category/TopCommRingCat.lean
./scripts/fix-comments.py Mathlib/Topology/Category/UniformSpace.lean
./scripts/fix-comments.py Mathlib/Topology/Clopen.lean
./scripts/fix-comments.py Mathlib/Topology/ClopenBox.lean
./scripts/fix-comments.py Mathlib/Topology/CompactOpen.lean
./scripts/fix-comments.py Mathlib/Topology/Compactification/OnePoint.lean
./scripts/fix-comments.py Mathlib/Topology/Compactness/Compact.lean
./scripts/fix-comments.py Mathlib/Topology/Compactness/Lindelof.lean
./scripts/fix-comments.py Mathlib/Topology/Compactness/LocallyCompact.lean
./scripts/fix-comments.py Mathlib/Topology/Compactness/Paracompact.lean
./scripts/fix-comments.py Mathlib/Topology/Compactness/PseudometrizableLindelof.lean
./scripts/fix-comments.py Mathlib/Topology/Compactness/SigmaCompact.lean
./scripts/fix-comments.py Mathlib/Topology/CompletelyRegular.lean
./scripts/fix-comments.py Mathlib/Topology/Connected/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Connected/LocallyConnected.lean
./scripts/fix-comments.py Mathlib/Topology/Connected/PathConnected.lean
./scripts/fix-comments.py Mathlib/Topology/Connected/Separation.lean
./scripts/fix-comments.py Mathlib/Topology/Connected/TotallyDisconnected.lean
./scripts/fix-comments.py Mathlib/Topology/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Algebra.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Bounded.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/CocompactMap.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Compact.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/CompactlySupported.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/ContinuousMapZero.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/FunctionalCalculus.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Ideals.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/LocallyConstant.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/NonUnitalFunctionalCalculus.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Ordered.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Polynomial.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Sigma.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/StarOrdered.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/StoneWeierstrass.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/T0Sierpinski.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/UniqueCFC.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Units.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/Weierstrass.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousFunction/ZeroAtInfty.lean
./scripts/fix-comments.py Mathlib/Topology/ContinuousOn.lean
./scripts/fix-comments.py Mathlib/Topology/CountableSeparatingOn.lean
./scripts/fix-comments.py Mathlib/Topology/Covering.lean
./scripts/fix-comments.py Mathlib/Topology/Defs/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Defs/Filter.lean
./scripts/fix-comments.py Mathlib/Topology/Defs/Induced.lean
./scripts/fix-comments.py Mathlib/Topology/Defs/Sequences.lean
./scripts/fix-comments.py Mathlib/Topology/DenseEmbedding.lean
./scripts/fix-comments.py Mathlib/Topology/DiscreteQuotient.lean
./scripts/fix-comments.py Mathlib/Topology/DiscreteSubset.lean
./scripts/fix-comments.py Mathlib/Topology/EMetricSpace/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/EMetricSpace/Lipschitz.lean
./scripts/fix-comments.py Mathlib/Topology/EMetricSpace/Paracompact.lean
./scripts/fix-comments.py Mathlib/Topology/ExtendFrom.lean
./scripts/fix-comments.py Mathlib/Topology/ExtremallyDisconnected.lean
./scripts/fix-comments.py Mathlib/Topology/FiberBundle/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/FiberBundle/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/FiberBundle/IsHomeomorphicTrivialBundle.lean
./scripts/fix-comments.py Mathlib/Topology/FiberBundle/Trivialization.lean
./scripts/fix-comments.py Mathlib/Topology/Filter.lean
./scripts/fix-comments.py Mathlib/Topology/GDelta.lean
./scripts/fix-comments.py Mathlib/Topology/Germ.lean
./scripts/fix-comments.py Mathlib/Topology/Gluing.lean
./scripts/fix-comments.py Mathlib/Topology/Hom/Open.lean
./scripts/fix-comments.py Mathlib/Topology/Homeomorph.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/Contractible.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/Equiv.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/HSpaces.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/HomotopyGroup.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/Path.lean
./scripts/fix-comments.py Mathlib/Topology/Homotopy/Product.lean
./scripts/fix-comments.py Mathlib/Topology/IndicatorConstPointwise.lean
./scripts/fix-comments.py Mathlib/Topology/Inseparable.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/AddCircle.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/CantorSet.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Complex.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Discrete.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/ENNReal.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/EReal.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Int.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Irrational.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Matrix.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/NNReal.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Nat.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/PNat.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Rat.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/RatLemmas.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Real.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/RealVectorSpace.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/Sign.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/TrivSqZeroExt.lean
./scripts/fix-comments.py Mathlib/Topology/Instances/ZMod.lean
./scripts/fix-comments.py Mathlib/Topology/Irreducible.lean
./scripts/fix-comments.py Mathlib/Topology/IsLocalHomeomorph.lean
./scripts/fix-comments.py Mathlib/Topology/KrullDimension.lean
./scripts/fix-comments.py Mathlib/Topology/List.lean
./scripts/fix-comments.py Mathlib/Topology/LocalAtTarget.lean
./scripts/fix-comments.py Mathlib/Topology/LocallyClosed.lean
./scripts/fix-comments.py Mathlib/Topology/LocallyConstant/Algebra.lean
./scripts/fix-comments.py Mathlib/Topology/LocallyConstant/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/LocallyFinite.lean
./scripts/fix-comments.py Mathlib/Topology/Maps/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Maps/Proper/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Maps/Proper/UniversallyClosed.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Algebra.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Antilipschitz.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Bounded.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/CantorScheme.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/CauSeqFilter.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Cauchy.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Closeds.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Completion.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Contracting.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Dilation.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/DilationEquiv.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Equicontinuity.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Gluing.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/GromovHausdorff.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/GromovHausdorffRealized.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/HausdorffDimension.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/HausdorffDistance.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Holder.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Infsep.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/IsometricSMul.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Isometry.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Kuratowski.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Lipschitz.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/MetricSeparated.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/PartitionOfUnity.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Perfect.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/PiNat.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Polish.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/ProperSpace.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/ProperSpace/Lemmas.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Pseudo/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Pseudo/Defs.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Pseudo/Lemmas.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Sequences.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/ShrinkingLemma.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/ThickenedIndicator.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Thickening.lean
./scripts/fix-comments.py Mathlib/Topology/MetricSpace/Ultra/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Metrizable/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Metrizable/ContinuousMap.lean
./scripts/fix-comments.py Mathlib/Topology/Metrizable/Uniformity.lean
./scripts/fix-comments.py Mathlib/Topology/Metrizable/Urysohn.lean
./scripts/fix-comments.py Mathlib/Topology/NhdsSet.lean
./scripts/fix-comments.py Mathlib/Topology/NoetherianSpace.lean
./scripts/fix-comments.py Mathlib/Topology/OmegaCompletePartialOrder.lean
./scripts/fix-comments.py Mathlib/Topology/Order.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Bornology.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Bounded.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Category/AlexDisc.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Category/FrameAdjunction.lean
./scripts/fix-comments.py Mathlib/Topology/Order/DenselyOrdered.lean
./scripts/fix-comments.py Mathlib/Topology/Order/ExtendFrom.lean
./scripts/fix-comments.py Mathlib/Topology/Order/ExtrClosure.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Filter.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Hom/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Hom/Esakia.lean
./scripts/fix-comments.py Mathlib/Topology/Order/IntermediateValue.lean
./scripts/fix-comments.py Mathlib/Topology/Order/IsLUB.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Lattice.lean
./scripts/fix-comments.py Mathlib/Topology/Order/LawsonTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Order/LeftRight.lean
./scripts/fix-comments.py Mathlib/Topology/Order/LeftRightLim.lean
./scripts/fix-comments.py Mathlib/Topology/Order/LeftRightNhds.lean
./scripts/fix-comments.py Mathlib/Topology/Order/LocalExtr.lean
./scripts/fix-comments.py Mathlib/Topology/Order/LowerUpperTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Monotone.lean
./scripts/fix-comments.py Mathlib/Topology/Order/MonotoneContinuity.lean
./scripts/fix-comments.py Mathlib/Topology/Order/MonotoneConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/Order/NhdsSet.lean
./scripts/fix-comments.py Mathlib/Topology/Order/OrderClosed.lean
./scripts/fix-comments.py Mathlib/Topology/Order/PartialSups.lean
./scripts/fix-comments.py Mathlib/Topology/Order/Priestley.lean
./scripts/fix-comments.py Mathlib/Topology/Order/ProjIcc.lean
./scripts/fix-comments.py Mathlib/Topology/Order/ScottTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Order/T5.lean
./scripts/fix-comments.py Mathlib/Topology/Order/UpperLowerSetTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Partial.lean
./scripts/fix-comments.py Mathlib/Topology/PartialHomeomorph.lean
./scripts/fix-comments.py Mathlib/Topology/PartitionOfUnity.lean
./scripts/fix-comments.py Mathlib/Topology/Perfect.lean
./scripts/fix-comments.py Mathlib/Topology/QuasiSeparated.lean
./scripts/fix-comments.py Mathlib/Topology/RestrictGenTopology.lean
./scripts/fix-comments.py Mathlib/Topology/Semicontinuous.lean
./scripts/fix-comments.py Mathlib/Topology/SeparatedMap.lean
./scripts/fix-comments.py Mathlib/Topology/Separation.lean
./scripts/fix-comments.py Mathlib/Topology/Separation/NotNormal.lean
./scripts/fix-comments.py Mathlib/Topology/Sequences.lean
./scripts/fix-comments.py Mathlib/Topology/Sets/Closeds.lean
./scripts/fix-comments.py Mathlib/Topology/Sets/Compacts.lean
./scripts/fix-comments.py Mathlib/Topology/Sets/Opens.lean
./scripts/fix-comments.py Mathlib/Topology/Sets/Order.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Forget.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Functors.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Init.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Limits.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/LocalPredicate.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/LocallySurjective.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Operations.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/PUnit.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Presheaf.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/PresheafOfFunctions.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Sheaf.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/EqualizerProducts.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/OpensLeCover.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/PairwiseIntersections.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/Sites.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/UniqueGluing.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafOfFunctions.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Sheafify.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Skyscraper.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Stalks.lean
./scripts/fix-comments.py Mathlib/Topology/ShrinkingLemma.lean
./scripts/fix-comments.py Mathlib/Topology/Sober.lean
./scripts/fix-comments.py Mathlib/Topology/Specialization.lean
./scripts/fix-comments.py Mathlib/Topology/Spectral/Hom.lean
./scripts/fix-comments.py Mathlib/Topology/StoneCech.lean
./scripts/fix-comments.py Mathlib/Topology/Support.lean
./scripts/fix-comments.py Mathlib/Topology/Tactic.lean
./scripts/fix-comments.py Mathlib/Topology/TietzeExtension.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/AbsoluteValue.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/AbstractCompletion.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Ascoli.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Cauchy.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Compact.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/CompactConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/CompareReals.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/CompleteSeparated.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Completion.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Equicontinuity.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Equiv.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Matrix.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Pi.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Separation.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/UniformConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/UniformConvergenceTopology.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/UniformEmbedding.lean
./scripts/fix-comments.py Mathlib/Topology/UnitInterval.lean
./scripts/fix-comments.py Mathlib/Topology/UrysohnsBounded.lean
./scripts/fix-comments.py Mathlib/Topology/UrysohnsLemma.lean
./scripts/fix-comments.py Mathlib/Topology/VectorBundle/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/VectorBundle/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/VectorBundle/Hom.lean
./scripts/fix-comments.py Mathlib/Util/AddRelatedDecl.lean
./scripts/fix-comments.py Mathlib/Util/AssertExists.lean
./scripts/fix-comments.py Mathlib/Util/AssertNoSorry.lean
./scripts/fix-comments.py Mathlib/Util/AtomM.lean
./scripts/fix-comments.py Mathlib/Util/CompileInductive.lean
./scripts/fix-comments.py Mathlib/Util/CountHeartbeats.lean
./scripts/fix-comments.py Mathlib/Util/Delaborators.lean
./scripts/fix-comments.py Mathlib/Util/DischargerAsTactic.lean
./scripts/fix-comments.py Mathlib/Util/Export.lean
./scripts/fix-comments.py Mathlib/Util/FormatTable.lean
./scripts/fix-comments.py Mathlib/Util/GetAllModules.lean
./scripts/fix-comments.py Mathlib/Util/IncludeStr.lean
./scripts/fix-comments.py Mathlib/Util/LongNames.lean
./scripts/fix-comments.py Mathlib/Util/MemoFix.lean
./scripts/fix-comments.py Mathlib/Util/Qq.lean
./scripts/fix-comments.py Mathlib/Util/SleepHeartbeats.lean
./scripts/fix-comments.py Mathlib/Util/Superscript.lean
./scripts/fix-comments.py Mathlib/Util/SynthesizeUsing.lean
./scripts/fix-comments.py Mathlib/Util/Tactic.lean
./scripts/fix-comments.py Mathlib/Util/TermBeta.lean
./scripts/fix-comments.py Mathlib/Util/Time.lean
./scripts/fix-comments.py Mathlib/Util/WhatsNew.lean
./scripts/fix-comments.py Mathlib/Util/WithWeakNamespace.lean
