./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/PairwiseIntersections.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/Sites.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafCondition/UniqueGluing.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/SheafOfFunctions.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Sheafify.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Skyscraper.lean
./scripts/fix-comments.py Mathlib/Topology/Sheaves/Stalks.lean
./scripts/fix-comments.py Mathlib/Topology/ShrinkingLemma.lean
./scripts/fix-comments.py Mathlib/Topology/Sober.lean
./scripts/fix-comments.py Mathlib/Topology/Specialization.lean
./scripts/fix-comments.py Mathlib/Topology/Spectral/Hom.lean
./scripts/fix-comments.py Mathlib/Topology/StoneCech.lean
./scripts/fix-comments.py Mathlib/Topology/Support.lean
./scripts/fix-comments.py Mathlib/Topology/Tactic.lean
./scripts/fix-comments.py Mathlib/Topology/TietzeExtension.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/AbsoluteValue.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/AbstractCompletion.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Ascoli.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Cauchy.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Compact.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/CompactConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/CompareReals.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/CompleteSeparated.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Completion.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Equicontinuity.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Equiv.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Matrix.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Pi.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/Separation.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/UniformConvergence.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/UniformConvergenceTopology.lean
./scripts/fix-comments.py Mathlib/Topology/UniformSpace/UniformEmbedding.lean
./scripts/fix-comments.py Mathlib/Topology/UnitInterval.lean
./scripts/fix-comments.py Mathlib/Topology/UrysohnsBounded.lean
./scripts/fix-comments.py Mathlib/Topology/UrysohnsLemma.lean
./scripts/fix-comments.py Mathlib/Topology/VectorBundle/Basic.lean
./scripts/fix-comments.py Mathlib/Topology/VectorBundle/Constructions.lean
./scripts/fix-comments.py Mathlib/Topology/VectorBundle/Hom.lean
./scripts/fix-comments.py Mathlib/Util/AddRelatedDecl.lean
./scripts/fix-comments.py Mathlib/Util/AssertExists.lean
./scripts/fix-comments.py Mathlib/Util/AssertNoSorry.lean
./scripts/fix-comments.py Mathlib/Util/AtomM.lean
./scripts/fix-comments.py Mathlib/Util/CompileInductive.lean
./scripts/fix-comments.py Mathlib/Util/CountHeartbeats.lean
./scripts/fix-comments.py Mathlib/Util/Delaborators.lean
./scripts/fix-comments.py Mathlib/Util/DischargerAsTactic.lean
./scripts/fix-comments.py Mathlib/Util/Export.lean
./scripts/fix-comments.py Mathlib/Util/FormatTable.lean
./scripts/fix-comments.py Mathlib/Util/GetAllModules.lean
./scripts/fix-comments.py Mathlib/Util/IncludeStr.lean
./scripts/fix-comments.py Mathlib/Util/LongNames.lean
./scripts/fix-comments.py Mathlib/Util/MemoFix.lean
./scripts/fix-comments.py Mathlib/Util/Qq.lean
./scripts/fix-comments.py Mathlib/Util/SleepHeartbeats.lean
./scripts/fix-comments.py Mathlib/Util/Superscript.lean
./scripts/fix-comments.py Mathlib/Util/SynthesizeUsing.lean
./scripts/fix-comments.py Mathlib/Util/Tactic.lean
./scripts/fix-comments.py Mathlib/Util/TermBeta.lean
./scripts/fix-comments.py Mathlib/Util/Time.lean
./scripts/fix-comments.py Mathlib/Util/WhatsNew.lean
./scripts/fix-comments.py Mathlib/Util/WithWeakNamespace.lean
