/-
Copyright (c) 2025 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib.CategoryTheory.Sites.Coverage

/-!
# 0-hypercovers

Given a coverage `J` on a category `C`, we define the tyoe
of `0`-hypercovers of an object `S : C`. They consists of a covering family
of morphisms `X i ⟶ S` indexed by a type `I₀` such that the induced presieve is in `J`.

We define this with respect to a coverage and not to a Grothendieck topology, because this
yields more control over the components of the cover.
-/

universe w' w v u

namespace CategoryTheory

open Category Limits

variable {C : Type u} [Category.{v} C]

/-- The categorical data that is involved in a `0`-hypercover of an object `S`. This
consists of a family of morphisms `f i : X i ⟶ S` for `i : I₀`. -/
structure PreZeroHypercover (S : C) where
  /-- the index type of the covering of `S` -/
  I₀ : Type w
  /-- the objects in the covering of `S` -/
  X (i : I₀) : C
  /-- the morphisms in the covering of `S` -/
  f (i : I₀) : X i ⟶ S

namespace PreZeroHypercover

variable {S T : C} (E : PreZeroHypercover.{w} S)

/-- The assumption that the pullback of `X i₁` and `X i₂` over `S` exists
for any `i₁` and `i₂`. -/
abbrev HasPullbacks := ∀ (i₁ i₂ : E.I₀), HasPullback (E.f i₁) (E.f i₂)

/-- The presieve of `S` that is generated by the morphisms `f i : X i ⟶ S`. -/
abbrev presieve₀ : Presieve S := .ofArrows _ E.f

/-- The sieve of `S` that is generated by the morphisms `f i : X i ⟶ S`. -/
abbrev sieve₀ : Sieve S := .ofArrows _ E.f

/-- The pre-`0`-hypercover defined by a single morphism. -/
@[simps]
def singleton (f : S ⟶ T) : PreZeroHypercover.{w} T where
  I₀ := PUnit
  X _ := S
  f _ := f

/-- Pullback of a pre-`0`-hypercover along a morphism. The components are `pullback f (E.f i)`. -/
@[simps]
noncomputable
def pullback₁ (f : S ⟶ T) (E : PreZeroHypercover.{w} T) [∀ i, HasPullback f (E.f i)] :
    PreZeroHypercover.{w} S where
  I₀ := E.I₀
  X i := pullback f (E.f i)
  f _ := pullback.fst _ _

/-- Pullback of a pre-`0`-hypercover along a morphism. The components are `pullback (E.f i) f`. -/
@[simps]
noncomputable
def pullback₂ (f : S ⟶ T) (E : PreZeroHypercover.{w} T) [∀ i, HasPullback (E.f i) f] :
    PreZeroHypercover.{w} S where
  I₀ := E.I₀
  X i := pullback (E.f i) f
  f _ := pullback.snd _ _

lemma presieve₀_pullback₁ [Limits.HasPullbacks C] (f : S ⟶ T) (E : PreZeroHypercover.{w} T) :
    presieve₀ (E.pullback₂ f) = E.presieve₀.pullbackArrows f := by
  refine le_antisymm ?_ ?_
  · rintro - - ⟨i⟩
    use _, _, i
  · rintro W g ⟨-, -, ⟨i⟩⟩
    use i

lemma sieve₀_pullback₁ (f : S ⟶ T) (E : PreZeroHypercover.{w} T) [∀ i, HasPullback f (E.f i)] :
    (E.pullback₁ f).sieve₀ = E.sieve₀.pullback f := by
  rw [sieve₀, sieve₀]
  refine le_antisymm ?_ ?_
  · rw [Sieve.ofArrows, Sieve.generate_le_iff]
    intro Y g ⟨i⟩
    use E.X i, pullback.snd f (E.f i), E.f i, ⟨i⟩, pullback.condition.symm
  · rintro Z g ⟨W, p, q, ⟨i⟩, hp⟩
    use pullback f (E.f i), pullback.lift g p hp.symm, pullback.fst _ _, ⟨i⟩
    simp

/-- Refining each component of a pre-`0`-hypercover yields a refined pre-`0`-hypercover of the
base. -/
@[simps]
def bind (E : PreZeroHypercover.{w} T) (F : ∀ i, PreZeroHypercover.{w'} (E.X i)) :
    PreZeroHypercover.{max w w'} T where
  I₀ := Σ (i : E.I₀), (F i).I₀
  X := fun ⟨i, j⟩ ↦ (F i).X j
  f := fun ⟨i, j⟩ ↦ (F i).f j ≫ E.f i

section Category

variable {E : PreZeroHypercover.{w} S} {F : PreZeroHypercover.{w'} S}

/-- A morphism of pre-`0`-hypercovers of `S` is a family of refinement morphisms commuting
with the structure morphisms of `E` and `F`. -/
@[ext]
structure Hom (E : PreZeroHypercover.{w} S) (F : PreZeroHypercover.{w'} S) where
  /-- The map between indexing types of the coverings of `S` -/
  s₀ (i : E.I₀) : F.I₀
  /-- The refinement morphisms between objects in the coverings of `S`. -/
  h₀ (i : E.I₀) : E.X i ⟶ F.X (s₀ i)
  w₀ (i : E.I₀) : h₀ i ≫ F.f (s₀ i) = E.f i := by aesop_cat

attribute [reassoc (attr := simp)] Hom.w₀

/-- The identity refinement of a pre-`0`-hypercover. -/
@[simps]
def Hom.id (E : PreZeroHypercover S) : Hom E E where
  s₀ := _root_.id
  h₀ _ := 𝟙 _

variable {G : PreZeroHypercover S}

/-- Composition of refinement morphisms of pre-`0`-hypercovers. -/
@[simps]
def Hom.comp (f : E.Hom F) (g : F.Hom G) : E.Hom G where
  s₀ := g.s₀ ∘ f.s₀
  h₀ i := f.h₀ i ≫ g.h₀ _

@[simps! id_s₀ id_h₀ comp_s₀ comp_h₀]
instance : Category (PreZeroHypercover S) where
  Hom := Hom
  id E := Hom.id E
  comp f g := f.comp g

lemma Hom.ext' {E : PreZeroHypercover.{w} S} {F : PreZeroHypercover.{w'} S}
    {f g : E.Hom F} (hs : f.s₀ = g.s₀) (hh : ∀ i, f.h₀ i = g.h₀ i ≫ eqToHom (by rw [hs])) :
    f = g := by
  cases f
  cases g
  simp only at hs
  subst hs
  simp only [eqToHom_refl, Category.comp_id] at hh
  simp only [PreZeroHypercover.Hom.mk.injEq, heq_eq_eq, true_and]
  ext
  apply hh

end Category

@[simps]
noncomputable
def pullback₁Id (E : PreZeroHypercover S) [∀ (i : E.I₀), HasPullback (𝟙 S) (E.f i)] :
    E.pullback₁ (𝟙 S) ≅ E where
  hom.s₀ := id
  hom.h₀ i := pullback.snd _ _
  hom.w₀ i := by simp [← pullback.condition]
  inv.s₀ := id
  inv.h₀ i := pullback.lift (E.f i) (𝟙 _)
  hom_inv_id := by
    refine PreZeroHypercover.Hom.ext' rfl fun i ↦ ?_
    apply pullback.hom_ext <;> simp [← pullback.condition]
  inv_hom_id := PreZeroHypercover.Hom.ext' rfl (by simp)

@[simps]
noncomputable
def pullback₁Comp {S T W : C} (E : PreZeroHypercover.{w} S) (f : W ⟶ T) (g : T ⟶ S)
    [∀ (i : E.I₀), HasPullback (f ≫ g) (E.f i)] [∀ (i : E.I₀), HasPullback g (E.f i)]
    [∀ i, HasPullback f (pullback.fst g (E.f i))]
    [∀ (i : (pullback₁ g E).I₀), HasPullback f ((pullback₁ g E).f i)] :
    E.pullback₁ (f ≫ g) ≅ (E.pullback₁ g).pullback₁ f where
  hom.s₀ := id
  hom.h₀ i := (pullbackRightPullbackFstIso _ _ _).inv
  inv.s₀ := id
  inv.h₀ i := (pullbackRightPullbackFstIso _ _ _).hom
  hom_inv_id := PreZeroHypercover.Hom.ext' rfl (by simp)
  inv_hom_id := PreZeroHypercover.Hom.ext' rfl (by simp)

end PreZeroHypercover

namespace Coverage

variable (J : Coverage C)

/-- The type of `0`-hypercovers of an object `S : C` in a category equipped with a
coverage `J`. This can be constructed from a covering of `S`. -/
structure ZeroHypercover (S : C) extends PreZeroHypercover.{w} S where
  mem₀ : toPreZeroHypercover.presieve₀ ∈ J S

namespace ZeroHypercover

variable {S T : C}

/-- The `0`-hypercover defined by a single covering morphism. -/
@[simps toPreZeroHypercover]
def singleton (f : S ⟶ T) (hf : Presieve.singleton f ∈ J T) :
    J.ZeroHypercover T where
  __ := PreZeroHypercover.singleton f
  mem₀ := by
    simpa [PreZeroHypercover.presieve₀, PreZeroHypercover.singleton, Presieve.ofArrows_pUnit]

/-- Pullback of a `0`-hypercover along a morphism. The components are `pullback f (E.f i)`. -/
@[simps toPreZeroHypercover]
noncomputable
def pullback₁ [J.IsStableUnderBaseChange] [Limits.HasPullbacks C] (f : S ⟶ T)
    (E : ZeroHypercover.{w} J T) :
    J.ZeroHypercover S where
  __ := E.toPreZeroHypercover.pullback₁ f
  mem₀ := J.mem_covering_of_isPullback E.f E.mem₀ f _
    (fun _ ↦ pullback.snd _ _) fun i ↦ IsPullback.of_hasPullback f (E.f i)

/-- Pullback of a `0`-hypercover along a morphism. The components are `pullback (E.f i) f`. -/
@[simps toPreZeroHypercover]
noncomputable
def pullback₂ [J.IsStableUnderBaseChange] [Limits.HasPullbacks C] (f : S ⟶ T)
    (E : ZeroHypercover.{w} J T) :
    J.ZeroHypercover S where
  __ := E.toPreZeroHypercover.pullback₂ f
  mem₀ := J.mem_covering_of_isPullback E.f E.mem₀ f _
    (fun _ ↦ pullback.fst _ _) fun i ↦ (IsPullback.of_hasPullback (E.f i) f).flip

/-- Refining each component of a `0`-hypercover yields a refined `0`-hypercover of the base. -/
def bind [J.IsStableUnderComposition] (E : ZeroHypercover.{w} J T)
    (F : ∀ i, ZeroHypercover.{w'} J (E.X i)) :
    ZeroHypercover.{max w w'} J T where
  __ := E.toPreZeroHypercover.bind (fun i ↦ (F i).toPreZeroHypercover)
  mem₀ :=
    mem_covering_comp (f := E.f) (g := fun i j ↦ (F i).f j) E.mem₀ (fun i ↦ (F i).mem₀)

/-- A morphism of `0`-hypercovers is a morphism of the underlying pre-`0`-hypercovers. -/
abbrev Hom (E : ZeroHypercover.{w} J S) (F : ZeroHypercover.{w'} J S) :=
  E.toPreZeroHypercover.Hom F.toPreZeroHypercover

@[simps! id_s₀ id_h₀ comp_s₀ comp_h₀]
instance : Category (ZeroHypercover.{w} J S) where
  Hom := Hom J
  id _ := PreZeroHypercover.Hom.id _
  comp := PreZeroHypercover.Hom.comp

end ZeroHypercover

end Coverage

end CategoryTheory
