/-
Copyright (c) 2019 mathlib community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mario Carneiro, Wojciech Nawrocki, Brendan Murphy
-/
import Mathlib.Control.Fold
import Mathlib.Data.Tree.Defs
import Mathlib.Data.Tree.Instances

namespace Tree

universe u v

variable {α : Type u} {β : Type v}

-- def numLeaves' : Tree α → ℕ := sorry

-- def graft : Tree α → ℕ → Tree α → Option (Tree α)
--   | nil, _, _ => none
--   | node a l r, _, _ => none

end Tree
