/-
Copyright (c) 2024 Jireh Loreaux. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jireh Loreaux
-/
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Isometric
import Mathlib.Analysis.CStarAlgebra.SpecialFunctions.PosPart
import Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.Rpow
import Mathlib.Topology.ApproximateUnit

/-! # Nonnegative contractions in a C⋆-algebra form an approximate unit

This file shows that the collection of positive contractions (of norm strictly less than one)
in a possibly non-unital C⋆-algebra form a directed set. The key step uses the continuous functional
calculus applied with the functions `fun x : ℝ≥0, 1 - (1 + x)⁻¹` and `fun x : ℝ≥0, x * (1 - x)⁻¹`,
which are inverses on the interval `{x : ℝ≥0 | x < 1}`.

In addition, this file defines `IsIncreasingApproximateUnit` to be a filter `l` that is an
approximate unit contained in the closed unit ball of nonnegative elements. Every C⋆-algebra has
a filter generated by the sections `{x | a ≤ x} ∩ closedBall 0 1` for `0 ≤ a` and `‖a‖ < 1`, and
moreover, this filter is an increasing approximate unit.

## Main declarations

+ `CFC.monotoneOn_one_sub_one_add_inv`: the function `f := fun x : ℝ≥0, 1 - (1 + x)⁻¹` is
  *operator monotone* on `Set.Ici (0 : A)` (i.e., `cfcₙ f` is monotone on `{x : A | 0 ≤ x}`).
+ `Set.InvOn.one_sub_one_add_inv`: the functions `f := fun x : ℝ≥0, 1 - (1 + x)⁻¹` and
  `g := fun x : ℝ≥0, x * (1 - x)⁻¹` are inverses on `{x : ℝ≥0 | x < 1}`.
+ `CStarAlgebra.directedOn_nonneg_ball`: the set `{x : A | 0 ≤ x} ∩ Metric.ball 0 1` is directed.
+ `Filter.IsIncreasingApproximateUnit`: a filter `l` is an *increasing approximate unit* if it is an
  approximate unit contained in the closed unit ball of nonnegative elements.
+ `CStarAlgebra.approximateUnit`: the filter generated by the sections
  `{x | a ≤ x} ∩ closedBall 0 1` for `0 ≤ a` with `‖a‖ < 1`.
+ `CStarAlgebra.increasingApproximateUnit`: the filter `CStarAlgebra.approximateUnit` is an
  increasing approximate unit.

-/

variable {A : Type*} [NonUnitalCStarAlgebra A]

local notation "σₙ" => quasispectrum
local notation "σ" => spectrum

open Unitization NNReal CStarAlgebra

variable [PartialOrder A] [StarOrderedRing A]

lemma CFC.monotoneOn_one_sub_one_add_inv :
    MonotoneOn (cfcₙ (fun x : ℝ≥0 ↦ 1 - (1 + x)⁻¹)) (Set.Ici (0 : A)) := by
  intro a ha b hb hab
  simp only [Set.mem_Ici] at ha hb
  rw [← inr_le_iff .., nnreal_cfcₙ_eq_cfc_inr a _, nnreal_cfcₙ_eq_cfc_inr b _]
  rw [← inr_le_iff a b (.of_nonneg ha) (.of_nonneg hb)] at hab
  rw [← inr_nonneg_iff] at ha hb
  have h_cfc_one_sub (c : A⁺¹) (hc : 0 ≤ c := by cfc_tac) :
      cfc (fun x : ℝ≥0 ↦ 1 - (1 + x)⁻¹) c = 1 - cfc (·⁻¹ : ℝ≥0 → ℝ≥0) (1 + c) := by
    rw [cfc_tsub _ _ _ (fun x _ ↦ by simp) (hg := by fun_prop (disch := intro _ _; positivity)),
      cfc_const_one ℝ≥0 c, cfc_comp' (·⁻¹) (1 + ·) c ?_, cfc_add .., cfc_const_one ℝ≥0 c,
      cfc_id' ℝ≥0 c]
    exact continuousOn_id.inv₀ (Set.forall_mem_image.mpr fun x _ ↦ by dsimp only [id]; positivity)
  rw [h_cfc_one_sub (a : A⁺¹), h_cfc_one_sub (b : A⁺¹)]
  gcongr
  rw [← CFC.rpow_neg_one_eq_cfc_inv, ← CFC.rpow_neg_one_eq_cfc_inv]
  exact rpow_neg_one_le_rpow_neg_one (add_nonneg zero_le_one ha) (by gcongr) <|
    isUnit_of_le isUnit_one zero_le_one <| le_add_of_nonneg_right ha

lemma Set.InvOn.one_sub_one_add_inv : Set.InvOn (fun x ↦ 1 - (1 + x)⁻¹) (fun x ↦ x * (1 - x)⁻¹)
    {x : ℝ≥0 | x < 1} {x : ℝ≥0 | x < 1} := by
  have : (fun x : ℝ≥0 ↦ x * (1 + x)⁻¹) = fun x ↦ 1 - (1 + x)⁻¹ := by
    ext x : 1
    field_simp
    simp [tsub_mul, inv_mul_cancel₀]
  rw [← this]
  constructor <;> intro x (hx : x < 1)
  · have : 0 < 1 - x := tsub_pos_of_lt hx
    field_simp [tsub_add_cancel_of_le hx.le, tsub_tsub_cancel_of_le hx.le]
  · field_simp [mul_tsub]

lemma norm_cfcₙ_one_sub_one_add_inv_lt_one (a : A) :
    ‖cfcₙ (fun x : ℝ≥0 ↦ 1 - (1 + x)⁻¹) a‖ < 1 :=
  nnnorm_cfcₙ_nnreal_lt fun x _ ↦ tsub_lt_self zero_lt_one (by positivity)

-- the calls to `fun_prop` with a discharger set off the linter
set_option linter.style.multiGoal false in
lemma CStarAlgebra.directedOn_nonneg_ball :
    DirectedOn (· ≤ ·) ({x : A | 0 ≤ x} ∩ Metric.ball 0 1) := by
  let f : ℝ≥0 → ℝ≥0 := fun x => 1 - (1 + x)⁻¹
  let g : ℝ≥0 → ℝ≥0 := fun x => x * (1 - x)⁻¹
  suffices ∀ a b : A, 0 ≤ a → 0 ≤ b → ‖a‖ < 1 → ‖b‖ < 1 →
      a ≤ cfcₙ f (cfcₙ g a + cfcₙ g b) by
    rintro a ⟨(ha₁ : 0 ≤ a), ha₂⟩ b ⟨(hb₁ : 0 ≤ b), hb₂⟩
    simp only [Metric.mem_ball, dist_zero_right] at ha₂ hb₂
    refine ⟨cfcₙ f (cfcₙ g a + cfcₙ g b), ⟨by simp, ?_⟩, ?_, ?_⟩
    · simpa only [Metric.mem_ball, dist_zero_right] using norm_cfcₙ_one_sub_one_add_inv_lt_one _
    · exact this a b ha₁ hb₁ ha₂ hb₂
    · exact add_comm (cfcₙ g a) (cfcₙ g b) ▸ this b a hb₁ ha₁ hb₂ ha₂
  rintro a b ha₁ - ha₂ -
  calc
    a = cfcₙ (f ∘ g) a := by
      conv_lhs => rw [← cfcₙ_id ℝ≥0 a]
      refine cfcₙ_congr (Set.InvOn.one_sub_one_add_inv.1.eqOn.symm.mono fun x hx ↦ ?_)
      exact lt_of_le_of_lt (le_nnnorm_of_mem_quasispectrum hx) ha₂
    _ = cfcₙ f (cfcₙ g a) := by
      rw [cfcₙ_comp f g a ?_ (by simp [f, tsub_self]) ?_ (by simp [g]) ha₁]
      · fun_prop (disch := intro _ _; positivity)
      · have (x) (hx : x ∈ σₙ ℝ≥0 a) :  1 - x ≠ 0 := by
          refine tsub_pos_of_lt ?_ |>.ne'
          exact lt_of_le_of_lt (le_nnnorm_of_mem_quasispectrum hx) ha₂
        fun_prop (disch := assumption)
    _ ≤ cfcₙ f (cfcₙ g a + cfcₙ g b) := by
      have hab' : cfcₙ g a ≤ cfcₙ g a + cfcₙ g b := le_add_of_nonneg_right cfcₙ_nonneg_of_predicate
      exact CFC.monotoneOn_one_sub_one_add_inv cfcₙ_nonneg_of_predicate
        (cfcₙ_nonneg_of_predicate.trans hab') hab'

section ApproximateUnit

open Metric Filter Topology

/-- An *increasing approximate unit* in a C⋆-algebra is an approximate unit contained in the
closed unit ball of nonnegative elements. -/
structure Filter.IsIncreasingApproximateUnit (l : Filter A) extends l.IsApproximateUnit : Prop where
  eventually_nonneg : ∀ᶠ x in l, 0 ≤ x
  eventually_norm : ∀ᶠ x in l, ‖x‖ ≤ 1

namespace Filter.IsIncreasingApproximateUnit

omit [StarOrderedRing A] in
lemma eventually_nnnorm {l : Filter A} (hl : l.IsIncreasingApproximateUnit) :
    ∀ᶠ x in l, ‖x‖₊ ≤ 1 :=
  hl.eventually_norm

lemma eventually_isSelfAdjoint {l : Filter A} (hl : l.IsIncreasingApproximateUnit) :
    ∀ᶠ x in l, IsSelfAdjoint x :=
  hl.eventually_nonneg.mp <| .of_forall fun _ ↦ IsSelfAdjoint.of_nonneg

lemma eventually_star_eq {l : Filter A} (hl : l.IsIncreasingApproximateUnit) :
    ∀ᶠ x in l, star x = x :=
  hl.eventually_isSelfAdjoint.mp <| .of_forall fun _ ↦ IsSelfAdjoint.star_eq

end Filter.IsIncreasingApproximateUnit

namespace CStarAlgebra

open Submodule in
/-- To show that `l` is a one-sided approximate unit for `A`, it suffices to verify it only for
`m : A` with `0 ≤ m` and `‖m‖ < 1`. -/
lemma tendsto_mul_right_of_forall_nonneg_tendsto {l : Filter A}
    (h : ∀ m, 0 ≤ m → ‖m‖ < 1 → Tendsto (· * m) l (𝓝 m)) (m : A) :
    Tendsto (· * m) l (𝓝 m) := by
  obtain ⟨n, c, x, rfl⟩ := mem_span_set'.mp <| by
    show m ∈ span ℂ ({x | 0 ≤ x} ∩ ball 0 1)
    simp [span_nonneg_inter_unitBall]
  simp_rw [Finset.mul_sum]
  refine tendsto_finset_sum _ fun i _ ↦ ?_
  simp_rw [mul_smul_comm]
  exact tendsto_const_nhds.smul <| h (x i) (x i).2.1 <| by simpa using (x i).2.2

omit [PartialOrder A] in
/-- Multiplication on the left by `m` tends to `𝓝 m` if and only if multiplication on the right
does, provided the elements are eventually selfadjoint along the filter `l`. -/
lemma tendsto_mul_left_iff_tendsto_mul_right {l : Filter A} (hl : ∀ᶠ x in l, IsSelfAdjoint x) :
    (∀ m, Tendsto (m * ·) l (𝓝 m)) ↔ (∀ m, Tendsto (· * m) l (𝓝 m)) := by
  refine ⟨fun h m ↦ ?_, fun h m ↦ ?_⟩
  all_goals
    apply (star_star m ▸ (continuous_star.tendsto _ |>.comp <| h (star m))).congr'
    filter_upwards [hl] with x hx
    simp [hx.star_eq]

variable (A)

/-- The sections of positive strict contractions form a filter basis. -/
lemma isBasis_nonneg_sections :
    IsBasis (fun x : A ↦ 0 ≤ x ∧ ‖x‖ < 1) ({x | · ≤ x}) where
  nonempty := ⟨0, by simp⟩
  inter {x y} hx hy := by
    peel directedOn_nonneg_ball x (by simpa) y (by simpa) with z hz
    exact ⟨by simpa using hz.1, fun a ha ↦ ⟨hz.2.1.trans ha, hz.2.2.trans ha⟩⟩

/-- The canonical approximate unit in a C⋆-algebra generated by the basis of sets
`{x | a ≤ x} ∩ closedBall 0 1` for `0 ≤ a`. See also `CStarAlgebra.hasBasis_approximateUnit`. -/
def approximateUnit : Filter A :=
  (isBasis_nonneg_sections A).filter ⊓ 𝓟 (closedBall 0 1)

/-- The canonical approximate unit in a C⋆-algebra has a basis of sets
`{x | a ≤ x} ∩ closedBall 0 1` for `0 ≤ a`. -/
lemma hasBasis_approximateUnit :
    (approximateUnit A).HasBasis (fun x : A ↦ 0 ≤ x ∧ ‖x‖ < 1) ({x | · ≤ x} ∩ closedBall 0 1) :=
  isBasis_nonneg_sections A |>.hasBasis.inf_principal (closedBall 0 1)

instance : (approximateUnit A).NeBot :=
  hasBasis_approximateUnit A |>.neBot_iff.mpr fun hx ↦ ⟨_, ⟨le_rfl, by simpa using hx.2.le⟩⟩

lemma eventually_ge_approximateUnit {e : A} (he₀ : 0 ≤ e) (he₁ : ‖e‖ < 1) :
    ∀ᶠ x in approximateUnit A, e ≤ x := .filter_mono inf_le_left <|
  (isBasis_nonneg_sections A).hasBasis.eventually_iff.mpr ⟨e, ⟨he₀, he₁⟩, fun _ ↦ id⟩

lemma eventually_nonneg_approximateUnit : ∀ᶠ x in approximateUnit A, 0 ≤ x :=
  eventually_ge_approximateUnit A le_rfl (by simp)

lemma eventually_norm_le_approximateUnit : ∀ᶠ x in approximateUnit A, ‖x‖ ≤ 1 :=
  .filter_mono inf_le_right <| by simp

/-- This is a common reasoning sequence in C⋆-algebra theory. If `0 ≤ x ≤ y ≤ 1`, then the norm
of `z - y * z` is controled by the norm of `star z * (1 - x) * z`, which is advantageous because the
latter is nonnegative. This is a key step in establishing the existence of an increasing approximate
unit in general C⋆-algebras. -/
lemma sq_nnnorm_sub_mul_self_le {A : Type*} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
    {x : A} (z : A) (hx : x ∈ Set.Icc 0 1) :
    ‖z - x * z‖₊ ^ 2 ≤ ‖star z * (1 - x) * z‖₊ := by
  have hx' : 1 - x ∈ Set.Icc 0 1 := Set.sub_mem_Icc_zero_iff_right.mpr hx
  rw [← one_sub_mul, sq, ← CStarRing.nnnorm_star_mul_self]
  refine nnnorm_le_nnnorm_of_nonneg_of_le (star_mul_self_nonneg _) ?_
  rw [star_mul, star_sub, star_one, ← mul_assoc, mul_assoc _ _ (1 - x), hx.1.star_eq, ← sq]
  exact conjugate_le_conjugate (by simpa using pow_antitone hx'.1 hx'.2 one_le_two) z

/-- This is a common reasoning sequence in C⋆-algebra theory. If `0 ≤ x ≤ y ≤ 1`, then the norm
of `z - y * z` is controled by the norm of `star z * (1 - x) * z`, which is advantageous because the
latter is nonnegative. This is a key step in establishing the existence of an increasing approximate
unit in general C⋆-algebras. -/
lemma sq_norm_sub_mul_self_le {A : Type*} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
    {x : A} (z : A) (hx : x ∈ Set.Icc 0 1) :
    ‖z - x * z‖ ^ 2 ≤ ‖star z * (1 - x) * z‖ :=
  sq_nnnorm_sub_mul_self_le _ hx

variable {A} in
/-- A variant of `sq_norm_sub_mul_self_le` for non-unital algebras that passes to the
unitization. -/
lemma sq_norm_sub_mul_self_le_inr {x : A} (z : A) (hx₀ : 0 ≤ x) (hx₁ : ‖x‖ ≤ 1) :
    ‖z - x * z‖ ^ 2 ≤ ‖star (z : A⁺¹) * (1 - x) * z‖ := by
  rw [← norm_inr (𝕜 := ℂ), inr_sub, inr_mul]
  refine sq_norm_sub_mul_self_le _ ?_
  rw [Set.mem_Icc, inr_nonneg_iff, ← norm_le_one_iff_of_nonneg _, norm_inr]
  exact ⟨hx₀, hx₁⟩

variable {A} in
/-- This shows `CStarAlgebra.approximateUnit` is a one-sided approximate unit, but this is marked
`private` because it is only used to prove `CStarAlgebra.increasingApproximateUnit`. -/
private lemma tendsto_mul_right_approximateUnit (m : A) :
    Tendsto (· * m) (approximateUnit A) (𝓝 m) := by
  refine tendsto_mul_right_of_forall_nonneg_tendsto (fun m hm₀ hm₁ ↦ ?_) m
  rw [tendsto_iff_norm_sub_tendsto_zero, tendsto_zero_iff_sq (.of_forall fun _ ↦ norm_nonneg _)]
  have : ∀ᶠ x in approximateUnit A, ‖x * m - m‖ ^ 2 ≤ ‖star (m : A⁺¹) * (1 - x) * m‖ := by
    filter_upwards [eventually_nonneg_approximateUnit A, eventually_norm_le_approximateUnit A]
    simp_rw [norm_sub_rev]
    exact fun _ ↦ sq_norm_sub_mul_self_le_inr _
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds ?_
    (.of_forall fun _ ↦ sq_nonneg _) this

  suffices ∀ ε, 0 < ε → ∃ e : A, 0 ≤ e ∧ ‖e‖ < 1 ∧ ‖star (m : A⁺¹) * (1 - e) * m‖ ≤ ε by
    simp_rw [← tendsto_zero_iff_norm_tendsto_zero, Metric.nhds_basis_closedBall.tendsto_right_iff,
      mem_closedBall_zero_iff]
    peel this with ε hε this
    rcases this with ⟨e, he₀, he₁, he⟩
    filter_upwards [eventually_ge_approximateUnit A he₀ he₁, eventually_norm_le_approximateUnit A]
      with a hea ha₁
    have ha₀ : 0 ≤ a := he₀.trans hea
    have ha₀' : 0 ≤ (a : A⁺¹) := inr_nonneg_iff.mpr ha₀
    refine le_trans (norm_le_norm_of_nonneg_of_le ?_ ?_) he
    · refine conjugate_nonneg (sub_nonneg_of_le ?_) (m : A⁺¹)
      rwa [← norm_le_one_iff_of_nonneg (a : A⁺¹) ha₀', norm_inr]
    · refine conjugate_le_conjugate (sub_le_sub_iff_left _ |>.mpr ?_) (m : A⁺¹)
      exact inr_le_iff _ _ he₀.isSelfAdjoint ha₀.isSelfAdjoint |>.mpr hea

  intro ε hε
  lift ε to ℝ≥0 using hε.le
  rw [coe_pos] at hε
  set e : A := cfcₙ (fun y : ℝ≥0 ↦ 1 - (1 + y)⁻¹) (ε⁻¹ • m) with e_def
  have he₀ : 0 ≤ e := cfcₙ_nonneg_of_predicate
  have he₁ : ‖e‖ < 1 := norm_cfcₙ_one_sub_one_add_inv_lt_one (ε⁻¹ • m)
  refine ⟨e, he₀, he₁, ?_⟩
  rw [← norm_inr (𝕜 := ℂ)] at hm₁ he₁
  rw [← inr_nonneg_iff] at he₀ hm₀
  have cont : Continuous (fun y : ℝ≥0 ↦ 1 - (1 + y)⁻¹) := by
    rw [continuous_iff_continuousOn_univ]
    fun_prop (disch := intro _ _; positivity)
  have cont' : ContinuousOn (fun y ↦ (1 + ε⁻¹ • y)⁻¹) (spectrum ℝ≥0 (m : A⁺¹)) :=
    ContinuousOn.inv₀ (by fun_prop) fun _ _ ↦ by positivity
  have : star (m : A⁺¹) * (1 - e) * m =
      cfc (fun y : ℝ≥0 ↦ y * (1 + ε⁻¹ • y)⁻¹ * y) (m : A⁺¹) := by
    rw [hm₀.star_eq, e_def, nnreal_cfcₙ_eq_cfc_inr _ _ (by simp [tsub_self]), inr_smul,
      cfc_mul _ _ (m : A⁺¹) (continuousOn_id' _ |>.mul cont') (continuousOn_id' _),
      cfc_mul _ _ (m : A⁺¹) (continuousOn_id' _) cont', cfc_id' ..]
    rw [← cfc_one (R := ℝ≥0) (m : A⁺¹), ← cfc_comp_smul _ _ _ cont.continuousOn hm₀,
      ← cfc_tsub _ _ (m : A⁺¹) (by simp) hm₀ (by fun_prop) (continuousOn_const.sub cont')]
    simp [tsub_tsub_cancel_of_le]
  rw [this, ← coe_nnnorm, coe_le_coe]
  refine nnnorm_cfc_nnreal_le fun y hy ↦ ?_
  field_simp
  calc
    y * ε * y / (ε + y) ≤ ε * 1 := by
      rw [mul_div_assoc]
      refine mul_le_mul (mul_le_of_le_one_left (zero_le _) ?_)
        (div_le_one (by positivity) |>.mpr le_add_self)
        (by positivity) (by positivity)
      exact_mod_cast spectrum.coe_le_norm_of_mem hy |>.trans hm₁.le
    _ = ε := mul_one _

/-- The filter `CStarAlgebra.approximateUnit` generated by the sections
`{x | a ≤ x} ∩ closedBall 0 1` for `0 ≤ a` forms an increasing approximate unit. -/
lemma increasingApproximateUnit :
    IsIncreasingApproximateUnit (approximateUnit A) where
  tendsto_mul_left := by
    rw [tendsto_mul_left_iff_tendsto_mul_right]
    · exact tendsto_mul_right_approximateUnit
    · filter_upwards [eventually_nonneg_approximateUnit A] using fun _ h ↦ h.isSelfAdjoint
  tendsto_mul_right := tendsto_mul_right_approximateUnit
  eventually_nonneg := eventually_nonneg_approximateUnit A
  eventually_norm := eventually_norm_le_approximateUnit A
  neBot := inferInstance

end CStarAlgebra

end ApproximateUnit
