/-
Copyright (c) 2026 Robert Hawkins. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Hawkins
-/
module

public import Mathlib.RingTheory.Bialgebra.Primitive
public import Mathlib.RingTheory.HopfAlgebra.Generators

/-!
# Primitive elements in a Hopf algebra

Facts about primitive elements in a Hopf algebra, plus `HopfAlgebra.ofPrimitives`,
a constructor for Hopf algebras generated as algebras by primitive elements.

## Main declarations

* `IsPrimitiveElem.antipode_eq_neg` : the antipode sends primitive elements to their negation.
* `IsPrimitiveElem.antipode` : the antipode preserves primitivity.
* `HopfAlgebra.ofPrimitives` : construct a Hopf algebra from a primitive-element generating set.
-/

public section

open HopfAlgebra LinearMap MulOpposite

variable {R A : Type*} [CommSemiring R]

/-- The antipode of a Hopf algebra sends primitive elements to their negation. -/
@[simp] theorem IsPrimitiveElem.antipode_eq_neg [Ring A] [HopfAlgebra R A] {a : A}
    (ha : IsPrimitiveElem R a) : antipode R a = -a := by
  have key := mul_antipode_rTensor_comul_apply (R := R) a
  simp only [ha.comul_eq_tmul_add_tmul, ha.counit_eq_zero, map_add, rTensor_tmul,
    antipode_one, mul'_apply, mul_one, one_mul, map_zero] at key
  exact eq_neg_of_add_eq_zero_left key

/-- The antipode preserves primitivity. -/
protected lemma IsPrimitiveElem.antipode {R A : Type*} [CommRing R] [Ring A]
    [HopfAlgebra R A] {a : A} (ha : IsPrimitiveElem R a) : IsPrimitiveElem R (antipode R a) :=
  ha.antipode_eq_neg ▸ ha.neg

namespace HopfAlgebra

/-- Upgrade a bialgebra generated by primitive elements to a Hopf algebra by specifying the
antipode-on-generators formula `S p = op (-p)`. -/
noncomputable abbrev ofPrimitives [Ring A] [Bialgebra R A]
    (S : A →ₐ[R] Aᵐᵒᵖ) {s : Set A}
    (hs_gen : Algebra.adjoin R s = ⊤)
    (hs_prim : ∀ p ∈ s, IsPrimitiveElem R p)
    (hS : ∀ p ∈ s, S p = op (-p)) :
    HopfAlgebra R A := by
  refine ofGenerators ((opLinearEquiv R).symm.toLinearMap ∘ₗ S.toLinearMap)
    (by simp [map_one]) (fun _ _ => by simp [map_mul]) hs_gen ?_ ?_ <;>
    exact fun p hp => by
      simp [convMul_apply, (hs_prim p hp).comul_eq_tmul_add_tmul,
        (hs_prim p hp).counit_eq_zero, hS p hp]

end HopfAlgebra
