/-
Copyright (c) 2026 Xavier Roblot. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Xavier Roblot
-/
module

public import Mathlib.Algebra.Polynomial.SpecificDegree
public import Mathlib.NumberTheory.NumberField.Discriminant.Different
public import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind
public import Mathlib.NumberTheory.NumberField.QuadraticField.Basic
public import Mathlib.NumberTheory.RamificationInertia.Galois
public import Mathlib.RingTheory.RamificationInertia.Basic
public import Mathlib.Tactic.Polynomial.Basic

/-!
# Ideals in quadratic fields

In this file, we prove results about ideals in quadratic extensions of `ℚ`.

## Main results

* `NumberField.QuadraticField.exponent_integralGen`: the ring of integers of a quadratic field
  is generated by `integralGen K`, so the hypothesis gating the Kummer-Dedekind API holds for
  every prime.

* `NumberField.QuadraticField.inertiaDeg_of_not_isSquare`, `ramificationIdx_of_not_isSquare` and
  `ncard_primesOver_of_not_isSquare`: if the discriminant is not a square mod `p`, then `p` is
  inert.

* `NumberField.QuadraticField.ramificationIdx_of_dvd_discr`, `inertiaDeg_of_dvd_discr` and
  `ncard_primesOver_of_dvd_discr`: if `p` divides the discriminant, then `p` is ramified.

* `NumberField.QuadraticField.ncard_primesOver_of_isSquare`, `ramificationIdx_of_isSquare` and
  `inertiaDeg_of_isSquare`: if the discriminant is a nonzero square mod `p`, then `p` splits.

* `NumberField.QuadraticField.inertiaDeg_two_of_discr_emod_eight_five` and its companions: the
  behaviour of `2`, read off `discr K` modulo `8`.
-/

public section

open Ideal NumberField NumberField.Ideal Polynomial UniqueFactorizationMonoid

open scoped QuadraticAlgebra

namespace NumberField.QuadraticField

variable (K : Type*) [Field K] [CharZero K] [Algebra.IsQuadraticExtension ℚ K]

/-- The hypothesis gating the Kummer-Dedekind API holds for every prime, `2` included. -/
theorem exponent_integralGen : RingOfIntegers.exponent (integralGen K) = 1 :=
  RingOfIntegers.exponent_eq_one_iff.mpr (adjoin_integralGen_eq_top K)

theorem not_dvd_exponent_integralGen (p : ℕ) [hp : Fact p.Prime] :
    ¬ p ∣ RingOfIntegers.exponent (integralGen K) := by
  rw [exponent_integralGen, Nat.dvd_one]
  exact hp.out.ne_one

variable {K} in
/-- The fundamental identity `g * e * f = 2` for a quadratic field. -/
theorem ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg (P : Ideal (𝓞 K)) [P.IsPrime] :
    ((under ℤ P).primesOver (𝓞 K)).ncard * (P.ramificationIdx ℤ * P.inertiaDeg ℤ) = 2 := by
  rw [← ramificationIdxIn_eq_ramificationIdx (under ℤ P) P Gal(K/ℚ),
    ← inertiaDegIn_eq_inertiaDeg (under ℤ P) P Gal(K/ℚ),
    ncard_primesOver_mul_ramificationIdxIn_mul_inertiaDegIn _ _ Gal(K/ℚ),
    IsGalois.card_aut_eq_finrank, Algebra.IsQuadraticExtension.finrank_eq_two']

variable {K} (p : ℕ) [Fact p.Prime]

local notation3 "𝒑" => (span {(p : ℤ)})

section inert

variable (hd : ¬ IsSquare ((discr K : ZMod p)))

include hd

/-- If the discriminant is not a square mod `p`, then `p` is inert: `f = 2` at every prime
above `p`. -/
theorem inertiaDeg_of_not_isSquare (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver 𝒑] :
    P.inertiaDeg ℤ = 2 := by
  have h₀ : ¬ p ∣ RingOfIntegers.exponent (integralGen K) := not_dvd_exponent_integralGen K p
  let 𝓟 : 𝒑.primesOver (𝓞 K) := ⟨P, ⟨inferInstance, inferInstance⟩⟩
  have h₁ : RingOfIntegers.monicFactorsMod (integralGen K) p =
      {(minpoly ℤ (integralGen K)).map (Int.castRingHom (ZMod p))} := by
    simp only [RingOfIntegers.monicFactorsMod, minpoly_integralGen, eq_intCast, Polynomial.map_sub,
      Polynomial.map_pow, map_X, Polynomial.map_mul, Polynomial.map_intCast]
    rw [show X ^ 2 = C (1 : ZMod p) * X ^ 2 by rw [map_one, one_mul], ← C_eq_intCast,
      ← C_eq_intCast, sub_eq_add_neg, sub_eq_add_neg, ← neg_mul, ← map_neg, ← map_neg,
      normalizedFactors_quadratic_of_not_isSquare_discrim one_ne_zero
      (by rwa [discrim_minpoly_integralGen])]
    simp
  have h₂ := (primesOverSpanEquivMonicFactorsMod h₀ 𝓟).2
  simp only [h₁, Finset.mem_singleton] at h₂
  rw [inertiaDeg_primesOverSpanEquivMonicFactorsMod_apply h₀ 𝓟, h₂,
    Polynomial.Monic.natDegree_map (monic_minpoly_integralGen K)]
  exact natDegree_minpoly_integralGen K

/-- If the discriminant is not a square mod `p`, then `p` is inert: `e = 1` at every prime
above `p`. -/
theorem ramificationIdx_of_not_isSquare (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver 𝒑] :
    P.ramificationIdx ℤ = 1 := by
  have h := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [inertiaDeg_of_not_isSquare p hd, ← mul_assoc, mul_eq_right₀ two_ne_zero] at h
  exact Nat.eq_one_of_mul_eq_one_left h

/-- If the discriminant is not a square mod `p`, then `p` is inert: `g = 1`. -/
theorem ncard_primesOver_of_not_isSquare : (𝒑.primesOver (𝓞 K)).ncard = 1 := by
  obtain ⟨P, _, _⟩ := exists_isPrime_liesOver_of_faithfullyFlat 𝒑 (B := 𝓞 K)
  have h := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [inertiaDeg_of_not_isSquare p hd, ← mul_assoc, mul_eq_right₀ two_ne_zero,
    ← over_def P 𝒑] at h
  exact Nat.eq_one_of_mul_eq_one_right h

end inert

section ramified

variable (hd : (p : ℤ) ∣ discr K)

include hd

/-- If `p` divides the discriminant, it is ramified: `e = 2` at every prime above `p`. -/
theorem ramificationIdx_of_dvd_discr (P : Ideal (𝓞 K)) [hP₁ : P.IsPrime] [hP₂ : P.LiesOver 𝒑] :
    P.ramificationIdx ℤ = 2 := by
  refine Nat.le_antisymm ?_ ?_
  · rw [← ‹Algebra.IsQuadraticExtension ℚ K›.finrank_eq_two, ← RingOfIntegers.rank K]
    exact ramificationIdx_le_finrank' 𝒑 (𝓞 K) ⟨P, ⟨hP₁, hP₂⟩⟩
  · obtain ⟨Q, _, _, _⟩ := (dvd_discr_iff_exists_two_le_ramificationIdx K (𝓞 K)
      (Nat.prime_iff_prime_int.mp Fact.out)).mp hd
    rwa [ramificationIdx_eq_of_isGaloisGroup 𝒑 P Q Gal(K/ℚ)]

/-- If `p` divides the discriminant, it is ramified: `f = 1` at every prime above `p`. -/
theorem inertiaDeg_of_dvd_discr (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver 𝒑] :
    P.inertiaDeg ℤ = 1 := by
  have h := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [ramificationIdx_of_dvd_discr p hd, mul_comm 2, ← mul_assoc, mul_eq_right₀ two_ne_zero] at h
  exact Nat.eq_one_of_mul_eq_one_left h

/-- If `p` divides the discriminant, it is ramified: `g = 1`. -/
theorem ncard_primesOver_of_dvd_discr : (𝒑.primesOver (𝓞 K)).ncard = 1 := by
  obtain ⟨P, _, _⟩ := exists_isPrime_liesOver_of_faithfullyFlat 𝒑 (B := 𝓞 K)
  have h := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [ramificationIdx_of_dvd_discr p hd, mul_comm 2, ← mul_assoc, mul_eq_right₀ two_ne_zero,
    ← over_def P 𝒑] at h
  exact Nat.eq_one_of_mul_eq_one_right h

end ramified

section split

variable (hp2 : p ≠ 2) (hnd : ¬ (p : ℤ) ∣ discr K)
  (hd : IsSquare ((discr K : ZMod p)))

include hp2 hnd hd

/-- If the discriminant is a nonzero square mod `p`, then `p` splits: `g = 2`. -/
theorem ncard_primesOver_of_isSquare : (𝒑.primesOver (𝓞 K)).ncard = 2 := by
  have :  NeZero (2 : ZMod p) := ⟨Ring.two_ne_zero (by rwa [ZMod.ringChar_zmod_n])⟩
  obtain ⟨s, hs⟩ := hd
  have h₀ :  discrim (1 : ZMod p) (-(discr K % 4 : ℤ)) (-↑(discr K / 4 : ℤ)) = s ^ 2 := by
    rwa [discrim_minpoly_integralGen, pow_two]
  have h₁ : ¬ p ∣ RingOfIntegers.exponent (integralGen K) := not_dvd_exponent_integralGen K p
  rw [← Nat.card_coe_set_eq, Nat.card_congr (primesOverSpanEquivMonicFactorsMod h₁),
    RingOfIntegers.monicFactorsMod, minpoly_integralGen]
  simp only [eq_intCast, Polynomial.map_sub, Polynomial.map_pow, map_X, Polynomial.map_mul,
    Polynomial.map_intCast, Nat.card_eq_fintype_card, Fintype.card_coe]
  rw [show X ^ 2 = C (1 : ZMod p) * X ^ 2 by rw [map_one, one_mul], ← C_eq_intCast,
    ← C_eq_intCast, sub_eq_add_neg, sub_eq_add_neg, ← neg_mul, ← map_neg, ← map_neg,
    normalizedFactors_quadratic_of_discrim_eq_sq one_ne_zero h₀, Multiset.insert_eq_cons,
    Multiset.toFinset_cons, Multiset.toFinset_singleton, Finset.card_pair]
  rw [ne_eq, sub_right_inj, C_inj, mul_one, div_left_inj' two_ne_zero, sub_eq_add_neg,
    add_right_inj]
  refine fun h ↦ hnd ?_
  rw [eq_comm, Ring.eq_self_iff_eq_zero_of_char_ne_two (by rwa [ZMod.ringChar_zmod_n])] at h
  rwa [h, zero_mul, ZMod.intCast_zmod_eq_zero_iff_dvd] at hs

/-- If the discriminant is a nonzero square mod `p`, then `p` splits: `e = 1` at every prime
above `p`. -/
theorem ramificationIdx_of_isSquare (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver 𝒑] :
    P.ramificationIdx ℤ = 1 := by
  have h := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [← over_def P 𝒑, ncard_primesOver_of_isSquare p hp2 hnd hd, mul_eq_left₀ two_ne_zero] at h
  exact Nat.eq_one_of_mul_eq_one_right h

/-- If the discriminant is a nonzero square mod `p`, then `p` splits: `f = 1` at every prime
above `p`. -/
theorem inertiaDeg_of_isSquare (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver 𝒑] :
    P.inertiaDeg ℤ = 1 := by
  have h := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [← over_def P 𝒑, ncard_primesOver_of_isSquare p hp2 hnd hd, mul_eq_left₀ two_ne_zero] at h
  exact Nat.eq_one_of_mul_eq_one_left h

end split

section two_inert

variable (h : discr K % 8 = 5)

include h

/-- `2` is inert exactly when `discr K % 8 = 5`: `f = 2` at every prime above `2`. -/
theorem inertiaDeg_two_of_discr_emod_eight_five
    (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver (span {(2 : ℤ)})] :
    P.inertiaDeg ℤ = 2 := by
  have h₁ : ¬ 2 ∣ RingOfIntegers.exponent (integralGen K) := not_dvd_exponent_integralGen K 2
  have h₂ : (discr K / 4 : ℤ) = ((1 : ℤ) : ZMod 2) := by
    rw [ZMod.intCast_eq_intCast_iff']
    grind
  have h₃ : discr K % 4 = 1 := by grind
  have hd : (X ^ 2 - X - (1 : (ZMod 2)[X])).natDegree = 2 := by compute_degree!
  have h₄ : RingOfIntegers.monicFactorsMod (integralGen K) 2 =
      {X ^ 2 - X - 1} := by
    rw [RingOfIntegers.monicFactorsMod, minpoly_integralGen]
    simp only [h₃, map_one, one_mul, Polynomial.map_sub, Polynomial.map_pow, map_X, map_C,
      Int.coe_castRingHom, h₂, Int.cast_one]
    rw [UniqueFactorizationMonoid.normalizedFactors_irreducible,
      Monic.normalize_eq_self (by monicity!),
      Multiset.toFinset_singleton]
    exact Polynomial.irreducible_of_degree_le_three_of_not_isRoot (by simp [hd])
      (by simp [IsRoot.def])
  let 𝓟 : (span {(2 : ℤ)}).primesOver (𝓞 K) := ⟨P, ⟨inferInstance, inferInstance⟩⟩
  have h₂ := (primesOverSpanEquivMonicFactorsMod h₁ 𝓟).2
  simp only [h₄, Finset.mem_singleton] at h₂
  rw [inertiaDeg_primesOverSpanEquivMonicFactorsMod_apply h₁ 𝓟, h₂, hd]

/-- `2` is inert exactly when `discr K % 8 = 5`: `e = 1` at every prime above `2`. -/
theorem ramificationIdx_two_of_discr_emod_eight_five
    (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver (span {(2 : ℤ)})] :
    P.ramificationIdx ℤ = 1 := by
  have h' := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [inertiaDeg_two_of_discr_emod_eight_five h, ← mul_assoc, mul_eq_right₀ two_ne_zero] at h'
  exact Nat.eq_one_of_mul_eq_one_left h'

/-- `2` is inert exactly when `discr K % 8 = 5`: `g = 1`. -/
theorem ncard_primesOver_two_of_discr_emod_eight_five :
    ((span {(2 : ℤ)}).primesOver (𝓞 K)).ncard = 1 := by
  have : (span {(2 : ℤ)}).IsPrime := (span_singleton_prime two_ne_zero).mpr Int.prime_two
  obtain ⟨P, _, _⟩ := exists_isPrime_liesOver_of_faithfullyFlat (span {(2 : ℤ)}) (B := 𝓞 K)
  have h' := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [inertiaDeg_two_of_discr_emod_eight_five h, ← mul_assoc, mul_eq_right₀ two_ne_zero,
    ← over_def P (span {(2 : ℤ)})] at h'
  exact Nat.eq_one_of_mul_eq_one_right h'

end two_inert

section two_split

variable (h : discr K % 8 = 1)

include h

/-- `2` splits exactly when `discr K % 8 = 1`: `g = 2`. -/
theorem ncard_primesOver_two_of_discr_emod_eight_one :
    ((span {(2 : ℤ)}).primesOver (𝓞 K)).ncard = 2 := by
  have h₁ : ¬ 2 ∣ RingOfIntegers.exponent (integralGen K) := not_dvd_exponent_integralGen K 2
  have h₂ : (discr K / 4 : ℤ) = (0 : ZMod 2) := by
    grind [ZMod.intCast_zmod_eq_zero_iff_dvd, Int.dvd_iff_emod_eq_zero]
  have h₃ : discr K % 4 = 1 := by grind
  rw [show (2 : ℤ) = (2 : ℕ) by rfl, ← Nat.card_coe_set_eq,
    Nat.card_congr (primesOverSpanEquivMonicFactorsMod h₁), RingOfIntegers.monicFactorsMod,
    minpoly_integralGen, Polynomial.map_sub, Polynomial.map_sub, Polynomial.map_pow, map_X,
    Polynomial.map_mul, map_X, Polynomial.map_C, Polynomial.map_C, eq_intCast, h₃, eq_intCast, h₂,
    map_zero, sub_zero, Int.cast_one, map_one, one_mul,
    show (X : (ZMod 2)[X]) ^ 2 - X = X * (X - C 1) by polynomial,
    normalizedFactors_mul X_ne_zero (X_sub_C_ne_zero 1),
    normalizedFactors_irreducible (irreducible_X_sub_C 1),
    normalizedFactors_irreducible (irreducible_X), Multiset.singleton_add, Nat.card_eq_finsetCard,
    Multiset.toFinset_cons, Multiset.toFinset_singleton, Finset.card_pair]
  rw [(monic_X_sub_C 1).normalize_eq_self, (monic_X).normalize_eq_self]
  grind

/-- `2` splits exactly when `discr K % 8 = 1`: `e = 1` at every prime above `2`. -/
theorem ramificationIdx_two_of_discr_emod_eight_one
    (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver (span {(2 : ℤ)})] :
    P.ramificationIdx ℤ = 1 := by
  have h' := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [← over_def P (span {(2 : ℤ)}), ncard_primesOver_two_of_discr_emod_eight_one h,
    mul_eq_left₀ two_ne_zero] at h'
  exact Nat.eq_one_of_mul_eq_one_right h'

/-- `2` splits exactly when `discr K % 8 = 1`: `f = 1` at every prime above `2`. -/
theorem inertiaDeg_two_of_discr_emod_eight_one
    (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver (span {(2 : ℤ)})] :
    P.inertiaDeg ℤ = 1 := by
  have h' := ncard_primesOver_mul_ramificationIdx_mul_inertiaDeg P
  rw [← over_def P (span {(2 : ℤ)}), ncard_primesOver_two_of_discr_emod_eight_one h,
    mul_eq_left₀ two_ne_zero] at h'
  exact Nat.eq_one_of_mul_eq_one_left h'

end two_split

end NumberField.QuadraticField
