module

import Mathlib.Util.PrivateProof
import all Mathlib.Tactic.Linter.PrivateInPublic
import Lean.Elab.Command

/-!
# Tests for the `privateInPublic` linter

The linter reports on the terminal command, so to capture its messages we end the file with
`#guard_msgs in #exit`: `#exit` is a terminal command (`Lean.Parser.isTerminalCommand`), and
`#guard_msgs` re-runs the command it wraps through `elabCommandTopLevel`, which is what runs the
linters.
-/

public section

set_option backward.privateInPublic.warn false
set_option linter.privateInPublic true
-- The `privateProof` linter has plenty to say about the declarations below, and is tested
-- separately.
set_option linter.privateProof false

open Lean Elab Command

@[expose] def FEq (_ : (0 : Nat) = 0) := Bool

-- Exported, and nothing public uses it: its `set_option` should be deleted.
set_option backward.privateInPublic true in
private theorem unused : (0 : Nat) = 0 := rfl

-- Exported and used in the public type of `usesIt`: nothing to report.
set_option backward.privateInPublic true in
private theorem used : (0 : Nat) = 0 := rfl

set_option backward.privateInPublic true in
def usesIt (_ : FEq used) : Bool := true

-- Exported and used only from `chainOuter`, which is itself exported and unused: both should be
-- deleted. `chainOuter` carries two `set_option`s, and each is reported separately.
set_option backward.privateInPublic true in
private theorem chainInner : (0 : Nat) = 0 := rfl

set_option backward.privateInPublic.warn false in
set_option backward.privateInPublic true in
private def chainOuter (_ : FEq chainInner) : Bool := true

-- A single command declaring several candidates: `S` is used in the public type of `usesS`, while
-- its projection `S.k` is not. The `set_option` exports both, so it must be kept.
set_option backward.privateInPublic true in
private structure S where
  k : Nat

set_option backward.privateInPublic true in
def usesS (_ : S) : Bool := true

-- The `set_option` is doing two jobs: exporting `mixedPriv`, which nothing uses, and permitting
-- `mixedPub`'s exported signature to mention `used`. The latter is genuine work — `mixedPub` is
-- public whatever we do, so `used` stays in a public position — and so the `set_option` is kept.
-- (Wrapping that reference in `private` is the `privateProof` linter's business; once it is
-- wrapped, this `set_option` becomes deletable.)
set_option backward.privateInPublic true in
mutual
  def mixedPub (_ : FEq used) : Nat := 0
  private def mixedPriv : Nat := 1
end

-- The same, except that it is the *private* declaration whose signature refers to `used`, while
-- the public one refers to nothing private. Deleted, in contrast to the case above: `mixedPrivRef`
-- has a public form only because this very `set_option` exports it, so deleting the `set_option`
-- takes the reference with it. Elaboration of the signature does break, which is the point — it
-- marks the reference that needs reconfiguring.
set_option backward.privateInPublic true in
mutual
  def mixedPubPlain : Nat := 0
  private def mixedPrivRef (_ : FEq used) : Nat := 1
end

-- An entirely unused private structure. Most of the declarations this command adds are
-- autogenerated and have no declaration range, so attributing them by looking one up would report
-- only the handful that do.
set_option backward.privateInPublic true in
private structure T where
  j : Nat

-- A `set_option` doing nothing at all: it exports nothing and permits no public reference. We
-- report it even though there is no candidate to name, so that no `set_option` is left behind.
set_option backward.privateInPublic true in
def stray : Nat := 0

-- Not exported at all, so not a candidate.
private theorem plain : (0 : Nat) = 0 := rfl

@[expose] def usesPlain : Type := FEq (private plain)

/--
warning: using 'exit' to interrupt Lean
---
info: `unused` exported only because of this `set_option`, but nothing public uses it; delete it:
  [apply] (delete)
---
info: `chainInner` exported only because of this `set_option`, but nothing public uses it; delete it:
  [apply] (delete)
---
info: `chainOuter` exported only because of this `set_option`, but nothing public uses it; delete it:
  [apply] (delete)
---
info: `chainOuter` exported only because of this `set_option`, but nothing public uses it; delete it:
  [apply] (delete)
---
info: `mixedPrivRef` exported only because of this `set_option`, but nothing public uses it; delete it:
  [apply] (delete)
---
info: `T`, `T.j`, `T.mk` and 13 more exported only because of this `set_option`, but nothing public uses it; delete it:
  [apply] (delete)
---
info: This `set_option` exports nothing and permits no public reference; delete it:
  [apply] (delete)
-/
#guard_msgs in
#exit

-- `#exit` inside `#guard_msgs` does not stop the outer frontend, so the linter also runs on
-- the real end-of-input token. Disable it so that that run is silent.
set_option linter.privateInPublic false
