/-
Copyright (c) 2026 Edison Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Edison Xu
-/
module

public import Mathlib.Algebra.Order.GroupWithZero.Subgroup
public import Mathlib.Topology.Algebra.WithZeroTopology

/-!
# The topology on a subgroup with zero

A subgroup with zero of a `LinearOrderedCommGroupWithZero` is itself a
`LinearOrderedCommGroupWithZero`, and so carries its own `WithZeroTopology`. This file declares
that topology at a priority high enough to beat `instTopologicalSpaceSubtype`.

## Implementation notes

**This deliberately overrides the subspace topology, because the two genuinely differ.**

`SubgroupWithZero` is `SetLike`, so `↥s` is a subtype of the ambient `Γ₀`; once `Γ₀` carries the
`WithZeroTopology`, `instTopologicalSpaceSubtype` applies to `↥s` at the default priority and
would silently win over `WithZeroTopology.topologicalSpace`, which is scoped at priority 100.
That would be the wrong topology.

They agree only when the ambient group is mul-archimedean over `s`. For a concrete failure, take
`Γ₀ = WithZero (Multiplicative (ℤ ×ₗ ℤ))` and let `s` be generated by `exp (0, 1)`. In the
lexicographic order `(-1, 0) < (0, n)` for every `n`, so
`{y ∈ s | y < exp (-1, 0)} = {0}` and `0` is *isolated* in the subspace topology. In the
`WithZeroTopology` of `s` it is not: every basic neighbourhood `{y ∈ s | y < exp (0, -n)}`
contains `exp (0, m)` for `m < -n`.

The `WithZeroTopology` is the one that matters for valuation theory — it is what makes
`Valued.continuous_valuation` and the `Valued` neighbourhood bases say what they are meant to say
— so it is the one declared here.

Like `WithZeroTopology.topologicalSpace` itself, this is a scoped instance: activate it with
`open WithZeroTopology`.
-/

@[expose] public section

namespace WithZeroTopology

variable {Γ₀ S : Type*} [LinearOrderedCommGroupWithZero Γ₀] [SetLike S Γ₀]
  [SubgroupWithZeroClass S Γ₀]

/-- A subgroup with zero carries its own `WithZeroTopology`, **not** the subspace topology
induced from the ambient group. See the module docstring: the two are genuinely different
topologies, and this one is the one valuation theory needs.

The priority must exceed that of `instTopologicalSpaceSubtype`. -/
scoped instance (priority := 2000) instSubgroupWithZero (s : S) : TopologicalSpace s :=
  WithZeroTopology.topologicalSpace

lemma instSubgroupWithZero_eq (s : S) :
    (instSubgroupWithZero s) = (WithZeroTopology.topologicalSpace : TopologicalSpace s) := rfl

end WithZeroTopology
