/-
Copyright (c) 2025 Jiedong Jiang, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johan Commelin, Jiedong Jiang, Christian Merten
-/
module

public import Mathlib.Topology.Spectral.Basic
public import Mathlib.Topology.JacobsonSpace
public import Mathlib.Data.Set.Card
public import Mathlib.Topology.Constructible

/-!
# Constructible topology

In this file we define the constructible topology on a topological space. This is the topology
generated by compact open subsets and their complements.

## Main definitions and results

- `WithConstructibleTopology`: `X` equipped with its constructible topology.
- `compactSpace_withConstructibleTopology`: If `X` is quasi-separated, quasi-sober,
  prespectral and quasi-compact, then `X` is still quasi-compact in the constructible topology.

## TODOs

- If `X` is a spectral space, show that `X` is T2 and totally disconnected (@chrisflav).
-/

@[expose] public section

variable {X : Type*} [TopologicalSpace X]

/-- The subbasis of the constructible topology on a topological space `X`: It consists
of the open and compact sets of `X` and their complements. -/
def constructibleTopologySubbasis (X : Type*) [TopologicalSpace X] : Set (Set X) :=
  { s | IsOpen s ∧ IsCompact s } ∪ { s | IsClosed s ∧ IsCompact sᶜ }

/-- The constructible topology on a topological space `X` has as a subbasis
the open and compact sets of `X` and their complements. -/
@[implicit_reducible]
def constructibleTopology (X : Type*) [TopologicalSpace X] : TopologicalSpace X :=
  .generateFrom (constructibleTopologySubbasis X)

/-- A type synonym for `X` that is equipped with the constructible topology of `X`. -/
@[nolint unusedArguments]
def WithConstructibleTopology (X : Type*) [TopologicalSpace X] : Type _ :=
  X

instance : TopologicalSpace (WithConstructibleTopology X) :=
  fast_instance% constructibleTopology X

open Topology

lemma IsCompact.isOpen_constructibleTopology_of_isOpen {s : Set X}
    (hs : IsCompact s) (ho : IsOpen s) : IsOpen[constructibleTopology X] s := by
  apply TopologicalSpace.isOpen_generateFrom_of_mem
  simp [constructibleTopologySubbasis, ho, hs]

lemma IsCompact.isOpen_constructibleTopology_of_isClosed {s : Set X}
    (hs : IsCompact sᶜ) (ho : IsClosed s) : IsOpen[constructibleTopology X] s := by
  apply TopologicalSpace.isOpen_generateFrom_of_mem
  simp [constructibleTopologySubbasis, ho, hs]

@[simp]
lemma compl_mem_constructibleTopologySubbasis_iff {s : Set X} :
    sᶜ ∈ constructibleTopologySubbasis X ↔ s ∈ constructibleTopologySubbasis X := by
  grind [constructibleTopologySubbasis, isClosed_compl_iff, compl_compl]

lemma isCompact_of_mem_constructibleTopologySubbasis [CompactSpace X] {s : Set X}
    (hs : s ∈ constructibleTopologySubbasis X) : IsCompact s := by
  obtain (hs | hs) := hs
  · exact hs.2
  · exact hs.1.isCompact

lemma isCompact_sInter_of_subset_constructibleTopologySubbasis [CompactSpace X]
    [QuasiSeparatedSpace X] {s : Set (Set X)} (hs : s ⊆ constructibleTopologySubbasis X)
    (hf : s.Finite) : IsCompact (⋂₀ s) := by
  refine QuasiSeparatedSpace.isCompact_sInter hf (fun t ht ↦ ?_) (fun t ht ↦ ?_)
  · apply (hs ht).imp <;> grind
  · exact isCompact_of_mem_constructibleTopologySubbasis (hs ht)

/-- If `X` is quasi-separated, quasi-sober, prespectral and quasi-compact, then `X`
is still quasi-compact in the constructible topology. This holds in particular for spectral
spaces. -/
@[stacks 0901 "quasi-compactness"]
instance compactSpace_withConstructibleTopology [CompactSpace X] [QuasiSober X]
    [PrespectralSpace X] [QuasiSeparatedSpace X] :
    CompactSpace (WithConstructibleTopology X) := by
  let 𝔅 := constructibleTopologySubbasis X
  /- It suffices to check that any subset of `𝔅` for which every finite subset has non-empty
  intersection, has non-empty intersection. We argue by contradiction and by Zorn's
  lemma, we may take a maximal counterexample `B`. -/
  apply compactSpace_generateFrom_of_compl_mem (T := constructibleTopology X) 𝔅 rfl (by simp [𝔅])
  let 𝒮 := {P : Set (Set X) | P ⊆ 𝔅 ∧ (∀ Q ⊆ P, Q.Finite → (⋂₀ Q).Nonempty) ∧ (⋂₀ P) = ∅}
  suffices 𝒮 = ∅ by contrapose! this; tauto
  by_contra! h𝒮
  obtain ⟨s, hs⟩ := h𝒮
  obtain ⟨B, hsB, hB⟩ := by
    refine zorn_subset_nonempty 𝒮 (fun c hc𝒮 hc hne@⟨x, hxc⟩ ↦ ?_) s hs
    refine ⟨⋃₀ c, ?_, fun S hSc ↦ Set.subset_sUnion_of_subset c S subset_rfl hSc⟩
    refine ⟨by grind, fun a hac ha ↦ ?_, by grind⟩
    obtain ⟨i, hmem, hsub⟩ := hc.directedOn.exists_mem_subset_of_finite_of_subset_sUnion hne ha hac
    exact (hc𝒮 hmem).2.1 a hsub ha
  let B' := {s | s ∈ B ∧ IsClosed s}
  /- Let `Z` be the intersection of all closed sets in `B`. We argue
  by cases if `Z` is irreducible or not. -/
  let Z := ⋂₀ B'
  have hZ_closed : IsClosed Z := isClosed_sInter fun b hb ↦ hb.2
  have hZ_nonempty : Z.Nonempty :=
    CompactSpace.nonempty_sInter (fun _ ht ↦ ht.2) fun t ht hf ↦
      hB.prop.2.1 _ (subset_trans ht (by simp [B'])) hf
  by_cases hZ_irred : IsIrreducible Z
  · -- If `Z` is irreducible, the intersection `⋂₀ B` contains the generic point of `Z`.
    suffices (⋂₀ B).Nonempty by simp_all [hB.prop.2.2]
    have hη := hZ_irred.isGenericPoint_genericPoint (isClosed_sInter fun b hb ↦ hb.2)
    refine ⟨hZ_irred.genericPoint, ?_⟩
    rw [Set.mem_sInter]
    intro i hi
    by_cases hiB' : i ∈ B'
    · exact Set.sInter_subset_of_mem hiB' hη.mem
    · have hi_cmpt : IsCompact i := by grind [hB.prop, constructibleTopologySubbasis]
      rw [hη.mem_open_set_iff (by grind [hB.prop, constructibleTopologySubbasis]), Set.inter_comm]
      refine hi_cmpt.nonempty_inter_sInter (fun _ hb ↦ hb.2) fun a ha hfa ↦ ?_
      rw [← Set.sInter_insert]
      exact hB.prop.2.1 _ (by grind) (by simpa)
  · -- If `Z` is reducible, there exist closed compacts `Y₁` and `Y₂` such that `Z ⊆ Y₁ ∪ Y₂`.
    simp only [IsIrreducible, hZ_nonempty, true_and] at hZ_irred
    obtain ⟨Y₁, Y₂, hY₁_cl, hY₂_cl, hc₁, hc₂, hsub, ⟨x₁, hx₁⟩, ⟨x₂, hx₂⟩⟩ :=
      PrespectralSpace.exists_isClosed_of_not_isPreirreducible _ hZ_irred
    have hY₁ : Y₁ ∈ 𝔅 := .inr ⟨hY₁_cl, hc₁⟩
    have hY₂ : Y₂ ∈ 𝔅 := .inr ⟨hY₂_cl, hc₂⟩
    have hY₁_inter_B : Y₁ ∩ ⋂₀ B = ∅ := by grind
    have hY₂_inter_B : Y₂ ∩ ⋂₀ B = ∅ := by grind
    -- By maximality of `B`, neither `B ∪ {Y₁}` nor `B ∪ {Y₂}` is contained in `𝒮`
    have hY₁B : insert Y₁ B ∉ 𝒮 := by
      intro hY₁B
      grind [show insert Y₁ B ⊆ B from hB.le_of_ge hY₁B (Set.subset_insert Y₁ B)]
    have hY₂B : insert Y₂ B ∉ 𝒮 := by
      intro hY₂B
      grind [show insert Y₂ B ⊆ B from hB.le_of_ge hY₂B (Set.subset_insert Y₂ B)]
    dsimp [𝒮] at hY₁B hY₂B
    simp only [Set.insert_subset_iff, hY₁, hB.prop.1, and_self, Set.sInter_insert, hY₁_inter_B,
      and_true, true_and, not_forall, Set.not_nonempty_iff_eq_empty, hY₂, hY₂_inter_B] at hY₁B hY₂B
    -- Hence there exist finitely many `{Aᵢ} ⊆ B` such that `Z ∩ ⋂ Aᵢ = ∅`.
    obtain ⟨A₁, hA₁, hA₁', hA₁''⟩ := hY₁B
    obtain ⟨A₂, hA₂, hA₂', hA₂''⟩ := hY₂B
    have : Z ∩ ⋂₀ (A₁ \ {Y₁} ∪ A₂ \ {Y₂}) = ∅ := by grind
    rw [← Set.not_nonempty_iff_eq_empty] at this
    apply this
    rw [Set.inter_comm]
    refine IsCompact.nonempty_inter_sInter ?_ (fun _ hb ↦ hb.2) fun F hsub hF ↦ ?_
    · apply isCompact_sInter_of_subset_constructibleTopologySubbasis _ (hA₁'.diff.union hA₂'.diff)
      grind [hB.prop, Set.union_subset_iff]
    · rw [← Set.sInter_union]
      refine hB.prop.2.1 (_ ∪ F) ?_ <| (hA₁'.diff.union hA₂'.diff).union hF
      grind [Set.diff_singleton_subset_iff, Set.union_subset_iff]

variable {Y : Type*} [TopologicalSpace Y]

instance [PrespectralSpace X] [T0Space X] [QuasiSober X] :
    T2Space <| WithConstructibleTopology X where
  t2 := by
    intro x y hxy
    obtain ⟨U, hU, (⟨hxU, hyU⟩ | ⟨hyU, hxU⟩)⟩ := exists_isOpen_xor_mem (X := X) hxy <;>
      obtain ⟨V, ⟨hVo, hVc⟩, hV, hVU⟩ :=
        PrespectralSpace.isTopologicalBasis.mem_nhds_iff.mp (hU.mem_nhds ‹_›)
    · exact ⟨V, Vᶜ,
        TopologicalSpace.isOpen_generateFrom_of_mem (.inl ⟨hVo, hVc⟩),
        TopologicalSpace.isOpen_generateFrom_of_mem
          (Or.inr ⟨hVo.isClosed_compl, (compl_compl V).symm ▸ hVc⟩),
        hV, Set.mem_compl (fun h ↦ hyU (hVU h)), disjoint_compl_right⟩
    · exact ⟨Vᶜ, V,
        TopologicalSpace.isOpen_generateFrom_of_mem
          (Or.inr ⟨hVo.isClosed_compl, (compl_compl V).symm ▸ hVc⟩),
        TopologicalSpace.isOpen_generateFrom_of_mem (.inl ⟨hVo, hVc⟩),
        Set.mem_compl (fun h ↦ hxU (hVU h)), hV, disjoint_compl_left⟩

/--
Canoical map from a space `X` to `WithConstructibleTopology X`
-/
def toConstructibleTopology (X) [TopologicalSpace X] : X ≃ WithConstructibleTopology X :=
  Equiv.refl _

/--
Canoical map from a space `WithConstructibleTopology X` to `X`
-/
def ofConstructibleTopology (X) [TopologicalSpace X] : WithConstructibleTopology X ≃ X :=
  Equiv.refl _

/--
Induced map `lift f : WithConstructibleTopology X → WithConstructibleTopology Y` by a map
`f : X → Y`
-/
def WithConstructibleTopology.lift (f : X → Y) :
    WithConstructibleTopology X → WithConstructibleTopology Y :=
  toConstructibleTopology Y ∘ f ∘ ofConstructibleTopology X

/--
The map from `X` with the constructible topology to `X` is continuous if `X` is prespectral.
-/
lemma ofConstructibleTopology_continuous [PrespectralSpace X] :
    Continuous <| ofConstructibleTopology X := by
  rw [TopologicalSpace.IsTopologicalBasis.continuous_iff (PrespectralSpace.isBasis_opens X)]
  intro U ⟨hU1, hU2, hU3⟩
  convert hU2.isOpen_constructibleTopology_of_isOpen hU1.2
  simp [hU3, ofConstructibleTopology]
  rfl

lemma WithConstructibleTopology.lift_continuous {f : X → Y} (hf : IsSpectralMap f) :
    Continuous <| WithConstructibleTopology.lift f := by
  apply continuous_generateFrom_iff.mpr
  intro s hs
  obtain ⟨hso, hsc⟩ | ⟨hscl, hsc⟩ := hs
  · exact (hf.isCompact_preimage_of_isOpen hso hsc).isOpen_constructibleTopology_of_isOpen
      (hso.preimage hf.continuous)
  · exact
    (hf.isCompact_preimage_of_isOpen hscl.isOpen_compl hsc).isOpen_constructibleTopology_of_isClosed
      (hscl.preimage hf.continuous)

lemma Topology.IsOpenEmbedding.isSpectralMap_of_compactSpace {f : X → Y} [CompactSpace X]
    (hf : Topology.IsOpenEmbedding f) [QuasiSeparatedSpace Y] :
  IsSpectralMap f := ⟨hf.continuous, fun _ hU hU' ↦ IsRetrocompact.isCompact <|
    IsRetrocompact.preimage_of_isOpenEmbedding hf <| hU'.isRetrocompact hU⟩

/--
A spectral map between *quasi-separated* quasispectral, sober spaces has compact fibers.
Somewhat strangely, this is the strongest such statement we can figure out how to show.
This is weird because compactness of fibers is a purely topological property,
and yet there is an analogous theorem in algebraic geometry saying that the fibers of a quasicompact
morphism are quasicompact. The underlying space of a scheme is precisely a topological space which
is locally a spectral space, which notably does not necessarily have any global quasi-separatedness
assumptions. However, the proof of this fact is very algebraic (utilizing the fact that
quasi-compactness of morphisms is closed under base change). So, we have that this purely
topological property of quasicompact morphisms of schemes seems to be entirely a consequence of
algebra.
-/
lemma IsSpectralMap.hasCompactFibers [PrespectralSpace X] [T0Space X] [QuasiSeparatedSpace X]
    [QuasiSober X] [PrespectralSpace Y] [T0Space Y] [QuasiSeparatedSpace Y] [QuasiSober Y]
    {f : X → Y} (hf : IsSpectralMap f) : HasCompactFibers f := by
  intro y
  -- Take a compact open neighbourhood U of y (exists since Y is prespectral)
  obtain ⟨U, ⟨hUo, hUc⟩, hyU, -⟩ :=
    (PrespectralSpace.isTopologicalBasis (X := Y)).mem_nhds_iff.mp (isOpen_univ.mem_nhds trivial)
  -- f ⁻¹' U is compact and open (spectral map + U compact open)
  have hfUo : IsOpen (f ⁻¹' U) := hUo.preimage hf.continuous
  have hfUc : IsCompact (f ⁻¹' U) := hf.isCompact_preimage_of_isOpen hUo hUc
  -- f ⁻¹' U is an open subspace, inheriting all the needed instances
  have hfU_oe : IsOpenEmbedding (Subtype.val : ↥(f ⁻¹' U) → X) := hfUo.isOpenEmbedding_subtypeVal
  have : CompactSpace ↥(f ⁻¹' U) := isCompact_iff_compactSpace.mp hfUc
  have : PrespectralSpace ↥(f ⁻¹' U) := hfU_oe.prespectralSpace
  have : QuasiSeparatedSpace ↥(f ⁻¹' U) := hfU_oe.quasiSeparatedSpace
  have : QuasiSober ↥(f ⁻¹' U) := hfU_oe.quasiSober
  let g := f ∘ (Subtype.val : f ⁻¹' U → X)
  have hg : IsSpectralMap g :=
    hf.comp hfUo.isOpenEmbedding_subtypeVal.isSpectralMap_of_compactSpace
  suffices h : f ⁻¹' {y} = Subtype.val '' (g ⁻¹' {y}) by
    rw [h]
    exact
      (isClosed_singleton.preimage (WithConstructibleTopology.lift_continuous hg)).isCompact.image
      (continuous_subtype_val.comp ofConstructibleTopology_continuous)
  ext x
  simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_image, g, Function.comp,
    Subtype.exists]
  exact ⟨fun hfx => ⟨x, hfx ▸ hyU, hfx, rfl⟩, fun ⟨_, _, hfa, rfl⟩ => hfa⟩
