/-
Copyright (c) 2026 University of Washington Math AI Lab. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bianca Viray, Bryan Boehnke, Grant Yang, George Peykanu, Tianshuo Wang
-/

module

public import Mathlib.RingTheory.Unramified.LocalRing
public import Mathlib.RingTheory.Smooth.Flat
public import Mathlib.RingTheory.LocalRing.Module
public import Mathlib.RingTheory.LocalRing.Quotient
public import Mathlib.RingTheory.IsAdjoinRoot

/-!
# Étale extensions of local rings

We prove that a finite étale extension of local rings is monogenic (generated by a single element),
and that the derivative of the minimal polynomial evaluated at the generator is a unit.
These are parts 1 and 2 of Lemma 3.2 of [arXiv:2503.07846](https://arxiv.org/abs/2503.07846).

## Main results

* `IsLocalRing.exists_adjoin_eq_top`: a finite étale extension of local rings is generated by a
  single element (Lemma 3.2, part 1).
* `IsLocalRing.isUnit_aeval_derivative_minpoly_of_adjoin_eq_top`: if `R → S` is étale and
  `R[β] = S`, then `f'(β)` is a unit, where `f = minpoly R β` (Lemma 3.2, part 2).

## Key intermediate results

* `IsLocalRing.adjoin_residue_eq_top_of_adjoin_eq_top`: if `β` generates `S` over `R`, then
  `β mod m_S` generates `S/m_S` over `R/m_R`.
* `IsLocalRing.finrank_eq_finrank_residueField`: for finite étale extensions of local rings,
  `finrank R S = finrank (ResidueField R) (ResidueField S)`.
* `IsLocalRing.minpoly_map_residue`: the minimal polynomial of `β` over `R` maps to the
  minimal polynomial of `β mod m_S` over the residue field.

## Future work

The following results from [arXiv:2503.07846](https://arxiv.org/abs/2503.07846) (formalized at [uw-math-ai/monogenic-extensions](https://github.com/uw-math-ai/monogenic-extensions)) are planned for
future PRs:

* **Converse**: If `S ≅ R[X]/(f)` with `f` monic and `f'(root)` a unit, then `R → S` is étale.
* **Lemma 3.1** (partial étale case): If `R` and `S` are local integral domains with `R`
  integrally closed, `S` a UFD, `R → S` finite and injective, and there exists a height-one
  prime `q ⊆ S` such that `R/(q ∩ R) → S/q` is étale, then `S ≅ R[X]/(f)` for some monic `f`.

## Tags

étale, monogenic, local ring, minimal polynomial, residue field
-/

@[expose] public section

namespace IsLocalRing

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    [IsLocalRing S] [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S]

open Polynomial in
/-- A finite étale extension of local rings is generated by a single element.
This is Lemma 3.2, part 1 of [arXiv:2503.07846](https://arxiv.org/abs/2503.07846).
The proof lifts a primitive element of the residue field extension via Nakayama's lemma. -/
theorem exists_adjoin_eq_top [Algebra.Etale R S] :
    ∃ β : S, Algebra.adjoin R {β} = ⊤ := by
  obtain ⟨β₀, hβ₀⟩ := Field.exists_primitive_element (IsLocalRing.ResidueField R)
    (IsLocalRing.ResidueField S)
  obtain ⟨β, hβ⟩ := Ideal.Quotient.mk_surjective β₀
  refine ⟨β, ?_⟩
  have h_adjoin_top : Algebra.adjoin (IsLocalRing.ResidueField R) {β₀} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic β₀), hβ₀, IntermediateField.top_toSubalgebra]
  rw [show β₀ = IsLocalRing.residue S β from hβ.symm,
    Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at h_adjoin_top
  set mR := IsLocalRing.maximalIdeal R
  have h_le_sup : (⊤ : Submodule R S) ≤ (Algebra.adjoin R {β}).toSubmodule ⊔ mR • ⊤ := by
    intro s _
    obtain ⟨p, hp⟩ := h_adjoin_top (IsLocalRing.residue S s)
    obtain ⟨q, rfl⟩ := Polynomial.map_surjective _ IsLocalRing.residue_surjective p
    rw [Ideal.smul_top_eq_map]
    refine Submodule.mem_sup.mpr ⟨aeval β q, ?_, s - aeval β q, ?_, by ring⟩
    · rw [Algebra.adjoin_singleton_eq_range_aeval]; exact ⟨q, rfl⟩
    · exact (Algebra.FormallyUnramified.map_maximalIdeal (R := R) (S := S)) ▸
        Ideal.Quotient.eq.mp
          (show IsLocalRing.residue S s = IsLocalRing.residue S (aeval β q) by
            rw [map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
              (φ := IsLocalRing.residue R) rfl, hp])
  exact eq_top_iff.mpr (Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) h_le_sup)

-- ResidueField.Basic does not import Algebra stuff.
/-- When `β` generates `S` over `R`, the residue `β₀ = β mod m_S`
generates `S/m_S` over `R/m_R`. -/
lemma adjoin_residue_eq_top_of_adjoin_eq_top
    {β : S} (hβ_gen : Algebra.adjoin R {β} = ⊤) :
    Algebra.adjoin (IsLocalRing.ResidueField R) {IsLocalRing.residue S β} = ⊤ := by
  rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at *
  intro x
  obtain ⟨s, rfl⟩ := IsLocalRing.residue_surjective (R := S) x
  obtain ⟨p, rfl⟩ := hβ_gen s
  exact ⟨p.map (IsLocalRing.residue R),
    (Polynomial.map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
      (φ := IsLocalRing.residue R) rfl p β).symm⟩

-- Q: Is this in the right level of generality?
-- consider adding the maximal ideals mapping as an explicit
-- hypothesis instead of using Algebra.Etale.
/-- For finite étale extensions of local rings,
`finrank R S = finrank (ResidueField R) (ResidueField S)`. -/
lemma finrank_eq_finrank_residueField [Algebra.Etale R S] :
    Module.finrank R S =
      Module.finrank (IsLocalRing.ResidueField R) (IsLocalRing.ResidueField S) := by
  haveI : Module.Free R S := Module.free_of_flat_of_isLocalRing
  have hmaximal : Ideal.map (algebraMap R S) (IsLocalRing.maximalIdeal R) =
      IsLocalRing.maximalIdeal S := Algebra.FormallyUnramified.map_maximalIdeal
  let e : (S ⧸ Ideal.map (algebraMap R S) (IsLocalRing.maximalIdeal R))
      ≃ₗ[R ⧸ IsLocalRing.maximalIdeal R] (S ⧸ IsLocalRing.maximalIdeal S) :=
    AddEquiv.toLinearEquiv (Ideal.quotEquivOfEq hmaximal).toAddEquiv (fun r x => by
      obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective r
      obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective x
      simp only [RingEquiv.toAddEquiv_eq_coe]; rfl)
  erw [← e.finrank_eq, IsLocalRing.finrank_quotient_map (R := R) (S := S)]

/-- For a monogenic étale extension of local rings, the minimal polynomial of `β`
maps to the minimal polynomial of `β mod m_S` over the residue field. -/
lemma minpoly_map_residue [Algebra.Etale R S]
    {β : S} (hadj : Algebra.adjoin R {β} = ⊤) :
    (minpoly R β).map (IsLocalRing.residue R) = minpoly (IsLocalRing.ResidueField R)
      (IsLocalRing.residue S β) := by
  have hmonic := minpoly.monic <| Algebra.IsIntegral.isIntegral (R:=R) β
  let kR := IsLocalRing.ResidueField R
  let β₀ := IsLocalRing.residue S β
  let f_bar := (minpoly R β).map (IsLocalRing.residue R)
  have hβ₀_int : IsIntegral kR β₀ := Algebra.IsIntegral.isIntegral β₀
  -- β₀ is a root of f_bar, so minpoly kR β₀ divides f_bar
  have hdvd : minpoly kR β₀ ∣ f_bar := minpoly.dvd kR β₀ (by
    rw [← Polynomial.map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
      (φ := IsLocalRing.residue R) rfl, minpoly.aeval, map_zero])
  have hβ₀_gen : Algebra.adjoin kR {β₀} = ⊤ := adjoin_residue_eq_top_of_adjoin_eq_top hadj
  have hβ₀_field_gen : IntermediateField.adjoin kR {β₀} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic β₀)] at hβ₀_gen
    exact IntermediateField.toSubalgebra_injective hβ₀_gen
  have hdeg_eq : f_bar.natDegree = (minpoly kR β₀).natDegree := by
    haveI : Module.Free R S := Module.free_of_flat_of_isLocalRing
    rw [hmonic.natDegree_map _,
      ← (IsAdjoinRootMonic.mkOfAdjoinEqTop' hadj).finrank,
      finrank_eq_finrank_residueField, ← IntermediateField.finrank_top', ← hβ₀_field_gen,
      IntermediateField.adjoin.finrank hβ₀_int]
  exact Polynomial.eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hβ₀_int)
    (hmonic.map _) hdvd hdeg_eq.le

open Polynomial in
/-- If `R → S` is étale and `R[β] = S`, then `f'(β)` is a unit in `S`,
where `f = minpoly R β`. The proof reduces to separability of the
residue field extension via `minpoly_map_residue`. -/
lemma isUnit_aeval_derivative_minpoly_of_adjoin_eq_top
    [Algebra.Etale R S] {β : S}
    (hadj : Algebra.adjoin R {β} = ⊤) :
    IsUnit (aeval β (minpoly R β).derivative) := by
  apply fun s => (IsLocalRing.residue_ne_zero_iff_isUnit s).mp
  let kR := IsLocalRing.ResidueField R
  let β₀ := IsLocalRing.residue S β
  have hderiv_ne_zero : aeval β₀ (minpoly kR β₀).derivative ≠ 0 :=
    (Algebra.IsSeparable.isSeparable kR β₀).aeval_derivative_ne_zero (minpoly.aeval kR β₀)
  rw [map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
    (φ := IsLocalRing.residue R) rfl, ← derivative_map, minpoly_map_residue hadj]
  exact hderiv_ne_zero

end IsLocalRing

end
