/-
Copyright (c) 2025 Amelia Livingston. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Amelia Livingston
-/
import Mathlib.RepresentationTheory.Homological.FiniteCyclic
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Basic

/-!
# Group cohomology of a finite cyclic group

Let `k` be a commutative ring and `G` a finite commutative group. Given `g : G` and `A : Rep k G`,
we can define a periodic chain complex in `Rep k G` given by
`... ⟶ A --N--> A --(ρ(g) - 𝟙)--> A --N--> A --(ρ(g) - 𝟙)--> A ⟶ 0`
where `N` is the norm map. When `G` is generated by `g` and `A` is the left regular representation
`k[G]`, it is a projective resolution of `k` as a trivial representation.

yadda yadda. -/

universe v u

open CategoryTheory

namespace Rep.finiteCyclicGroup

variable {k G : Type u} [CommRing k] [CommGroup G] [Fintype G] (g : G)
  (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G)

/-- Given a finite cyclic group `G` generated by `g : G` and a `k`-linear `G`-representation `A`,
the periodic cochain complex
```
0 ⟶ Hom(k[G], A) --(- ∘ (ρ(g) - 𝟙))--> Hom(k[G], A) --(- ∘ N)--> Hom(k[G], A) ⟶ ...
```
is isomorphic as a complex in `ModuleCat k` to
```
0 ⟶ A --(ρ(g) - 𝟙)--> A --N--> A --(ρ(g) - 𝟙)--> A --N--> A ⟶ ...
```
-/
@[simps!]
noncomputable def homResolutionIso :
    (resolution k g hg).complex.linearYonedaObj k A ≅ moduleCatCochainComplex A g :=
  HomologicalComplex.Hom.isoOfComponents (fun _ => (leftRegularHomEquiv A).toModuleIso) <| by
    rintro i j ⟨rfl⟩
    ext (x : leftRegular _ _ ⟶ _)
    by_cases hi : Even i
    · have : ¬(Even (i + 1)) := (not_iff_comm.1 Nat.even_add_one.symm).2 hi
      simp [hi, this, sub_eq_add_neg, ← hom_comm_apply x]
    · simp [hi, Nat.even_add_one.2 hi, Representation.norm,
        ← hom_comm_apply x]

open ShortComplex Limits

/-- Given a finite cyclic group `G` generated by `g` and `A : Rep k G`, `H⁰(G, A)` is isomorphic
to the kernel of `ρ(g) - Id(A)`. -/
noncomputable def groupCohomologyIso₀
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) :
    groupCohomology A 0 ≅ (mk _ (applyAsHom A g - 𝟙 A).hom (zero_comp (X := A.V))).cycles :=
  groupCohomologyIso A 0 (resolution k g hg) ≪≫
  HomologicalComplex.homologyMapIso (homResolutionIso g hg A) 0 ≪≫
  (CochainComplex.isoHomologyπ₀ _).symm ≪≫
  cyclesMapIso (HomologicalComplex.isoSc' _ 0 0 1 (by simp) (by simp))

/-- Given a finite cyclic group `G` generated by `g` and `A : Rep k G`, `Hⁱ(G, A)` is isomorphic
to the homology of the short complex of `k`-modules `A --N--> A --(ρ(g) - 𝟙)--> A` when `i` is
nonzero and even. -/
noncomputable def groupCohomologyEvenIso
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) [h₀ : NeZero i] (hi : Even i) :
    groupCohomology A i ≅ (normHomCompSub A g).homology :=
  groupCohomologyIso A i (resolution k g hg) ≪≫
  (HomologicalComplex.homologyMapIso (homResolutionIso g hg A) i) ≪≫
  HomologicalComplex.alternatingConstHomologyEvenIso A.V
    (by ext; simp [sub_eq_add_neg]) (by ext; simp [sub_eq_add_neg]) (by simp)
    (by induction i generalizing h₀ with | zero => exact (NeZero.ne 0 rfl).elim | succ n _ => simp)
    (by simp) hi

open groupCohomology

namespace groupCohomology

/-- Given a finite cyclic group `G` generated by `g` and `A : Rep k G`, this is the quotient map
`Ker(ρ(g) - Id(A)) ⟶ Ker(ρ(g) - Id(A))/Im(N) ≅ Hⁱ(G, A)` for any nonzero even `i`. -/
noncomputable abbrev πEven
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) [NeZero i] (hi : Even i) :
    ModuleCat.of k (LinearMap.ker (applyAsHom A g - 𝟙 A).hom.hom) ⟶ groupCohomology A i :=
    (moduleCatCyclesIso <| normHomCompSub A g).inv ≫
      ShortComplex.homologyπ _ ≫ (groupCohomologyEvenIso g hg A i hi).inv

lemma πEven_eq_zero_iff
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) [NeZero i] (hi : Even i)
    (x : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.hom) :
    πEven g hg A i hi x = 0 ↔ x.1 ∈ LinearMap.range A.norm.hom.hom := by
  simp [πEven, map_eq_zero_iff _ ((ModuleCat.mono_iff_injective _).1 inferInstance),
    moduleCatToCycles, -LinearMap.mem_range, LinearMap.range_codRestrict]

lemma πEven_eq_iff {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) [NeZero i] (hi : Even i)
    (x y : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.hom) :
    πEven g hg A i hi x = πEven g hg A i hi y ↔ x.1 - y.1 ∈ LinearMap.range A.norm.hom.hom := by
  rw [← sub_eq_zero, ← map_sub, πEven_eq_zero_iff]; rfl

/-- Given a finite cyclic group `G` generated by `g` and `A : Rep k G`, `Hⁱ(G, A)` is isomorphic
to the homology of the short complex of `k`-modules `A --(ρ(g) - 𝟙)--> A --N--> A` when `i` is
odd. -/
noncomputable def groupCohomologyOddIso
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) (hi : Odd i) :
    groupCohomology A i ≅ (subCompNormHom A g).homology :=
  groupCohomologyIso A i (resolution k g hg) ≪≫
  (HomologicalComplex.homologyMapIso (homResolutionIso g hg A) i) ≪≫
  HomologicalComplex.alternatingConstHomologyOddIso A.V (by ext; simp [sub_eq_add_neg])
    (by ext; simp [sub_eq_add_neg]) (by simp) (by rcases hi with ⟨j, rfl⟩; simp) (by simp) hi

/-- Given a finite cyclic group `G` generated by `g` and `A : Rep k G`, this is the quotient map
`Ker(N) ⟶ Ker(N)/Im(ρ(g) - Id(A)) ≅ Hⁱ(G, A)` for any odd `i`. -/
noncomputable abbrev πOdd
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) (hi : Odd i) :
    ModuleCat.of k (LinearMap.ker A.norm.hom.hom) ⟶ groupCohomology A i :=
    (moduleCatCyclesIso <| subCompNormHom A g).inv ≫
      ShortComplex.homologyπ _ ≫ (groupCohomologyOddIso g hg A i hi).inv

lemma πOdd_eq_zero_iff
    {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) (hi : Odd i)
    (x : LinearMap.ker A.norm.hom.hom) :
    πOdd g hg A i hi x = 0 ↔ x.1 ∈ LinearMap.range (applyAsHom A g - 𝟙 A).hom.hom := by
  simp [πOdd, map_eq_zero_iff _ ((ModuleCat.mono_iff_injective _).1 inferInstance),
    moduleCatToCycles, -LinearMap.mem_range, LinearMap.range_codRestrict]

lemma πOdd_eq_iff {G : Type u} [CommGroup G] [Fintype G] [DecidableEq G] (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (A : Rep k G) (i : ℕ) (hi : Odd i)
    (x y : LinearMap.ker A.norm.hom.hom) :
    πOdd g hg A i hi x = πOdd g hg A i hi y ↔
      x.1 - y.1 ∈ LinearMap.range (applyAsHom A g - 𝟙 A).hom.hom := by
  rw [← sub_eq_zero, ← map_sub, πOdd_eq_zero_iff]; rfl

end groupCohomology
end Rep.finiteCyclicGroup
