/-
Copyright (c) 2026 Caleb Geiger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Caleb Geiger
-/
module

public import Mathlib.RingTheory.ZMod.UnitsCyclic

/-!
# Square-root counts in `ZMod`

This file counts the square roots of an odd integer modulo a power of two.

## Main definitions

* `ZMod.sqrtCard`: the number of square roots of an element of `ZMod n`.

## Main results

* `ZMod.sqrtCard_two_pow_unit`: an odd integer has four square roots modulo `2 ^ n`, for
  `n ≥ 3`, exactly when it is congruent to `1` modulo `8`.

The proof identifies the subgroup of units congruent to `1` modulo `4` with the cyclic
subgroup generated by `5`. It then computes the kernel and range of the squaring
endomorphism on `(ZMod (2 ^ n))ˣ` and transfers the resulting fiber count to `ZMod`.
-/

public section

open Finset

namespace ZMod

/-- The number of elements `x : ZMod n` satisfying `x ^ 2 = c`. -/
def sqrtCard (n : ℕ) [NeZero n] (c : ZMod n) : ℕ :=
  (univ.filter fun x : ZMod n => x ^ 2 = c).card

private lemma ker_unitsMap_four_eq_zpowers_five (n : ℕ) (hn : 3 ≤ n) :
    let h4 : 4 ∣ 2 ^ n := by
      change 2 ^ 2 ∣ 2 ^ n
      exact pow_dvd_pow 2 (by omega)
    let five : (ZMod (2 ^ n))ˣ :=
      ZMod.unitOfCoprime 5 ((by decide : Nat.Coprime 5 2).pow_right n)
    (ZMod.unitsMap h4).ker = Subgroup.zpowers five := by
  dsimp only
  let h4 : 4 ∣ 2 ^ n := by
    change 2 ^ 2 ∣ 2 ^ n
    exact pow_dvd_pow 2 (by omega)
  let five : (ZMod (2 ^ n))ˣ :=
    ZMod.unitOfCoprime 5 ((by decide : Nat.Coprime 5 2).pow_right n)
  let q := ZMod.unitsMap h4
  have hfive_mem : five ∈ q.ker := by
    rw [MonoidHom.mem_ker]
    apply Units.ext
    rw [ZMod.unitsMap_val]
    rw [show (five : ZMod (2 ^ n)) = 5 by simp [five]]
    rw [ZMod.cast_eq_val]
    rw [ZMod.val_ofNat_of_lt]
    · decide
    · calc
        5 < 2 ^ 3 := by decide
        _ ≤ 2 ^ n := Nat.pow_le_pow_right (by omega) hn
  have hle : Subgroup.zpowers five ≤ q.ker :=
    Subgroup.zpowers_le.2 hfive_mem
  symm
  apply Subgroup.eq_of_le_of_card_ge hle
  have hq_surj : Function.Surjective q := ZMod.unitsMap_surjective h4
  have hrange : q.range = ⊤ := MonoidHom.range_eq_top.2 hq_surj
  have hindex : q.ker.index = 2 := by
    rw [Subgroup.index_ker, hrange, Subgroup.card_top]
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  have hcardG : Nat.card (ZMod (2 ^ n))ˣ = 2 ^ (n - 1) := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
      Nat.totient_prime_pow Nat.prime_two (by omega)]
    simp
  have hcardker_mul : Nat.card q.ker * 2 = 2 ^ (n - 1) := by
    calc
      Nat.card q.ker * 2 = Nat.card q.ker * q.ker.index :=
        congrArg (Nat.card q.ker * ·) hindex.symm
      _ = Nat.card (ZMod (2 ^ n))ˣ := q.ker.card_mul_index
      _ = 2 ^ (n - 1) := hcardG
  have hcardker : Nat.card q.ker = 2 ^ (n - 2) := by
    apply Nat.eq_of_mul_eq_mul_right (by omega : 0 < 2)
    rw [hcardker_mul]
    rw [show n - 1 = (n - 2) + 1 by omega, pow_succ]
  rw [hcardker, Nat.card_zpowers]
  have horderfive : orderOf five = 2 ^ (n - 2) := by
    rw [← orderOf_units]
    change orderOf (5 : ZMod (2 ^ n)) = 2 ^ (n - 2)
    rw [show n = (n - 2) + 2 by omega]
    exact ZMod.orderOf_five (n - 2)
  rw [horderfive]

private lemma card_sq_ker_units_two_pow (n : ℕ) (hn : 3 ≤ n) :
    Nat.card (powMonoidHom 2 : (ZMod (2 ^ n))ˣ →* (ZMod (2 ^ n))ˣ).ker = 4 := by
  let h4 : 4 ∣ 2 ^ n := by
    change 2 ^ 2 ∣ 2 ^ n
    exact pow_dvd_pow 2 (by omega)
  let q := ZMod.unitsMap h4
  let five : (ZMod (2 ^ n))ˣ :=
    ZMod.unitOfCoprime 5 ((by decide : Nat.Coprime 5 2).pow_right n)
  let H := q.ker
  have hH : H = Subgroup.zpowers five :=
    ker_unitsMap_four_eq_zpowers_five n hn
  letI : IsCyclic H :=
    (Subgroup.isCyclic_iff_exists_zpowers_eq_top H).2 ⟨five, hH.symm⟩
  have hcardH : Nat.card H = 2 ^ (n - 2) := by
    rw [hH, Nat.card_zpowers]
    rw [← orderOf_units]
    change orderOf (5 : ZMod (2 ^ n)) = 2 ^ (n - 2)
    rw [show n = (n - 2) + 2 by omega]
    exact ZMod.orderOf_five (n - 2)
  have hcardHker : Nat.card (powMonoidHom 2 : H →* H).ker = 2 := by
    rw [IsCyclic.card_powMonoidHom_ker H 2, hcardH]
    rw [Nat.gcd_eq_right_iff_dvd]
    exact ⟨2 ^ (n - 3), by
      rw [show n - 2 = (n - 3) + 1 by omega, pow_succ]
      omega⟩
  let lift : (ZMod 4)ˣ → (ZMod (2 ^ n))ˣ := fun z => if z = 1 then 1 else -1
  have hlift_sq (z : (ZMod 4)ˣ) : lift z ^ 2 = 1 := by
    by_cases hz : z = 1 <;> simp [lift, hz]
  have hq_neg_one : q (-1) = -1 := by
    apply Units.ext
    rw [ZMod.unitsMap_val]
    change ((-1 : ZMod (2 ^ n)).cast : ZMod 4) = -1
    rw [ZMod.cast_neg h4, ZMod.cast_one h4]
  have htarget_sq (z : (ZMod 4)ˣ) : z ^ 2 = 1 := by
    fin_cases z <;> decide
  have hq_lift (z : (ZMod 4)ˣ) : q (lift z) = z := by
    rcases (show z = 1 ∨ z = -1 by fin_cases z <;> decide) with rfl | rfl
    · simp [lift, q]
    · have hneg : (-1 : (ZMod 4)ˣ) ≠ 1 := by decide
      simp [lift, hneg, hq_neg_one]
  let e :
      (powMonoidHom 2 : (ZMod (2 ^ n))ˣ →* (ZMod (2 ^ n))ˣ).ker ≃
        (ZMod 4)ˣ × (powMonoidHom 2 : H →* H).ker := {
    toFun g :=
      let z := q g.1
      let h : H := ⟨lift z * g.1, by
        rw [MonoidHom.mem_ker]
        simp only [map_mul, hq_lift]
        simpa [pow_two] using htarget_sq z⟩
      ⟨z, ⟨h, by
        rw [MonoidHom.mem_ker]
        apply Subtype.ext
        change (lift z * g.1) ^ 2 = 1
        rw [mul_pow, hlift_sq]
        have hg_sq : g.1 ^ 2 = 1 := by
          simpa using MonoidHom.mem_ker.mp g.2
        rw [hg_sq, one_mul]⟩⟩
    invFun zh := ⟨lift zh.1 * zh.2.1, by
      rw [MonoidHom.mem_ker]
      change (lift zh.1 * zh.2.1) ^ 2 = 1
      rw [mul_pow, hlift_sq]
      have hh_sq : zh.2.1 ^ 2 = 1 := by
        simpa using MonoidHom.mem_ker.mp zh.2.2
      have hh_sqG : (zh.2.1.1 : (ZMod (2 ^ n))ˣ) ^ 2 = 1 := by
        simpa using congrArg (fun x : H => (x : (ZMod (2 ^ n))ˣ)) hh_sq
      rw [one_mul]
      exact hh_sqG⟩
    left_inv g := by
      apply Subtype.ext
      change lift (q g.1) * (lift (q g.1) * g.1) = g.1
      rw [← mul_assoc, ← pow_two, hlift_sq, one_mul]
    right_inv zh := by
      apply Prod.ext
      · dsimp
        rw [map_mul, hq_lift]
        have hhq : q zh.2.1 = 1 := MonoidHom.mem_ker.mp zh.2.1.property
        rw [hhq, mul_one]
      · apply Subtype.ext
        apply Subtype.ext
        dsimp
        rw [map_mul, hq_lift]
        have hhq : q zh.2.1 = 1 := MonoidHom.mem_ker.mp zh.2.1.property
        rw [hhq, mul_one]
        rw [← mul_assoc, ← pow_two, hlift_sq, one_mul]
  }
  rw [Nat.card_congr e, Nat.card_prod, hcardHker]
  have hcard4 : Nat.card (ZMod 4)ˣ = 2 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  rw [hcard4]

private lemma sq_range_eq_ker_unitsMap_eight (n : ℕ) (hn : 3 ≤ n) :
    let h8 : 8 ∣ 2 ^ n := by
      change 2 ^ 3 ∣ 2 ^ n
      exact pow_dvd_pow 2 hn
    (powMonoidHom 2 : (ZMod (2 ^ n))ˣ →* (ZMod (2 ^ n))ˣ).range =
      (ZMod.unitsMap h8).ker := by
  dsimp only
  let h8 : 8 ∣ 2 ^ n := by
    change 2 ^ 3 ∣ 2 ^ n
    exact pow_dvd_pow 2 hn
  let sq := (powMonoidHom 2 : (ZMod (2 ^ n))ˣ →* (ZMod (2 ^ n))ˣ)
  let q8 := ZMod.unitsMap h8
  have htarget_sq (z : (ZMod 8)ˣ) : z ^ 2 = 1 := by
    fin_cases z <;> decide
  have hle : sq.range ≤ q8.ker := by
    rintro _ ⟨g, rfl⟩
    rw [MonoidHom.mem_ker]
    simp only [sq, powMonoidHom_apply, map_pow]
    exact htarget_sq (q8 g)
  apply Subgroup.eq_of_le_of_card_ge hle
  have hcardG : Nat.card (ZMod (2 ^ n))ˣ = 2 ^ (n - 1) := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
      Nat.totient_prime_pow Nat.prime_two (by omega)]
    simp
  have hsquare_index : sq.ker.index = Nat.card sq.range := Subgroup.index_ker sq
  have hcard_sq_ker : Nat.card sq.ker = 4 := card_sq_ker_units_two_pow n hn
  have hcard_range_mul : 4 * Nat.card sq.range = 2 ^ (n - 1) := by
    calc
      4 * Nat.card sq.range = Nat.card sq.ker * sq.ker.index := by
        rw [hcard_sq_ker, hsquare_index]
      _ = Nat.card (ZMod (2 ^ n))ˣ := sq.ker.card_mul_index
      _ = 2 ^ (n - 1) := hcardG
  have hcard_range : Nat.card sq.range = 2 ^ (n - 3) := by
    apply Nat.eq_of_mul_eq_mul_left (by omega : 0 < 4)
    rw [hcard_range_mul]
    rw [show n - 1 = (n - 3) + 2 by omega, pow_add]
    ring
  have hq8_surj : Function.Surjective q8 := ZMod.unitsMap_surjective h8
  have hq8_range : q8.range = ⊤ := MonoidHom.range_eq_top.2 hq8_surj
  have hq8_index : q8.ker.index = 4 := by
    rw [Subgroup.index_ker, hq8_range, Subgroup.card_top,
      Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  have hcard_q8_mul : Nat.card q8.ker * 4 = 2 ^ (n - 1) := by
    calc
      Nat.card q8.ker * 4 = Nat.card q8.ker * q8.ker.index :=
        congrArg (Nat.card q8.ker * ·) hq8_index.symm
      _ = Nat.card (ZMod (2 ^ n))ˣ := q8.ker.card_mul_index
      _ = 2 ^ (n - 1) := hcardG
  have hcard_q8 : Nat.card q8.ker = 2 ^ (n - 3) := by
    apply Nat.eq_of_mul_eq_mul_right (by omega : 0 < 4)
    rw [hcard_q8_mul]
    rw [show n - 1 = (n - 3) + 2 by omega, pow_add]
    norm_num
  rw [hcard_range, hcard_q8]

private lemma isUnit_intCast_two_pow (n : ℕ) (u : ℤ) (hu : ¬ (2 : ℤ) ∣ u) :
    IsUnit (u : ZMod (2 ^ n)) := by
  have hnot : ¬ 2 ∣ u.natAbs := by
    intro h
    exact hu (Int.natCast_dvd.mpr h)
  have hcop : Nat.Coprime u.natAbs (2 ^ n) :=
    (Nat.prime_two.coprime_iff_not_dvd.mpr hnot).symm.pow_right n
  have habs : IsUnit (u.natAbs : ZMod (2 ^ n)) :=
    (ZMod.isUnit_iff_coprime u.natAbs (2 ^ n)).2 hcop
  rcases le_total 0 u with hu0 | hu0
  · have heq : (u.natAbs : ℤ) = u := by
      rw [Int.natCast_natAbs, abs_of_nonneg hu0]
    have hcast := congrArg (fun z : ℤ => (z : ZMod (2 ^ n))) heq
    have hcast' : (u.natAbs : ZMod (2 ^ n)) = (u : ZMod (2 ^ n)) := by
      simpa only [Int.cast_natCast] using hcast
    change IsUnit (u : ZMod (2 ^ n))
    rw [← hcast']
    exact habs
  · have hneg := habs.neg
    have heq : -(u.natAbs : ℤ) = u := by
      rw [Int.natCast_natAbs, abs_of_nonpos hu0]
      simp
    have hcast := congrArg (fun z : ℤ => (z : ZMod (2 ^ n))) heq
    have hcast' : -(u.natAbs : ZMod (2 ^ n)) = (u : ZMod (2 ^ n)) := by
      simpa only [Int.cast_neg, Int.cast_natCast] using hcast
    change IsUnit (u : ZMod (2 ^ n))
    rw [← hcast']
    exact hneg

private lemma sqrtCard_eq_card_units_sq_fiber (m : ℕ) [NeZero m]
    (c : ZMod m) (hc : IsUnit c) :
    sqrtCard m c =
      (univ.filter fun x : (ZMod m)ˣ => x ^ 2 = hc.unit).card := by
  classical
  let T := univ.filter fun x : (ZMod m)ˣ => x ^ 2 = hc.unit
  let f : (ZMod m)ˣ → ZMod m := fun x => x
  have heq : univ.filter (fun x : ZMod m => x ^ 2 = c) = T.image f := by
    ext x
    simp only [mem_filter, mem_univ, true_and, mem_image]
    constructor
    · intro hx
      have hxpow : IsUnit (x ^ 2) := by rwa [hx]
      have hxunit : IsUnit x := (isUnit_pow_iff (by decide : 2 ≠ 0)).mp hxpow
      refine ⟨hxunit.unit, ?_, IsUnit.unit_spec hxunit⟩
      rw [mem_filter]
      refine ⟨mem_univ _, ?_⟩
      apply Units.ext
      change (x ^ 2 : ZMod m) = c
      exact hx
    · rintro ⟨y, hy, rfl⟩
      change ((y : ZMod m) ^ 2 = c)
      have hy' := (mem_filter.mp hy).2
      have := congrArg (fun z : (ZMod m)ˣ => (z : ZMod m)) hy'
      simpa only [Units.val_pow_eq_pow_val, IsUnit.unit_spec] using this
  unfold sqrtCard
  rw [heq, card_image_of_injective _ Units.val_injective]

private lemma sqrtCard_unit_eq_ker_or_zero (m : ℕ) [NeZero m]
    (c : ZMod m) (hc : IsUnit c) :
    sqrtCard m c =
      if hc.unit ∈ (powMonoidHom 2 : (ZMod m)ˣ →* (ZMod m)ˣ).range then
        Nat.card (powMonoidHom 2 : (ZMod m)ˣ →* (ZMod m)ˣ).ker
      else 0 := by
  rw [sqrtCard_eq_card_units_sq_fiber m c hc]
  let sq := (powMonoidHom 2 : (ZMod m)ˣ →* (ZMod m)ˣ)
  by_cases hmem : hc.unit ∈ sq.range
  · rw [if_pos hmem]
    have hone : (1 : (ZMod m)ˣ) ∈ Set.range sq := ⟨1, by simp [sq]⟩
    have hfiber := MonoidHom.card_fiber_eq_of_mem_range sq
      (show hc.unit ∈ Set.range sq from hmem) hone
    change #{x | sq x = hc.unit} = Nat.card sq.ker
    rw [hfiber]
    rw [Nat.card_eq_fintype_card]
    symm
    calc
      Fintype.card sq.ker = #{g | g ∈ sq.ker} :=
        Fintype.card_subtype fun g => g ∈ sq.ker
      _ = #{g | sq g = 1} := by
        congr 1
        ext g
        simp [MonoidHom.mem_ker]
  · rw [if_neg hmem, card_eq_zero, filter_eq_empty_iff]
    intro x _ hx
    exact hmem ⟨x, by simpa [sq] using hx⟩

/-- For `n ≥ 3` and odd `u`, the equation `x² = u` in `ZMod (2 ^ n)` has four
solutions exactly when `u ≡ 1 (mod 8)`, and has no solutions otherwise. -/
theorem sqrtCard_two_pow_unit (n : ℕ) (hn : 3 ≤ n) (u : ℤ)
    (hu : ¬ (2 : ℤ) ∣ u) :
    sqrtCard (2 ^ n) (u : ZMod (2 ^ n)) = if u % 8 = 1 then 4 else 0 := by
  have hunit : IsUnit (u : ZMod (2 ^ n)) := isUnit_intCast_two_pow n u hu
  rw [sqrtCard_unit_eq_ker_or_zero (2 ^ n) (u : ZMod (2 ^ n)) hunit]
  let h8 : 8 ∣ 2 ^ n := by
    change 2 ^ 3 ∣ 2 ^ n
    exact pow_dvd_pow 2 hn
  let sq := (powMonoidHom 2 : (ZMod (2 ^ n))ˣ →* (ZMod (2 ^ n))ˣ)
  let q8 := ZMod.unitsMap h8
  have hrange : sq.range = q8.ker := sq_range_eq_ker_unitsMap_eight n hn
  have hmem_iff : hunit.unit ∈ sq.range ↔ u % 8 = 1 := by
    rw [hrange, MonoidHom.mem_ker]
    rw [Units.ext_iff, ZMod.unitsMap_val]
    rw [show (hunit.unit : ZMod (2 ^ n)) = (u : ZMod (2 ^ n)) from hunit.unit_spec]
    rw [ZMod.cast_intCast h8]
    exact (ZMod.intCast_eq_intCast_iff' u 1 8).trans (by norm_num)
  by_cases h : u % 8 = 1
  · rw [if_pos h, if_pos (hmem_iff.mpr h), card_sq_ker_units_two_pow n hn]
  · rw [if_neg h, if_neg (fun hm => h (hmem_iff.mp hm))]

end ZMod
