/-
Copyright (c) 2024 Yury Kudryashov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yury Kudryashov
-/
module

public import Mathlib.Topology.Defs.Sequences
public import Mathlib.Topology.ContinuousOn
public import Mathlib.Topology.ContinuousMap.Basic

/-!
# Topology generated by its restrictions to subsets

We say that restrictions of the topology on `X` to sets from a family `S`
generates the original topology,
if either of the following equivalent conditions hold:

- a set which is relatively open in each `s ∈ S` is open;
- a set which is relatively closed in each `s ∈ S` is closed;
- for any topological space `Y`, a function `f : X → Y` is continuous
  provided that it is continuous on each `s ∈ S`.

We use the first condition as the definition
(see `IsCoherentWith` in `Mathlib/Topology/Defs/Induced.lean`),
and provide the others as corollaries.

## Main results

- `IsCoherentWith.of_seq`: if `X` is a sequential space
  and `S` contains all sets of the form `insert x (Set.range u)`,
  where `u : ℕ → X` is a sequence that converges to `x`,
  then we have `IsCoherentWith S`;
-/

public section

open Filter Set Set.Notation

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {S : Set (Set X)} {t : Set X} {x : X}

namespace Topology.IsCoherentWith

protected theorem isOpen_iff (hS : IsCoherentWith S) :
    IsOpen t ↔ ∀ s ∈ S, IsOpen ((↑) ⁻¹' t : Set s) :=
  ⟨fun ht _ _ ↦ ht.preimage continuous_subtype_val, hS.1 t⟩

protected theorem isClosed_iff (hS : IsCoherentWith S) :
    IsClosed t ↔ ∀ s ∈ S, IsClosed ((↑) ⁻¹' t : Set s) := by
  simp only [← isOpen_compl_iff, hS.isOpen_iff, preimage_compl]

protected theorem continuous_iff {Y : Type*} [TopologicalSpace Y] {f : X → Y}
    (hS : IsCoherentWith S) :
    Continuous f ↔ ∀ s ∈ S, ContinuousOn f s :=
  ⟨fun h _ _ ↦ h.continuousOn, fun h ↦ continuous_def.2 fun _u hu ↦ hS.isOpen_iff.2 fun s hs ↦
    hu.preimage <| (h s hs).domRestrict⟩

theorem of_continuous_prop (h : ∀ f : X → Prop, (∀ s ∈ S, ContinuousOn f s) → Continuous f) :
    IsCoherentWith S where
  isOpen_of_forall_induced u hu := by
    simp only [continuousOn_iff_continuous_domRestrict, continuous_Prop] at *
    exact h _ hu

theorem of_isClosed (h : ∀ t : Set X, (∀ s ∈ S, IsClosed ((↑) ⁻¹' t : Set s)) → IsClosed t) :
    IsCoherentWith S :=
  ⟨fun _t ht ↦ isClosed_compl_iff.1 <| h _ fun s hs ↦ (ht s hs).isClosed_compl⟩

protected theorem enlarge {T} (hS : IsCoherentWith S) (hT : ∀ s ∈ S, ∃ t ∈ T, s ⊆ t) :
    IsCoherentWith T :=
  of_continuous_prop fun _f hf ↦ hS.continuous_iff.2 fun s hs ↦
    let ⟨t, htT, hst⟩ := hT s hs; (hf t htT).mono hst

protected theorem mono {T} (hS : IsCoherentWith S) (hT : S ⊆ T) : IsCoherentWith T :=
  hS.enlarge fun s hs ↦ ⟨s, hT hs, Subset.rfl⟩

/-- If `X` is a sequential space
and `S` contains each set of the form `insert x (Set.range u)`
where `u : ℕ → X` is a sequence and `x` is its limit,
then topology on `X` is generated by its restrictions to the sets of `S`. -/
lemma of_seq [SequentialSpace X]
    (h : ∀ ⦃u : ℕ → X⦄ ⦃x : X⦄, Tendsto u atTop (𝓝 x) → insert x (range u) ∈ S) :
    IsCoherentWith S := by
  refine of_isClosed fun t ht ↦ IsSeqClosed.isClosed fun u x hut hux ↦ ?_
  rcases isClosed_induced_iff.1 (ht _ (h hux)) with ⟨s, hsc, hst⟩
  rw [Subtype.preimage_val_eq_preimage_val_iff, Set.ext_iff] at hst
  suffices x ∈ s by specialize hst x; simp_all
  refine hsc.mem_of_tendsto hux <| Eventually.of_forall fun k ↦ ?_
  specialize hst (u k)
  simp_all

/-- If each point of the space has a neighborhood from the family `S`,
then the topology is generated by its restrictions to the sets of `S`. -/
lemma of_nhds (h : ∀ x, ∃ s ∈ S, s ∈ 𝓝 x) : IsCoherentWith S :=
  of_continuous_prop fun _f hf ↦ continuous_iff_continuousAt.2 fun x ↦
    let ⟨s, hsS, hsx⟩ := h x
    (hf s hsS).continuousAt hsx

/-- If a space `X` is coherent with an indexed family of subspaces `S` whose union is `X`, then the
 canonical inclusion from `Σ i, S i` to `X` is a quotient map. -/
lemma isQuotientMap_sigma_desc'
    {ι : Type*} {S : ι → Set X} (hX : IsCoherentWith (range S)) (hS : ⋃ i, S i = univ) :
    IsQuotientMap (ContinuousMap.sigma (fun _ ↦ ContinuousMap.subtypeVal) : C(Σ i, S i, X)) where
  surjective y := by
    rw [iUnion_eq_univ_iff] at hS
    obtain ⟨i, hx⟩ := hS y
    use Sigma.mk i ⟨y, hx⟩
    simp
  eq_coinduced := by
    ext t
    unfold instTopologicalSpaceSigma
    simp [hX.isOpen_iff (t := t), isOpen_coinduced, isOpen_iSup_iff, preimage_preimage]

/-- If a space `X` is coherent with a set of subspaces `S` whose union is `X`, then the
 canonical inclusion from `Σ i, S i` to `X` is a quotient map. -/
lemma isQuotientMap_sigma_desc (hX : IsCoherentWith S) (hS : ⋃₀ S = univ) :
    IsQuotientMap (ContinuousMap.sigma (fun _ ↦ ContinuousMap.subtypeVal) : C(Σ (s : S), s, X)) :=
  have h : S = range Subtype.val := by simp
  IsCoherentWith.isQuotientMap_sigma_desc' (S := ((↑) : S → Set X))
    (h ▸ hX) (sUnion_eq_iUnion ▸ hS)

variable {S : Set (Set X)} (hS : IsCoherentWith S) (surj : ⋃₀ S = Set.univ) (F : ∀ s ∈ S, C(s, Y))
  (hF : ∀ (s) (hs : s ∈ S) (t) (ht : t ∈ S) (x : X) (hxs : x ∈ s) (hxt : x ∈ t),
    F s hs ⟨x, hxs⟩ = F t ht ⟨x, hxt⟩)

/-- A family `F s` of continuous maps `C(s, Y)`, where (1) the domains `s` are taken from a set `S`
of sets in `X` which are jointly surjective and coherent with `X` and (2) the functions `F s` agree
pairwise on intersections, can be glued to construct a continuous map `C(X, Y)`. -/
noncomputable def liftCover : C(X, Y) where
  toFun := Set.liftCover ((↑) : S → Set X) (fun s ↦ F s s.2) (fun s t ↦ hF s s.2 t t.2)
    (by simp [sUnion_eq_iUnion, ← surj])
  continuous_toFun := by
    rw [hS.continuous_iff, Subtype.forall']
    intro s
    rw [continuousOn_iff_continuous_restrict, Set.liftCover_restrict]
    exact (F s s.2).continuous

variable {hS surj F hF}

@[simp]
theorem liftCover_coe {s : S} (x : (s : Set X)) : hS.liftCover surj F hF x = F s s.2 x := by
  simp [IsCoherentWith.liftCover]

@[simp]
theorem liftCover_of_mem_coe {s : Set X} (hs : s ∈ S) (x : s) :
    hS.liftCover surj F hF x = F s hs x :=
  hS.liftCover_coe (s := ⟨s, hs⟩) x

theorem liftCover_of_mem {s : Set X} (hs : s ∈ S) {x : X} (hx : x ∈ s) :
    hS.liftCover surj F hF x = F s hs ⟨x, hx⟩ :=
  hS.liftCover_of_mem_coe hs ⟨x, hx⟩

theorem preimage_liftCover (t : Set Y) :
    hS.liftCover surj F hF ⁻¹' t = ⋃ s : S, (↑) '' (F s s.2 ⁻¹' t) := by
  simp only [IsCoherentWith.liftCover, ContinuousMap.coe_mk]
  rw [Set.preimage_liftCover]

@[simp]
theorem liftCover_restrict (s : Set X) (hs : s ∈ S) :
    s.restrict (hS.liftCover surj F hF) = F s hs := by
  ext x; simp [hs]

variable (hS surj) in
/-- When `X` is coherent with a set of subspaces `S`, every continuous map out of `X` can be
written as a `liftCover`. -/
@[simps]
noncomputable def liftEquiv :
    { F : ∀ s ∈ S, C(s, Y) // ∀ s (hs : s ∈ S) t (ht : t ∈ S) x (hxs : x ∈ s) (hxt : x ∈ t),
       F s hs ⟨x, hxs⟩ = F t ht ⟨x, hxt⟩ } ≃ C(X, Y) where
  toFun F := hS.liftCover surj F F.2
  invFun f := ⟨fun s hs ↦ f.restrict s, fun s hs t ht x hxs hxt ↦ by simp⟩
  left_inv := by rintro ⟨F, hF⟩; ext s hs x; simp [hs]
  right_inv f := by
    ext x
    rw [sUnion_eq_univ_iff] at surj
    obtain ⟨s, hs, hxs⟩ := surj x
    simp [liftCover_of_mem hs hxs]

/-- A version of `liftEquiv_apply` that is more convenient when rewriting. -/
lemma liftEquiv_apply' : hS.liftCover surj F hF = hS.liftEquiv surj ⟨F, hF⟩ := by rfl

variable {ι} {S : ι → Set X} (hS : IsCoherentWith (range S)) (surj : ⋃ i, S i = Set.univ)
  (φ : (i : ι) → C(S i, Y))
  (hφ : ∀ i j x (hxi : x ∈ S i) (hxj : x ∈ S j), φ i ⟨x, hxi⟩ = φ j ⟨x, hxj⟩)

/-- A family `φ i` of continuous maps `(i : ι) → C(S i, Y)`, where (1) the domains `S i` are taken
from a family `S` of sets in `X` which are jointly surjective and coherent with `X` and (2) the
functions `φ` agree pairwise on intersections, can be glued to construct a continuous map
`C(X, Y)`. -/
noncomputable def liftCover' : C(X, Y) where
  toFun := Set.liftCover S (φ ·) hφ surj
  continuous_toFun := by
    rw [hS.continuous_iff, forall_mem_range]
    intro i
    rw [continuousOn_iff_continuous_restrict, Set.liftCover_restrict]
    exact (φ i).continuous

variable {hS surj φ hφ}
variable {i : ι}

@[simp]
theorem liftCover'_coe (x : S i) : hS.liftCover' surj φ hφ x = φ i x := by
  simp [IsCoherentWith.liftCover']

theorem liftCover'_of_mem {x : X} (hx : x ∈ S i) : hS.liftCover' surj φ hφ x = φ i ⟨x, hx⟩ :=
  hS.liftCover'_coe ⟨x, hx⟩

theorem preimage_liftCover' (t : Set Y) :
    hS.liftCover' surj φ hφ ⁻¹' t = ⋃ i, (↑) '' (φ i ⁻¹' t) := by
  simp only [IsCoherentWith.liftCover', ContinuousMap.coe_mk]
  rw [Set.preimage_liftCover]

@[simp]
theorem liftCover'_restrict : (S i).restrict (hS.liftCover' surj φ hφ) = φ i := by ext x; simp

variable (hS surj) in
/-- When `X` is coherent with a family of subspaces `S i`, every continuous map out of `X` can be
written as a `liftCover'`. -/
@[simps]
noncomputable def liftEquiv' :
    { φ : (i : ι) → C(S i, Y) // ∀ i j x (hxi : x ∈ S i) (hxj : x ∈ S j),
       φ i ⟨x, hxi⟩ = φ j ⟨x, hxj⟩ } ≃ C(X, Y) where
  toFun φ := hS.liftCover' surj φ φ.2
  invFun f := ⟨fun i ↦ f.restrict (S i), fun i j x hxi hxj ↦ by simp⟩
  left_inv := by rintro ⟨φ, hφ⟩; ext i x; simp
  right_inv f := by
    ext x
    rw [iUnion_eq_univ_iff] at surj
    obtain ⟨i, hxi⟩ := surj x
    simp [liftCover'_of_mem hxi]

/-- A version of `liftEquiv'_apply` that is more convenient when rewriting. -/
lemma liftEquiv'_apply' : hS.liftCover' surj φ hφ = hS.liftEquiv' surj ⟨φ, hφ⟩ := by rfl

end Topology.IsCoherentWith
