/-
Copyright (c) 2025 Nailin Guan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nailin Guan
-/
module

public import Mathlib.Algebra.Module.SpanRankOperations
public import Mathlib.RingTheory.DedekindDomain.Dvr
public import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
public import Mathlib.RingTheory.KrullDimension.Field
public import Mathlib.RingTheory.KrullDimension.PID

/-!
# Regular local rings

For a Noetherian local ring `R`, we define `IsRegularLocalRing` as
`(maximalIdeal R).spanFinrank = ringKrullDim R`. This definition is equivalent to
the dimension of the cotangent space over the residue field being equal to `ringKrullDim R`,
(see `IsRegularLocalRing.iff_finrank_cotangentSpace`).

# Main Definition and Results

* `IsRegularLocalRing` : A Noetherian local ring is regular if
  `(maximalIdeal R).spanFinrank = ringKrullDim R`,
  i.e. its maximal ideal can be generated by `dim R` elements.

* `IsRegularLocalRing.iff_finrank_cotangentSpace` : the equivalence of `IsRegularLocalRing` and
  `Module.finrank (ResidueField R) (CotangentSpace R) = ringKrullDim R`

-/

@[expose] public section

open IsLocalRing

/-- A Noetherian local ring is said to be regular if its maximal ideal
can be generated by `dim R` elements. -/
@[stacks 00KU]
class IsRegularLocalRing (R : Type*) [CommRing R] : Prop extends
    IsLocalRing R, IsNoetherianRing R where
  spanFinrank_maximalIdeal : (maximalIdeal R).spanFinrank = ringKrullDim R

variable (R : Type*) [CommRing R]

lemma isRegularLocalRing_iff [IsLocalRing R] [IsNoetherianRing R] :
    IsRegularLocalRing R ↔ (maximalIdeal R).spanFinrank = ringKrullDim R :=
  ⟨fun ⟨h⟩ ↦ h, fun h ↦ ⟨h⟩⟩

namespace IsRegularLocalRing

lemma of_spanFinrank_maximalIdeal_le [IsLocalRing R] [IsNoetherianRing R]
    (le : (maximalIdeal R).spanFinrank ≤ ringKrullDim R) : IsRegularLocalRing R :=
  (isRegularLocalRing_iff _).mpr (le_antisymm le (ringKrullDim_le_spanFinrank_maximalIdeal R))

variable {R} in
lemma of_ringEquiv [IsRegularLocalRing R] {R' : Type*} [CommRing R']
    (e : R ≃+* R') : IsRegularLocalRing R' := by
  have := e.isLocalRing
  have := isNoetherianRing_of_ringEquiv R e
  rwa [isRegularLocalRing_iff, ← ringKrullDim_eq_of_ringEquiv e, ← map_ringEquiv_maximalIdeal e,
    Ideal.spanFinrank_map_eq_of_ringEquiv, ← isRegularLocalRing_iff]

lemma iff_finrank_cotangentSpace [IsLocalRing R] [IsNoetherianRing R] :
    IsRegularLocalRing R ↔ Module.finrank (ResidueField R) (CotangentSpace R) = ringKrullDim R := by
  rw [isRegularLocalRing_iff, spanFinrank_maximalIdeal_eq_finrank_cotangentSpace]

instance [IsLocalRing R] [IsDomain R] [IsPrincipalIdealRing R] : IsRegularLocalRing R := by
  by_cases isf : IsField R
  · let := isf.toField
    simp [isRegularLocalRing_iff, maximalIdeal_eq_bot]
  · apply of_spanFinrank_maximalIdeal_le
    rcases IsPrincipalIdealRing.principal (maximalIdeal R) with ⟨x, hx⟩
    simpa only [(IsPrincipalIdealRing.ringKrullDim_eq_one R) isf,
      Nat.cast_le_one, ← Set.ncard_singleton x, hx] using
        Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_singleton x)

end IsRegularLocalRing

/-!

# Definition of regular rings

In this section, we define regular rings as noetherian rings whose localization at every prime are
regular local rings.
(Note that a regular local ring is a regular ring, but this is not immediate under this definition).

## TODO
Show that regular local rings are regular under this definition.
This follows from localizations of regular local rings being regular (@Thmoas-Guan).

-/

/-- A noetherian ring is regular if its localization at any prime `IsRegularLocalRing`. -/
class IsRegularRing (R : Type*) [CommRing R] : Prop extends IsNoetherianRing R where
  isRegularLocalRing_localization (p : Ideal R) [p.IsPrime] :
    IsRegularLocalRing (Localization.AtPrime p)

section IsRegularRing

variable {R} in
lemma isRegularRing_iff [IsNoetherianRing R] : IsRegularRing R ↔
    ∀ (p : Ideal R) (_ : p.IsPrime), IsRegularLocalRing (Localization.AtPrime p) :=
  ⟨fun ⟨h⟩ ↦ h, fun h ↦ ⟨h⟩⟩

variable {R} in
lemma isRegularRing_of_ringEquiv {R' : Type*} [CommRing R'] (e : R ≃+* R') [IsRegularRing R] :
    IsRegularRing R' := by
  have := isNoetherianRing_of_ringEquiv R e
  rw [isRegularRing_iff]
  intro p hp
  have := isRegularRing_iff.mp ‹_› (p.comap e) (Ideal.comap_isPrime e p)
  suffices (p.comap e).primeCompl.map e = p.primeCompl from
    IsRegularLocalRing.of_ringEquiv <| IsLocalization.ringEquivOfRingEquiv
      (Localization.AtPrime (p.comap e)) (Localization.AtPrime p) e this
  ext x
  have : (∃ y, e y ∉ p ∧ e y = x) ↔ x ∉ p := by
    refine ⟨fun ⟨y, hy, eq⟩ ↦ eq ▸ hy, fun h ↦ ⟨e.symm x, ?_⟩⟩
    simpa
  simpa

lemma IsRegularLocalRing.of_isRegularRing_of_isLocalRing [IsLocalRing R] [IsRegularRing R] :
    IsRegularLocalRing R := by
  have := isRegularRing_iff.mp ‹_› (maximalIdeal R) (Ideal.IsMaximal.isPrime' _)
  let e : R ≃ₐ[R] (Localization.AtPrime (maximalIdeal R)) :=
    IsLocalization.atUnits R (maximalIdeal R).primeCompl (fun x ↦ by simpa using fun a ↦ a)
  exact IsRegularLocalRing.of_ringEquiv e.toRingEquiv.symm

instance (priority := low) [IsDomain R] [IsDedekindDomain R] : IsRegularRing R := by
  rw [isRegularRing_iff]
  intro p hp
  by_cases eqbot : p = ⊥
  · let : Field (Localization.AtPrime p) := IsField.toField <| by
      simp [isField_iff_maximalIdeal_eq, ← Localization.AtPrime.map_eq_maximalIdeal, eqbot]
    infer_instance
  · have := IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
      R eqbot (Localization.AtPrime p)
    infer_instance

end IsRegularRing
