/-
Copyright (c) 2026 Nailin Guan, Jingting Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nailin Guan, Jingting Wang
-/
module

public import Mathlib.Algebra.Category.ModuleCat.ExteriorPower
public import Mathlib.Algebra.Homology.HomologicalComplex
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Grading
public import Mathlib.LinearAlgebra.ExteriorPower.Basis

/-!

# Definition of Koszul cocomplex

Given a commutative ring `R`, an `R`-module `M` and an element `x : M`, the
*Koszul cocomplex* `K(x)` is the cochain complex of `R`-modules whose `n`-th term is the exterior
power `⋀[R]^n M` and whose differential `⋀[R]^n M → ⋀[R]^(n + 1) M` is `y ↦ y ∧ x`.

The Koszul complex of a sequence `f₁, …, fᵣ` of elements of `R` is the special case
`M = Rʳ`, `x = (f₁, …, fᵣ)`.

## Main definitions

* `koszulCocomplex.d x n`: the induced linear map `⋀[R]^n M →ₗ[R] ⋀[R]^(n + 1) M`, the Koszul
  differential.
* `koszulCocomplex φ`: the Koszul complex of `φ`, as a `ChainComplex (ModuleCat R) ℕ`.
* `koszulCocomplex.ofList l`: the Koszul complex of a list `l` of elements of `R`.
* `koszulCocomplex.map`: the chain map `koszulCocomplex φ ⟶ koszulCocomplex φ'` induced by a
  linear map `f : M →ₗ[R] N` with `φ' ∘ₗ f = φ`, and `koszulCocomplex.isoOfEquiv`, the
  isomorphism induced by a linear equivalence.

## Main results

* `koszulCocomplex.map_comp`: `koszulCocomplex.map` is compatible with composition.
* `koszulCocomplex.isZero_X_of_card_generators_le`: if `M` is generated by `k` elements then
  `koszulCocomplex φ` vanishes in degrees `> k`; in particular
  (`koszulCocomplex.isZero_X_ofList_of_length_le`) the Koszul complex of a list of length `r`
  vanishes in degrees `> r`.

-/

@[expose] public section

universe u v w w'

open CategoryTheory Category MonoidalCategory Limits Module

section GradedAlgebra

variable {ι R A : Type*} [DecidableEq ι] [AddMonoid ι]
    [CommSemiring R] [Semiring A] [Algebra R A] (𝒜 : ι → Submodule R A) [GradedAlgebra 𝒜]
    {i j k : ι}

/-- The linear graded multiplication for general index. -/
def GradedAlgebra.linearGMul (h : k = i + j) : 𝒜 i →ₗ[R] (𝒜 j →ₗ[R] 𝒜 k) :=
  h ▸ DirectSum.gMulLHom (R := R) (A := fun n ↦ 𝒜 n)

@[simp]
lemma GradedAlgebra.linearGMul_eq_mul (h : k = i + j) (x : 𝒜 i) (y : 𝒜 j) :
    (GradedAlgebra.linearGMul 𝒜 h) x y = x.1 * y.1 := by
  subst h
  rfl

end GradedAlgebra

section

variable (R : Type u) [CommRing R] (M : Type v) [AddCommGroup M] [Module R M]

/-- The differential of Koszul cocoplex defined as wedging with `x` on the right. -/
noncomputable abbrev koszulCocomplex.d (x : M) (n : ℕ) :
    ⋀[R]^n M →ₗ[R] ⋀[R]^(n + 1) M :=
  GradedAlgebra.linearGMul (fun i : ℕ ↦ ⋀[R]^i M) (add_comm n 1)
    ((exteriorPower.oneEquiv R M).symm x)

lemma koszulCocomplex.d_apply_ιMulti (x : M) (i : ℕ) (m : Fin i → M) :
    koszulCocomplex.d R M x i (exteriorPower.ιMulti R i m) =
      exteriorPower.ιMulti R (i + 1) (Matrix.vecCons x m) := by
  apply Subtype.ext
  simp [koszulCocomplex.d, exteriorPower.oneEquiv_symm_apply,
    GradedAlgebra.linearGMul_eq_mul, exteriorPower.ιMulti_apply_coe,
    ExteriorAlgebra.ιMulti_succ_apply]

variable {M} in
/-- The Koszul cocomplex with objects exterior powers and differential `koszulCocomplex.d`. -/
noncomputable def koszulCocomplex (x : M) : CochainComplex (ModuleCat.{max u v} R) ℕ :=
  CochainComplex.of (fun n ↦ ModuleCat.of R (⋀[R]^n M))
    (fun n ↦ ModuleCat.ofHom (koszulCocomplex.d R M x n))
    (fun n ↦ by
      simp only [← ModuleCat.ofHom_comp]
      congr
      refine LinearMap.ext fun x ↦ Subtype.ext ?_
      simp [exteriorPower.oneEquiv_symm_apply, LinearMap.coe_comp, Function.comp_apply,
        GradedAlgebra.linearGMul_eq_mul, exteriorPower.ιMulti_apply_coe,
        ExteriorAlgebra.ιMulti_succ_apply, ExteriorAlgebra.ιMulti_zero_apply, mul_one, ← mul_assoc,
        CliffordAlgebra.ι_sq_scalar, zero_apply, map_zero, zero_mul])

namespace koszulCocomplex

theorem d_eq_aux (x : M) (i : ℕ) :
    (koszulCocomplex R x).d i (i + 1) = ModuleCat.ofHom (koszulCocomplex.d R M x i) := by
  simp [koszulCocomplex]

variable {R} in
/-- The abbreviation for the Koszul cocomplex generated by a list of elements in the ring. -/
noncomputable abbrev ofList (l : List R) :=
  koszulCocomplex R l.get

instance free [Module.Free R M] (x : M) (i : ℕ) : Module.Free R ((koszulCocomplex R x).X i) :=
  inferInstanceAs <| Module.Free R (⋀[R]^i M)

variable {M} {N : Type v} [AddCommGroup N] [Module R N]

section functoriality

set_option backward.isDefEq.respectTransparency false in
/-- The map between two Koszul complex when give a linear map between module that maps
the two defining elements. -/
noncomputable def map (f : M →ₗ[R] N) {x : M} {y : N} (h : f x = y) :
    koszulCocomplex R x ⟶ koszulCocomplex R y :=
  CochainComplex.ofHom
    (fun i ↦ (ModuleCat.exteriorPower.functor R i).map (ModuleCat.ofHom f))
    (fun i ↦ ModuleCat.hom_ext <| LinearMap.ext fun z ↦ Subtype.ext
      (by simp [koszulCocomplex, ModuleCat.exteriorPower.map,
        koszulCocomplex.d, exteriorPower.oneEquiv_symm_apply, h]))

lemma map_hom (f : M →ₗ[R] N) (x : M) (y : N) (h : f x = y) (i : ℕ) :
    (map R f h).f i = (ModuleCat.exteriorPower.functor R i).map (ModuleCat.ofHom f) := rfl

lemma map_id_refl (x : M) : koszulCocomplex.map R (M := M) .id (Eq.refl x) = 𝟙 _ := by
  ext i x
  simp only [map_hom, ModuleCat.ofHom_id, ModuleCat.exteriorPower.functor_map,
    ModuleCat.exteriorPower.map, ModuleCat.hom_id, exteriorPower.map_id, HomologicalComplex.id_f,
    LinearMap.id_coe, id_eq]
  rfl

lemma map_id (x y : M) (h : x = y) : koszulCocomplex.map R (M := M) .id h =
  eqToHom (congrArg _ h) := by
  subst h
  exact map_id_refl R x

set_option backward.isDefEq.respectTransparency false in
lemma map_comp {P : Type v} [AddCommGroup P] [Module R P]
    (f : M →ₗ[R] N) (g : N →ₗ[R] P) {x : M} {y : N} {z : P} (hxy : f x = y) (hyz : g y = z) :
    koszulCocomplex.map R f hxy ≫ koszulCocomplex.map R g hyz =
    koszulCocomplex.map R (g ∘ₗ f) (hxy ▸ hyz : g (f x) = z) := by
  refine HomologicalComplex.hom_ext _ _ fun i ↦ ?_
  simp only [HomologicalComplex.comp_f, map_hom, ModuleCat.ofHom_comp, Functor.map_comp]

/-- The map between two Koszul complex when give an linear equiv between module that maps
the two defining elements. -/
noncomputable def isoOfEquiv (f : M ≃ₗ[R] N) {x : M} {y : N} (h : f x = y) :
    koszulCocomplex R x ≅ koszulCocomplex R y where
  hom := koszulCocomplex.map R f h
  inv := koszulCocomplex.map R f.symm (f.injective (by simpa using h.symm))
  hom_inv_id := by simp [map_comp, map_id_refl]
  inv_hom_id := by simp [map_comp, map_id_refl]

end functoriality

lemma isZero_X_of_card_generators_le (x : M) {ι : Type*} [Finite ι] [LinearOrder ι] (g : ι → M)
    (hg : Submodule.span R (Set.range g) = ⊤) (i : ℕ) (hi : Nat.card ι < i) :
    IsZero ((koszulCocomplex R x).X i) :=
  ModuleCat.isZero_of_iff_subsingleton.mpr
    (exteriorPower.subsingleton_of_span_eq_top_of_card_lt g hg i hi)

lemma isZero_X_ofList_of_length_le (l : List R) (i : ℕ) (hi : l.length < i) :
    IsZero ((ofList l).X i) :=
  isZero_X_of_card_generators_le R l.get
  (Pi.basisFun R (Fin l.length)) (Pi.basisFun R (Fin l.length)).span_eq i
  (by simpa [Nat.card_eq_fintype_card] using hi)

end koszulCocomplex
