/-
Copyright (c) 2026 Nailin Guan, Jingting Wang, Yi Yuan, Yongle Hu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nailin Guan, Jingting Wang, Yi Yuan, Yongle Hu
-/
module

public import Mathlib.Algebra.Category.ModuleCat.ExteriorPower
public import Mathlib.Algebra.Homology.HomologicalComplex
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.Alternating.Uncurry.Fin

/-!
# The Koszul complex

Given a commutative ring `R`, an `R`-module `M` and a linear map `φ : M →ₗ[R] R`, the
*Koszul complex* `K(φ)` is the chain complex of `R`-modules whose `n`-th term is the exterior
power `⋀[R]^n M` and whose differential `⋀[R]^(n + 1) M → ⋀[R]^n M` is

`x₀ ∧ ⋯ ∧ xₙ ↦ ∑ i, (-1) ^ i • φ (xᵢ) • x₀ ∧ ⋯ ∧ x̂ᵢ ∧ ⋯ ∧ xₙ`.

The Koszul complex of a sequence `f₁, …, fᵣ` of elements of `R` is the special case
`M = Rʳ`, `φ = (a₁, …, aᵣ) ↦ ∑ aᵢ fᵢ`.

## Main definitions

* `koszulComplex.dAlternating φ n`: the alternating map `M [⋀^Fin (n + 1)]→ₗ[R] ⋀[R]^n M`
  displayed above, defined as the alternatisation of `x ↦ φ x • ιMulti`.
* `koszulComplex.d φ n`: the induced linear map `⋀[R]^(n + 1) M →ₗ[R] ⋀[R]^n M`, the Koszul
  differential.
* `koszulComplex φ`: the Koszul complex of `φ`, as a `ChainComplex (ModuleCat R) ℕ`.
* `koszulComplex.ofList l`: the Koszul complex of a list `l` of elements of `R`.
* `koszulComplex.map`: the chain map `koszulComplex φ ⟶ koszulComplex φ'` induced by a
  linear map `f : M →ₗ[R] N` with `φ' ∘ₗ f = φ`, and `koszulComplex.isoOfEquiv`, the
  isomorphism induced by a linear equivalence.

## Main results

* `koszulComplex.d_comp_eq_zero`: the Koszul differential squares to zero.
* `koszulComplex.map_comp`: `koszulComplex.map` is compatible with composition.
* `koszulComplex.isZero_X_of_card_generators_lt`: if `M` is generated by `k` elements then
  `koszulComplex φ` vanishes in degrees `> k`; in particular
  (`koszulComplex.isZero_X_ofList_of_length_lt`) the Koszul complex of a list of length `r`
  vanishes in degrees `> r`.

## Implementation notes

* The Stacks project defines the Koszul complex as a commutative differential graded algebra,
  the exterior algebra `⋀ M` with `d` the unique derivation extending `φ`; here we only record
  the underlying chain complex.

## References

* [The Stacks project, Section 15.29 *The Koszul complex*](https://stacks.math.columbia.edu/tag/0621)
-/

@[expose] public section

universe u v

open CategoryTheory Category Limits Module ExteriorAlgebra

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M] (φ : M →ₗ[R] R)

/-- The alternating map for the Koszul differential. -/
noncomputable def koszulComplex.dAlternating (n : ℕ) :
    M [⋀^Fin (n + 1)]→ₗ[R] ⋀[R]^n M :=
  AlternatingMap.alternatizeUncurryFin (φ.smulRight (exteriorPower.ιMulti R n))

lemma koszulComplex.dAlternating_apply (n : ℕ) (x : Fin (n + 1) → M) :
    koszulComplex.dAlternating φ n x =
      ∑ i : Fin (n + 1),
        ((-1 : R) ^ (i : ℕ) * φ (x i)) • exteriorPower.ιMulti R n (i.removeNth x) := by
  rw [koszulComplex.dAlternating, AlternatingMap.alternatizeUncurryFin_apply]
  refine Finset.sum_congr rfl ?_
  intro i _
  simp [← Int.cast_smul_eq_zsmul R, smul_smul]

/-- The differential for Koszul complex. -/
noncomputable def koszulComplex.d (n : ℕ) : ⋀[R]^(n + 1) M →ₗ[R] ⋀[R]^n M :=
  exteriorPower.alternatingMapLinearEquiv (koszulComplex.dAlternating φ n)

lemma koszulComplex.d_comp_eq_zero (n : ℕ) :
    koszulComplex.d φ n ∘ₗ koszulComplex.d φ (n + 1) = 0 := by
  let β : M →ₗ[R] M →ₗ[R] M [⋀^Fin n]→ₗ[R] ⋀[R]^n M :=
    φ.smulRight (φ.smulRight (exteriorPower.ιMulti R n))
  have hβ (x y : M) : β x y = β y x := by
    ext v
    simp [β, smul_smul, mul_comm]
  have : (koszulComplex.d φ n).compAlternatingMap (koszulComplex.dAlternating φ (n + 1)) = 0 := by
    rw [← AlternatingMap.alternatizeUncurryFin_alternatizeUncurryFinLM_comp_of_symmetric hβ]
    ext v
    simp [koszulComplex.d, koszulComplex.dAlternating, β,
      AlternatingMap.alternatizeUncurryFin_apply, Finset.smul_sum]
  simpa [koszulComplex.d, ← exteriorPower.alternatingMapLinearEquiv_comp]

/-- The Koszul complex, with objects exterior powers and differential `koszulComplex.d`. -/
noncomputable def koszulComplex : ChainComplex (ModuleCat R) ℕ :=
  ChainComplex.of (fun n ↦ ModuleCat.of R (⋀[R]^n M))
    (fun n ↦ ModuleCat.ofHom (koszulComplex.d φ n))
    (fun n ↦ by rw [← ModuleCat.ofHom_comp, koszulComplex.d_comp_eq_zero, ModuleCat.ofHom_zero])

lemma koszulComplex.X_eq_exteriorPower (i : ℕ) :
    (koszulComplex φ).X i = ModuleCat.of R (⋀[R]^i M) := rfl

lemma koszulComplex.d_eq_d (i : ℕ) :
    (koszulComplex φ).d (i + 1) i = ModuleCat.ofHom (koszulComplex.d φ i) := by
  simp [koszulComplex]

namespace koszulComplex

variable {N : Type v} [AddCommGroup N] [Module R N]

/-- The Koszul complex generated by a list of elements in the ring. -/
noncomputable def ofList (l : List R) := koszulComplex (Fintype.linearCombination R l.get)

section functoriality

lemma map_dAlternating_apply (f : M →ₗ[R] N) (φ' : N →ₗ[R] R) (h : φ' ∘ₗ f = φ)
    (i : ℕ) (v : Fin (i + 1) → M) :
    ((koszulComplex.dAlternating φ' i) (f ∘ v) : ⋀[R]^i N) =
      exteriorPower.map i f ((koszulComplex.dAlternating φ i) v) := by
  calc
    _ = ∑ x : Fin (i + 1), (-1) ^ (x : ℕ) • φ' (f (v x)) •
          exteriorPower.ιMulti R i (x.removeNth (f ∘ v)) := by
      simp [koszulComplex.dAlternating, AlternatingMap.alternatizeUncurryFin_apply]
    _ = ∑ x : Fin (i + 1), (-1) ^ (x : ℕ) • φ (v x) •
          exteriorPower.ιMulti R i (f ∘ x.removeNth v) := by
      refine Finset.sum_congr rfl (fun x hx ↦ ?_)
      simp only [← h, LinearMap.coe_comp, Function.comp_apply]
      rfl
    _ = exteriorPower.map i f ((koszulComplex.dAlternating φ i) v) := by
      rw [koszulComplex.dAlternating, AlternatingMap.alternatizeUncurryFin_apply]
      simp [map_sum, map_smul, exteriorPower.map_apply_ιMulti]

lemma map_d_comm (f : M →ₗ[R] N) (φ' : N →ₗ[R] R) (h : φ' ∘ₗ f = φ) (i : ℕ) :
    ModuleCat.ofHom (exteriorPower.map (i + 1) f) ≫ ModuleCat.ofHom (koszulComplex.d φ' i) =
      ModuleCat.ofHom (koszulComplex.d φ i) ≫ ModuleCat.ofHom (exteriorPower.map i f) := by
  ext v
  simp [koszulComplex.d, map_dAlternating_apply (φ := φ) (f := f) (φ' := φ') h]

/-- The map between two Koszul complex when give a linear map between module that commute with
two defining linear maps. -/
noncomputable def map (f : M →ₗ[R] N) (φ' : N →ₗ[R] R) (h : φ' ∘ₗ f = φ) :
    koszulComplex φ ⟶ koszulComplex φ' :=
  ChainComplex.ofHom
    (fun i ↦ ModuleCat.ofHom (exteriorPower.map i f))
    (fun i ↦ by simpa [d_eq_d] using! map_d_comm φ f φ' h i)

variable {L : Type v} [AddCommGroup L] [Module R L]

lemma map_comp (f : M →ₗ[R] N) (φ' : N →ₗ[R] R) (g : N →ₗ[R] L) (φ'' : L →ₗ[R] R)
    (h : φ' ∘ₗ f = φ) (h' : φ'' ∘ₗ g = φ') (h'' : φ'' ∘ₗ g ∘ₗ f = φ) :
    koszulComplex.map φ f φ' h ≫ koszulComplex.map φ' g φ'' h' =
      koszulComplex.map φ (g ∘ₗ f) φ'' h'' := by
  ext i x
  simp [map, X_eq_exteriorPower, exteriorPower.map_comp]

/-- The map between two Koszul complex when give an linear equiv between module that commute with
two defining linear maps. -/
noncomputable def isoOfEquiv (f : M ≃ₗ[R] N) (φ' : N →ₗ[R] R) (h : φ' ∘ₗ f = φ) :
    koszulComplex φ ≅ koszulComplex φ' where
  hom := koszulComplex.map φ f φ' h
  inv := koszulComplex.map φ' f.symm φ ((f.comp_toLinearMap_symm_eq φ' φ).mpr h.symm)
  hom_inv_id := by
    ext i x
    simp [map, X_eq_exteriorPower, ← exteriorPower.map_comp]
  inv_hom_id := by
    ext i x
    simp [map, X_eq_exteriorPower, ← exteriorPower.map_comp]

end functoriality

lemma isZero_X_of_card_generators_lt {ι : Type*} [Finite ι] [LinearOrder ι] (g : ι → M)
    (hg : Submodule.span R (Set.range g) = ⊤) (i : ℕ) (hi : Nat.card ι < i) :
    IsZero ((koszulComplex φ).X i) :=
  ModuleCat.isZero_of_iff_subsingleton.mpr
    (exteriorPower.subsingleton_of_span_eq_top_of_card_lt g hg i hi)

lemma isZero_X_ofList_of_length_lt (l : List R) (i : ℕ) (hi : l.length < i) :
    IsZero ((ofList l).X i) := isZero_X_of_card_generators_lt _
  (Pi.basisFun R (Fin l.length)) (Pi.basisFun R (Fin l.length)).span_eq i
  (by simpa [Nat.card_eq_fintype_card] using hi)

end koszulComplex
