/-
Copyright (c) 2026 Jovan Gerbscheid. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jovan Gerbscheid, Michael Rothgang, Damiano Testa, Kim Morrison
-/
module

-- Import this linter explicitly to ensure that
-- this file has a valid copyright header and module docstring.
public import Mathlib.Tactic.Linter.Header  -- shake: keep

/-!
# Syntax based linters

This file defines a linter that combines many differen linters that each operate directly on
the `Syntax`. This approach of combining the linters into a single loop is more efficient than
having each linter do this by itself.
-/

meta section

namespace Mathlib.Linter

open Lean Linter Elab.Command

/-! ### The `cdot` linter -/

/--
The `cdot` linter flags uses of a dot (`.`) that could instead be a "cdot" (`·`).
It also flags "isolated cdots", i.e. when the `·` is on its own line.
-/
public register_option linter.style.cdot : Bool := {
  defValue := false
  descr := "enable the `cdot` linter"
}

/-- Run the cdot linter, given that `stx` has kind `cdotTk` or `Lean.Parser.Term.cdot`. -/
def cdotLinter (stx : Syntax) : CommandElabM Unit := do
  -- let .node info kind args := stx | unreachable!
  if let .atom _ dot := stx[0] then
    if dot != "·" then
      logLintIf linter.style.cdot stx
        m!"Please, use '·' (typed as `\\.`) instead of '.' as 'cdot'."
  -- We also check for isolated cdot's, i.e. when the cdot is on its own line.
  -- Apply this only to cdot tactics
  if stx.isOfKind ``cdotTk then
    if let some trailingWhitespace := stx.getTrailing? then
      if (trailingWhitespace.takeWhile (·.isWhitespace)).contains '\n' then
        Linter.logLintIf linter.style.cdot stx
          m!"This central dot `·` is isolated; please merge it with the next line."


/-! ### The `dollarSyntax` linter -/

/--
The `dollarSyntax` linter flags uses of `$` that could instead be `<|`.
These are disallowed by the mathlib style guide, as using `<|` pairs better with `|>`.
-/
public register_option linter.style.dollarSyntax : Bool := {
  defValue := false
  descr := "enable the `dollarSyntax` linter"
}

/-- Run the dollar syntax linter, given that `stx` has kind `term_$__`. -/
def dollarLinter (stx : Syntax) : CommandElabM Unit := do
  Linter.logLintIf linter.style.dollarSyntax stx
    m!"Please use '<|' instead of '$' for the pipe operator."


/-! ### The `lambdaSyntax` linter -/

/--
The `lambdaSyntax` linter flags uses of the symbol `λ` to define anonymous functions.
This is syntactically equivalent to the `fun` keyword; mathlib style prefers using the latter.
-/
public register_option linter.style.lambdaSyntax : Bool := {
  defValue := false
  descr := "enable the `lambdaSyntax` linter"
}

/-- Run the lambda syntax linter, given that `stx` has kind `Lean.Parser.Term.fun`. -/
def lambdaLinter (stx : Syntax) : CommandElabM Unit := do
  if let .atom _ "λ" := stx[0] then
    Linter.logLintIf linter.style.lambdaSyntax stx[0] m!"\
      Please use 'fun' and not 'λ' to define anonymous functions.\n\
      The 'λ' syntax is deprecated in mathlib4."


/-! ### The auxiliary declaration linter -/

/--
The `auxLemma` linter flags explicit references to auto-generated "auxiliary" declarations
such as `_proof_1`, `match_1`, or `_sizeOf_1`.

These names are internal implementation details generated by the Lean elaborator.
They are not stable across refactors (e.g. reordering fields in a structure can renumber
`_proof_` indices), so depending on them makes code fragile.
-/
public register_option linter.auxLemma : Bool := {
  defValue := true
  descr := "enable the `auxLemma` linter"
}

/-- Returns `true` if `s` has the form `pfx ++ digits`, e.g. `"_proof_17"`. -/
@[inline] def matchesAuxPattern (pfx : String) (s : String) : Bool :=
  s.startsWith pfx && (s.drop pfx.length).all (·.isDigit) && s.rawEndPos > pfx.rawEndPos

/-- Returns `true` if `s` is an auto-generated auxiliary name component,
such as `_proof_1`, `match_2`, or `_sizeOf_3`. -/
def isAuxName (s : String) : Bool :=
  matchesAuxPattern "_proof_" s ||
  matchesAuxPattern "match_" s ||
  matchesAuxPattern "_sizeOf_" s ||
  matchesAuxPattern "_simp_" s ||
  matchesAuxPattern "_aux_" s

/-- Returns `true` if any component of the name is an auto-generated auxiliary name. -/
def nameRefersToAuxLemma : Name → Bool
  | .str p s => isAuxName s || nameRefersToAuxLemma p
  | .num p _ => nameRefersToAuxLemma p
  | .anonymous => false

/-- Run the aux lemma linter, given that `stx` is an `ident`. -/
def auxLemmaLinter (stx : Syntax) : CommandElabM Unit := do
  if nameRefersToAuxLemma stx.getId then
    logLintIf linter.auxLemma stx
      m!"`{stx.getId}` refers to an auto-generated auxiliary declaration. \
        These are not stable across refactors; consider using a different approach."


/-!
### Linter for `attribute [...] in`

Linter for global attributes created via `attribute [...] in`.

The syntax `attribute [instance] instName in` can be used to accidentally create a global instance.
This is **not** obvious from reading the code, and in fact happened twice during the port,
hence, we lint against it.

*Example*: before this was discovered, `Mathlib/Topology/Category/TopCat/Basic.lean`
contained the following code:
```
attribute [instance] HasForget.instFunLike in
instance (X Y : TopCat.{u}) : CoeFun (X ⟶ Y) fun _ => X → Y where
  coe f := f
```
Despite the `in`, this makes `HasForget.instFunLike` a global instance.

This seems to apply to all attributes. For example:
```lean
theorem what : False := sorry

attribute [simp] what in
#guard true

-- the `simp` attribute persists
example : False := by simp  -- `simp` finds `what`

theorem who {x y : Nat} : x = y := sorry

attribute [ext] who in
#guard true

-- the `ext` attribute persists
example {x y : Nat} : x = y := by ext
```
Therefore, we lint against this pattern on all instances.

For *removing* attributes, the `in` works as expected.
```lean
/--
error: failed to synthesize
  Add Nat
-/

#guard_msgs in
attribute [-instance] instAddNat in
#synth Add Nat

-- the `instance` persists
/-- info: instAddNat -/
#guard_msgs in
#synth Add Nat

@[simp]
theorem what : False := sorry

/-- error: simp made no progress -/
#guard_msgs in
attribute [-simp] what in
example : False := by simp

-- the `simp` attribute persists
#guard_msgs in
example : False := by simp
```
-/

/--
Flag any occurrence of `attribute [...] name in` which is not `local`, `scoped` or negated (`-`):
these are a footgun, as the attribute is applied *globally* (despite the `in`).
-/
public register_option linter.globalAttributeIn : Bool := {
  defValue := true
  descr := "enable the globalAttributeIn linter"
}

/-- Run the global attribute in linter, given that `stx` has kind `Lean.Parser.Command.in` -/
def globalAttributeInLinter (stx : Syntax) : CommandElabM Unit := do
  if let `(attribute [$attrs,*] $id) := stx[0] then
    for attr in attrs.getElems do
      match attr with
      | `(Parser.Command.eraseAttr| -$_) => pure ()
      | `(Parser.Term.attrInstance| local $_attr:attr) => pure ()
      | `(Parser.Term.attrInstance| scoped $_attr:attr) => pure ()
      | `(attr| $attr) =>
        Linter.logLintIf linter.globalAttributeIn attr m!
          "Despite the `in`, the attribute '{attr}' is added globally to '{id}'\n\
          please remove the `in` or make this a `local {attr}`"


/-!
### The `oldObtain` linter, against stream-of-consciousness `obtain`

The `oldObtain` linter flags any occurrences of "stream-of-consciousness" `obtain`,
i.e. uses of the `obtain` tactic which do not immediately provide a proof.

#### Example

There are six different kinds of `obtain` uses. In one example, they look like this.
```
theorem foo : True := by
  -- These cases are fine.
  obtain := trivial
  obtain h := trivial
  obtain : True := trivial
  obtain h : True := trivial
  -- These are linted against.
  obtain : True
  · trivial
  obtain h : True
  · trivial
```
We allow the first four (since an explicit proof is provided), but lint against the last two.

#### Why is this bad?

This is similar to removing all uses of `Tactic.Replace` and `Tactic.Have`
from mathlib: in summary,
- this version is a Lean3-ism, which can be unlearned now
- the syntax `obtain foo : type := proof` is slightly shorter;
  particularly so when the first tactic of the proof is `exact`
- when using the old syntax as `obtain foo : type; · proof`, there is an intermediate state with
  multiple goals right before the focusing dot. This can be confusing.
- the old syntax *could* be slightly nicer when deferring goals: however, this is rare.
  In the 30 replacements of the last PR, this occurred twice. In both cases, the `suffices` tactic
  could also be used, as was in fact clearer.
-/

/--
The `oldObtain` linter flags uses of the "stream-of-consciousness" variants of the `obtain`
tactic, i.e. with the proof postponed.
-/
public register_option linter.oldObtain : Bool := {
  defValue := false
  descr := "enable the `oldObtain` linter"
}

/-- Run the `oldObtain` linter, given that `stx` has kind `Lean.Parser.Tactic.obtain`. -/
def obtainLinter (stx : Syntax) : CommandElabM Unit := do
  if stx[3].isNone then
    Linter.logLint linter.oldObtain stx m!"Please remove stream-of-consciousness `obtain` syntax"


/-! ### The combined syntax linter -/

partial def lintSyntax (stx : Syntax) : CommandElabM Unit := do
  match stx with
  | .ident .. => auxLemmaLinter stx
  | .node _ kind args =>
    args.forM lintSyntax
    match kind with
    | ``cdotTk | ``Lean.Parser.Term.cdot => cdotLinter stx
    | ``«term_$__» => dollarLinter stx
    | ``Lean.Parser.Term.fun => lambdaLinter stx
    | ``Lean.Parser.Command.in => globalAttributeInLinter stx
    | ``Lean.Parser.Tactic.obtain => obtainLinter stx
    | _ => pure ()
  | _ => pure ()

def syntaxBasedLinter : Linter where
  run := withSetOptionIn fun stx ↦ do
    if ← MonadLog.hasErrors then
      return
    lintSyntax stx

initialize addLinter syntaxBasedLinter

end Mathlib.Linter
