name: Build Status Check

on:
  workflow_run:
    workflows: ["continuous integration", "continuous integration (mathlib forks)"]
    types:
      - completed

jobs:
  build-status:
    name: Build Status
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Mark as successful
        run: |
          echo "Build workflow completed successfully"
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
