on:
  pull_request:
    types: [labeled, unlabeled]
    branches:
      - '**/ci_debug_**'

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
