name: Dependent Issues

on:
  schedule:
    - cron: '*/15 * * * *' # run every 15 minutes
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Log the changes that would be made, without making them'
        type: boolean
        default: false

# Don't run concurrently. A run started while another one is in progress waits for it to finish.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'
    timeout-minutes: 30
    permissions:
      id-token: write
    steps:
      - name: Generate app token
        id: app-token
        uses: leanprover-community/mathlib-ci/.github/actions/azure-create-github-app-token@d6393a535c054122e507b6c5e1b2f4c31c604121
        with:
          app-id: ${{ secrets.MATHLIB_DEPENDENT_ISSUES_APP_ID }}
          key-vault-name: ${{ vars.MATHLIB_AZ_KEY_VAULT_NAME }}
          key-name: mathlib-dependent-issues-app-pk
          azure-client-id: ${{ vars.GH_APP_AZURE_CLIENT_ID_LABEL_BOTS }}
          azure-tenant-id: ${{ secrets.LPC_AZ_TENANT_ID }}
      - uses: leanprover-community/dependent-issues@642c46aafe7b8a799f4052dc4297e8e245e16f47
        env:
          # (Required) The token to use to make API calls to GitHub.
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          # (Optional) The label to use to mark dependent issues
          label: blocked-by-other-PR

          # (Optional) Enable checking for dependencies in issues. Enable by
          # setting the value to "on". Default "off"
          check_issues: off

          # (Optional) Set a commit status on PRs. Default "on"
          commit_status: off

          # (Optional) Log the changes that would be made without making them.
          dry_run: ${{ inputs.dry_run && 'on' || 'off' }}

          # (Optional) A comma-separated list of keywords. Default
          # "depends on, blocked by"
          keywords: "- \\[ \\] depends on:,- \\[x\\] depends on:"
