name: Export workflow telemetry

on:
  workflow_run:
    workflows:
      # The *names* of the workflows to collect telemetry for
      - "continuous integration"
      - "continuous integration (mathlib forks)"
      - "continuous integration (staging)"
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  otel-export:
    if: ${{ github.repository == 'leanprover-community/mathlib4' || github.repository == 'leanprover-community/mathlib4-nightly-testing' }}
    runs-on: ubuntu-latest
    steps:
      - name: Export workflow telemetry
        uses: corentinmusard/otel-cicd-action@895874bfae14f840e3032f1a14c3f2b45c93f4af # v4.1.1
        with:
          otlpEndpoint: ${{ vars.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          otelServiceName: "mathlib-ci"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
