name: Compute transitive imports

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y jq
        # If you have additional dependencies, install them here

    - name: Get changed files
      run: |
        git fetch origin ${{ github.base_ref }}  # fetch the base branch
        git diff --name-only origin/${{ github.base_ref }}... > changed_files.txt  # get the list of changed files

    - name: Compute transitive imports
      run: |
        # the checkout dance, to avoid a detached head
        git checkout master
        git checkout -
        currentHash="$(git rev-parse HEAD)"

        # Compute the counts for the HEAD of the PR
        python ./scripts/count-trans-deps.py "Mathlib/" > head.json

        # Checkout the merge base
        git checkout "$(git merge-base master ${{ github.sha }})"
        # git checkout origin/master scripts/count-trans-deps.py scripts/import-graph-report.py
        # get the files that we need from the current PR
        # ***switch*** to `origin/master`, when merging or right after
        git checkout origin/adomani/move_decls_autocomment_dev scripts/update_PR_comment.sh

        # Compute the counts for the merge base
        python ./scripts/count-trans-deps.py "Mathlib/" > base.json

        # switch back to the current branch: the `no_lost_declarations` script should be here
        git checkout "${currentHash}"
    - name: Compare results and comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR="${{ github.event.pull_request.number }}"
        title="### PR summary"

        ## Import count comment
        importCount=$(python ./scripts/import-graph-report.py base.json head.json changed_files.txt)

        ## Declarations' diff comment
        declDiff=$(./scripts/no_lost_declarations.sh short)

        message="$(printf '%s\n\n%s\n\n---\n\n%s\n' "${title}" "${importCount}" "${declDiff}")"

        ./scripts/update_PR_comment.sh "${message}" "${title}" "${PR}"
