name: LeanDeclDiff

on:
  workflow_run:
    workflows:
      - "continuous integration"
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env

      - name: decl-diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref }}
          PR: ${{ github.event.number }}
        run: |
          title="### Lean declaration difference"

          git checkout master
          git checkout -

          ## Lean declarations diff comment
          ddiff="$(./scripts/decls_diff_hybrid.sh "${{ github.sha }}" "$(git merge-base master ${{ github.sha }})")"
          if [ "$(printf '%s' "${ddiff}" | wc -l)" -gt 12 ]
          then
            ddiff="$(printf '<details><summary>\n\n%s\n\n</summary>\n\n%s\n\n</details>\n' "Report" "${ddiff}")"
          #else
          #  ddiff="$(printf '%s\n\n%s\n' "${title}" "${ddiff}")"
          fi

          echo "Message: ${ddiff}"

          git checkout "${BRANCH_NAME}"
          currentHash="$(git rev-parse HEAD)"
          hashURL="https://github.com/${{ github.repository }}/pull/${PR}/commits/${currentHash}"

          message="$(printf '%s [%s](%s)\n\n%s\n\n' "${title}" "$(git rev-parse --short HEAD)" "${hashURL}" "${ddiff}")"

          ./scripts/update_PR_comment.sh "${message}" "${title}" "${PR}"
