on:
  pull_request

name: lint and suggest

jobs:
  lint_and_suggest:
    if: github.repository == 'leanprover-community/mathlib4' && github.event.pull_request.draft == false
    name: Lint and suggest
    runs-on: ubuntu-latest
    steps:
      - uses: leanprover-community/lint-style-action@91923b046cc6a468e9ae340f32f8defe586bd08f # 2026-05-12
        with:
          mode: suggest
          lint-bib-file: true
