name: build and deploy mathlib3 docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *' # every 8 hours
jobs:
  build:
    name: build and deploy mathlib4 docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: get cache
        run: lake exe cache get

      - name: build mathlib
        run: env LEAN_ABORT_ON_PANIC=1 lake build

      - name: generate and deploy docs
        if: github.repository == 'leanprover-community/mathlib4'
        run: |
          cd ../
          ./mathlib4/scripts/deploy_docs.sh
        env:
          MATHLIB4_DOCS_KEY: ${{ secrets.MATHLIB4_DOCS_KEY }}
