name: Merge conflicts

on:
  schedule:
    - cron: '*/15 * * * *' # run every 15 minutes
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Generate app token
        id: app-token
        uses: ./.github/actions/azure-create-github-app-token
        with:
          app-id: ${{ secrets.MATHLIB_MERGE_CONFLICTS_APP_ID }}
          key-vault-name: ${{ vars.MATHLIB_AZ_KEY_VAULT_NAME }}
          key-name: mathlib-merge-conflicts-app-pk
          azure-client-id: ${{ vars.LABEL_BOTS_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.MATHLIB_CI_TENANT_ID }}
          azure-subscription-id: ${{ secrets.MATHLIB_CI_SUBSCRIPTION_ID }}

      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: "merge-conflict"
          commentOnDirty: "This pull request has conflicts, please merge `master` and resolve them."
          repoToken: ${{ steps.app-token.outputs.token }}
