name: Monthly Deprecated Alias Removal

on:
  schedule:
    - cron: '0 0 2 * *'  # Run at midnight UTC on the 2nd of each month
  workflow_dispatch:

jobs:
  remove-deprecated-aliases:
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Remove deprecated aliases
      run: |
        # Calculate date from 6 months ago
        SIX_MONTHS_AGO=$(date -d '6 months ago' +%Y-%m)
        echo "Removing deprecated aliases from $SIX_MONTHS_AGO..."
        
        # Build regex pattern with the calculated date
        PATTERN="(^@\[deprecated.*since.*${SIX_MONTHS_AGO}.*\]\n?\s*(noncomputable )?(protected )?alias\n?\s*[A-Za-z0-9_.'"'"'?!₀ℒ]+ :=\n?\s*[A-Za-z0-9_.'"'"'?!₀]+\n)+\n"
        
        find Mathlib/ -name "*.lean" -type f -exec perl -i -0pe "s/${PATTERN}//gm" {} +
        
    - name: Check if changes were made
      id: check_changes
      run: |
        if git diff --exit-code; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No deprecated aliases found to remove"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Found and removed deprecated aliases"
        fi

    - name: Run lake build
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        lake build

    - name: Create PR
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        BRANCH_NAME="deprecations_$(date +%Y-%m-%d)"
        SIX_MONTHS_AGO=$(date -d '6 months ago' +%Y-%m)
        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        git checkout -b "$BRANCH_NAME"
        git add -A
        git commit -m "chore: remove deprecated aliases from ${SIX_MONTHS_AGO}"
        
        git push origin "$BRANCH_NAME"
        
        gh pr create \
          --title "chore: remove deprecated aliases from ${SIX_MONTHS_AGO}" \
          --body "This PR automatically removes deprecated aliases that were marked for removal in ${SIX_MONTHS_AGO} (6 months ago).

        Generated by the monthly deprecated alias removal workflow." \
          --base master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}