name: update nolints

on:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 UTC on Sunday.
  workflow_dispatch:

jobs:
  build:
    name: Build, lint and update nolints and style exceptions
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure Lean
        uses: leanprover/lean-action@c544e89643240c6b398f14a431bcdc6309e36b3e # v1.4.0
        with:
          auto-config: false
          use-github-cache: false
          use-mathlib-cache: true

      - name: update nolints.json
        shell: bash
        run: |
          env LEAN_ABORT_ON_PANIC=1 lake exe runLinter --trace --update Mathlib

      - name: Generate app token
        id: app-token
        uses: leanprover-community/mathlib-ci/.github/actions/azure-create-github-app-token@3bb576208589a435eeaeac9b144a1b7c3e948760
        with:
          app-id: ${{ secrets.MATHLIB_NOLINTS_APP_ID }}
          key-vault-name: ${{ vars.MATHLIB_AZ_KEY_VAULT_NAME }}
          key-name: mathlib-nolints-app-pk
          azure-client-id: ${{ vars.GH_APP_AZURE_CLIENT_ID_PR_WRITERS }}
          azure-tenant-id: ${{ secrets.LPC_AZ_TENANT_ID }}

      # This token is masked by the token minting action and will not be logged accidentally.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          # this needs to be set, otherwise the last person who edited the `cron` line may get tagged
          author: "mathlib-nolints[bot] <258989889+mathlib-nolints[bot]@users.noreply.github.com>"
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore(scripts): update nolints.json"
          branch: "nolints"
          base: master
          title: "chore(scripts): update nolints.json"
          body: |
            I am happy to remove some nolints for you!

            ---

            [workflow run for this PR](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: "auto-merge-after-CI"
