name: Remove outdated deprecations

on:
  schedule:
    - cron: "5 4 * * 1" # At 04:05, on Monday
  workflow_dispatch:

jobs:
  build:
    name: Remove deprecations
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ## fetch the whole repository, as we want to push to it later
          fetch-depth: 0

      # - name: Configure Lean
      #   uses: leanprover/lean-action@f807b338d95de7813c5c50d018f1c23c9b93b4ec # 2025-04-24
      #   with:
      #     auto-config: false
      #     use-github-cache: false
      #     use-mathlib-cache: false

      - name: remove deprecations
        id: remove
        shell: bash
        run: |
          # requirements:
          # - must leave the mathlib4 repo in a state that is ready to commit and push
          # - must assign a step output named `deprecation_date` containing the cutoff date for removed deprecations

      - name: configure git setup
        run: |
          git remote add origin-bot "https://leanprover-community-bot:${{ secrets.UPDATE_NOLINTS_TOKEN }}@github.com/leanprover-community/mathlib4.git"
          git config user.email "leanprover.community@gmail.com"
          git config user.name "leanprover-community-bot"

          # By default, github actions overrides the credentials used to access any
          # github url so that it uses the github-actions[bot] user.  We want to access
          # github using a different username.
          git config --unset http.https://github.com/.extraheader

      - name: file a new PR to remove deprecations
        id: pr
        run: ./scripts/remove_deprecations_CI.sh
        env:
          DEPLOY_GITHUB_TOKEN: ${{ secrets.UPDATE_NOLINTS_TOKEN }}
          DEPRECATION_DATE: ${{ steps.remove.outputs.deprecation_date }}

      - name: Send Zulip message
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'nightly-testing'
          type: 'stream'
          topic: 'Mathlib `remove deprecations`'
          content: |
            ${{ steps.pr.outputs.message }}
