name: splice-bot

on:
  pull_request_review_comment:
    types: [created]

permissions: {}

jobs:
  call-splice-bot:
    if: ${{ contains(github.event.comment.body, 'splice-bot') }}
    uses: leanprover-community/SpliceBot/.github/workflows/splice.yaml@d86d20efffbd18f839199fdd5ec126570f7eceda # master
    with:
      # Optional override; omit to use the reusable workflow's default "master"
      base_ref: master
